Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2022-10, with the labels that each got.

#1201 Feature/multichainid
  aggregator/aggregator.go
  aggregator/aggregator_internal_test.go
  aggregator/config.go
  cmd/run.go
  docker-compose.yml
  etherman/etherman.go
  etherman/simulated.go
  etherman/smartcontracts/abi/proofofefficiency.abi
  etherman/smartcontracts/bin/proofofefficiency.bin
  etherman/smartcontracts/proofofefficiency/proofofefficiency.go
  merkletree/pb/statedb.pb.go
  merkletree/pb/statedb_grpc.pb.go
  proto/src/proto/executor/v1/executor.proto
  proto/src/proto/zkprover/v1/zk_prover.proto
  proverclient/pb/zk_prover.pb.go
  proverclient/pb/zk_prover_grpc.pb.go
  sequencer/broadcast/pb/broadcast.pb.go
  sequencer/broadcast/pb/broadcast_grpc.pb.go
  state/converters.go
  state/runtime/executor/pb/executor.pb.go
  state/state.go
  state/state_test.go
  test/contracts/bin/Counter/Counter.go
  test/contracts/bin/DelegatecallReceiver/DelegatecallReceiver.go
  test/contracts/bin/DelegatecallSender/DelegatecallSender.go
  test/contracts/bin/Destruct/Destruct.go
  test/contracts/bin/Double/Double.go
  test/contracts/bin/ERC20/ERC20.go
  test/contracts/bin/EmitLog/EmitLog.go
  test/contracts/bin/EmitLog2/EmitLog2.go
  test/contracts/bin/FailureTest/FailureTest.go
  test/contracts/bin/Interaction/Interaction.go
  test/contracts/bin/Read/Read.go
  test/contracts/bin/Revert/Revert.go
  test/contracts/bin/Revert2/Revert2.go
  test/contracts/bin/Storage/Storage.go
  test/contracts/bin/StorageOnDeploy/StorageOnDeploy.go
  test/contracts/bin/WETH/WETH.go
  test/contracts/bin/uniswap/v2/core/UniswapV2ERC20/UniswapV2ERC20.go
  test/contracts/bin/uniswap/v2/core/UniswapV2Factory/UniswapV2Factory.go
  test/contracts/bin/uniswap/v2/core/UniswapV2Pair/UniswapV2Pair.go
  test/contracts/bin/uniswap/v2/interface/UniswapInterfaceMulticall/UniswapInterfaceMulticall.go
  test/contracts/bin/uniswap/v2/periphery/UniswapV2Migrator/UniswapV2Migrator.go
  test/contracts/bin/uniswap/v2/periphery/UniswapV2Router02/UniswapV2Router02.go
  tools/zkevmprovermock/server/executor.go
Labels: cla-signed

#1203 Remove ChainID from config files
  aggregator/aggregator_internal_test.go
  config/network.go
  config/network_test.go
Labels: cla-signed

#1082 Potential fix oversized data
  Makefile
  aggregator/mocks/mock_etherman.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_proverclient.go
  aggregator/mocks/mock_state.go
  etherman/etherman.go
  ethtxmanager/interfaces.go
  go.mod
  go.sum
  sequencer/config.go
  sequencer/interfaces.go
  sequencer/sequencer_test.go
  sequencer/sequencesender.go
Labels: cla-signed

#1208 Change batch data size
  pool/pool.go
  pool/pool_test.go
  sequencer/batchbuilder.go
Labels: cla-signed

#1209 get tx by hash considers the pool
  jsonrpc/eth.go
  jsonrpc/eth_test.go
  jsonrpc/interfaces.go
  jsonrpc/mock_pool_test.go
  jsonrpc/types.go
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
Labels: cla-signed

#1197 deleted inmemory sequencer data
  aggregator/aggregator.go
  sequencer/batchbuilder.go
  sequencer/closingchecker.go
  sequencer/sequencer.go
  sequencer/sequencesender.go
  state/pgstatestorage.go
Labels: cla-signed

#1212 Add maxbatchsize config
  config/config.debug.toml
  config/config.go
  config/config.local.toml
  config/config_test.go
  config/default.go
  sequencer/config.go
  sequencer/sequencer_test.go
  sequencer/sequencesender.go
  test/config/config.test.toml
Labels: cla-signed

#1213 Try to add more txs when batch should be closed but it has no txs
  sequencer/batchbuilder.go
Labels: cla-signed

#1214 Add support for multiple provers in the aggregator
  Makefile
  aggregator/aggregator.go
  aggregator/aggregator_internal_test.go
  aggregator/config.go
  aggregator/interfaces.go
  aggregator/mocks/mock_proverclient.go
  aggregator/mocks/mock_state.go
  aggregator/prover/client.go
  aggregator/prover/prover.go
  cmd/run.go
  config/config.go
  config/config.local.toml
  db/migrations/state/0001.sql
  docker-compose.yml
  proverclient/config.go
  state/pgstatestorage.go
  test/config/config.test.toml
Labels: cla-signed

#1217 Revert batch data size to 30K
  pool/pool.go
  pool/pool_test.go
  sequencer/batchbuilder.go
Labels: cla-signed

#1224 fix connection counter
  jsonrpc/eth.go
  jsonrpc/handler.go
Labels: cla-signed

#1221 Improve aggregator tolerance to reboots
  aggregator/aggregator.go
  aggregator/aggregator_internal_test.go
  aggregator/interfaces.go
  aggregator/mocks/mock_etherman.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_proverclient.go
  aggregator/mocks/mock_state.go
  sequencer/mocks/mock_etherman.go
  state/pgstatestorage.go
Labels: cla-signed

#1226 Adds logs to estimate gas
  state/state.go
Labels: cla-signed

#1232 Improve gas estimation
  state/state.go
  state/state_test.go
Labels: cla-signed

#1231 Feature/update smc
  etherman/etherman.go
  etherman/smartcontracts/bin/bridge.bin
  etherman/smartcontracts/bin/globalexitrootmanager.bin
  etherman/smartcontracts/bin/mockverifier.bin
  etherman/smartcontracts/bin/proofofefficiency.bin
  etherman/smartcontracts/bridge/bridge.go
  etherman/smartcontracts/globalexitrootmanager/globalexitrootmanager.go
  etherman/smartcontracts/mockverifier/mockverifier.go
  etherman/smartcontracts/proofofefficiency/proofofefficiency.go
  test/operations/manager.go
Labels: cla-signed

#1236 Disable zkevmcounters during eth_call
  jsonrpc/eth.go
  jsonrpc/interfaces.go
  jsonrpc/mock_state_test.go
  proto/src/proto/executor/v1/executor.proto
  state/runtime/executor/pb/executor.pb.go
  state/state.go
  state/state_test.go
Labels: cla-signed

#1238 Fix/tx claims
  cmd/run.go
  config/network.go
  pool/pool.go
  pool/transaction.go
  pool/transaction_test.go
Labels: cla-signed

#1240 Add order by block_number when get logs in L2
  state/pgstatestorage.go
Labels: cla-signed

#1242 fixed todos for ethtxmanager.go
  config/config.debug.toml
  config/config.local.toml
  config/config_test.go
  config/default.go
  db/migrations/pool/0001.sql
  etherman/etherman.go
  ethtxmanager/config.go
  ethtxmanager/ethtxmanager.go
  ethtxmanager/interfaces.go
  test/config/config.test.toml
Labels: cla-signed

#1241 Migration down for failed_counter
  db/migrations/pool/0001.sql
  db/migrations/pool/0002.sql
Labels: cla-signed

#1249 Dont reduce precision when estimating gas for eth transfers
  state/state.go
Labels: cla-signed

#1253 Add option not to update StateDB when processing a batch
  state/state.go
Labels: cla-signed

#1256 Add deprecation warning
  docs/production-setup.md
  docs/running_local.md
Labels: cla-signed

#1257 Fix nil pointer exception when increasing gas price
  ethtxmanager/ethtxmanager.go
  ethtxmanager/ethtxmanager_test.go
Labels: cla-signed

#1259 Fix nonce on retry
  etherman/etherman.go
  ethtxmanager/ethtxmanager.go
  ethtxmanager/interfaces.go
Labels: cla-signed

#1272 Restore proper IP in tests
  state/state_test.go
Labels: cla-signed

#1278 fix event not registered
  etherman/etherman.go
Labels: cla-signed

#1280 Only delete null proofs
  aggregator/aggregator.go
  aggregator/interfaces.go
  aggregator/mocks/mock_state.go
  state/pgstatestorage.go
Labels: cla-signed

#1286 Reconnect to prover if connection breaks
  aggregator/aggregator.go
  aggregator/aggregator_internal_test.go
  aggregator/interfaces.go
  aggregator/mocks/mock_proverclient.go
  aggregator/prover/client.go
  aggregator/prover/prover.go
  config/config.go
Labels: cla-signed

#1291 Fixe aggregator restart
  aggregator/aggregator.go
  config/config.go
  ethtxmanager/ethtxmanager.go
Labels: cla-signed

#1294 Fix idle prover detection
  aggregator/aggregator.go
Labels: cla-signed

#1295 Remove fatal log
  aggregator/aggregator.go
  ethtxmanager/ethtxmanager.go
Labels: cla-signed

#1296 do not delete proofs
  aggregator/aggregator.go
Labels: cla-signed

#1297 Fix/wait cfg
  ethtxmanager/ethtxmanager.go
Labels: cla-signed

#1276 Fix non e2e tests
  jsonrpc/eth_test.go
  pool/pool_test.go
  pool/transaction.go
  sequencer/sequencer_test.go
Labels: cla-signed

#1211 Feature/#1145 genesis refactor
  cmd/approve.go
  cmd/dumpstate.go
  cmd/main.go
  cmd/run.go
  config/config.debug.toml
  config/config.go
  config/config.local.toml
  config/config_test.go
  config/default.go
  config/genesis.go
  config/genesis.local.json
  config/network.go
  config/network_test.go
  docker-compose.yml
  etherman/config.go
  etherman/etherman.go
  go.mod
  sequencer/sequencer_test.go
  synchronizer/config.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  tools/genesis/generator.go
Labels: cla-signed

#1255 Check added to checkTrustedState
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#1307 fixed not working deletion from the pool
  sequencer/sequencer.go
  state/pgstatestorage.go
Labels: cla-signed

#1305 trying to fix: "sequencer seems not to store the proper new state"
  sequencer/batchbuilder.go
  state/batch.go
  state/pgstatestorage.go
  state/state.go
Labels: cla-signed

#1127 Properly check tx hash in CheckSupersetBatchTransactions
  state/state.go
  state/state_test.go
Labels: cla-signed

#1312 approve without genesis
  cmd/approve.go
  config/network.go
  docker-compose.yml
Labels: cla-signed

#1313 Fix pointer log
  aggregator/aggregator.go
Labels: cla-signed

#1311 test/utils: provide 'ZKPROVER_URI' and 'MERKLETREE_URI' as env variables. [test/: operations/manager.go, e2e/boradcast_test.go]
  .gitignore
  test/constants/environment_variables.go
  test/e2e/broadcast_test.go
  test/operations/manager.go
Labels: cla-signed

#1314 Fix typos in aggregator
  aggregator/aggregator.go
Labels: cla-signed

#1316 fix the claim signature
  config/config.debug.toml
  pool/pool.go
Labels: cla-signed

#1319 add wait after verify batch mining tx
  ethtxmanager/ethtxmanager.go
Labels: cla-signed

#1322 fixed failed -> invalid
  pool/pgpoolstorage/pgpoolstorage.go
  sequencer/batchbuilder.go
  test/config/config.test.toml
Labels: cla-signed

#1325 new waitTx function
  aggregator/aggregator.go
  aggregator/interfaces.go
  aggregator/mocks/mock_ethtxmanager.go
  etherman/etherman.go
  ethtxmanager/ethtxmanager.go
  ethtxmanager/interfaces.go
  scripts/deploy_sc/main.go
  sequencer/interfaces.go
  sequencer/mocks/mock_txmanager.go
  sequencer/sequencesender.go
  test/e2e/ethtransfer_test.go
  test/e2e/pool_test.go
  test/e2e/sc_test.go
  test/operations/manager.go
  test/operations/wait.go
Labels: cla-signed

#1228 refactoring root docker-compose
  .github/workflows/release.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test-from-prover.yml
  .github/workflows/test-full-non-e2e.yml
  .github/workflows/updatedeps.yml
  Dockerfile
  Makefile
  config/default.go
  config/environments/local/debug.node.config.toml
  config/environments/local/local.genesis.config.json
  config/environments/local/local.node.config.toml
  config/environments/public/public.genesis.config.json
  config/environments/public/public.node.config.toml
  config/environments/public/public.prover.config.json
  config/example.keystore
  db/scripts/init_prover_db.sql
  db/scripts/single_db_server.sql
  docker-compose.yml
  docs/ci/groups.md
  test/Makefile
  test/config/test.genesis.config.json
  test/config/test.node.config.toml
  test/config/test.prover.config.json
  test/docker-compose.yml
  test/e2e/broadcast_test.go
  test/e2e/ethtransfer_test.go
  test/operations/manager.go
  test/scripts/cmd/compilesc.go
  test/scripts/cmd/compilesc/manager.go
  test/scripts/cmd/dependencies.go
  test/scripts/cmd/dependencies/files.go
  test/scripts/cmd/dependencies/files_test.go
  test/scripts/cmd/dependencies/github.go
  test/scripts/cmd/dependencies/github_test.go
  test/scripts/cmd/dependencies/images.go
  test/scripts/cmd/dependencies/images_test.go
  test/scripts/cmd/dependencies/manager.go
  test/scripts/cmd/dependencies/protobuffers.go
  test/scripts/cmd/dependencies/testvectors.go
  test/scripts/cmd/main.go
  test/scripts/deploy_sc/main.go
  test/scripts/init_network/main.go
  test/scripts/postgres/prover-user.sql
  test/scripts/postgres/run.sh
  test/scripts/uniswap/main.go
  tools/executor/docker-compose.yml
Labels: cla-signed

#1334 readd make generate-code-from-proto removed by mistake
  Makefile
Labels: cla-signed

#1258 JSONRPC L1/L2 Parity tests
  .github/workflows/test-e2e.yml
  ci/e2e-group1/ethtransfer_test.go
  ci/e2e-group1/shared.go
  ci/e2e-group1/state_test.go
  ci/e2e-group2/jsonrpc_test.go
  ci/e2e-group3/sc_test.go
  ci/e2e-group3/shared.go
  ci/e2e-group3/uniswap_test.go
  jsonrpc/eth.go
  jsonrpc/eth_test.go
  jsonrpc/pgstorage.go
  jsonrpc/query.go
  jsonrpc/types.go
  test/Makefile
  test/e2e/ethtransfer_test.go
  test/e2e/jsonrpc_test.go
  test/e2e/shared.go
Labels: cla-signed

#1333 improve: adding commit hash as env var in docker and printing it along with the version on start
  Dockerfile
  Makefile
  cmd/main.go
Labels: cmd, Improvement, cla-signed

#1326 refac: adding missing error wrapping.
  etherman/errors.go
  etherman/etherman.go
  ethtxmanager/ethtxmanager.go
  sequencer/batchbuilder.go
  sequencer/sequencer.go
  sequencer/sequencesender.go
  state/errors.go
  state/pgstatestorage.go
  state/state.go
  state/state_test.go
Labels: Improvement, EtherMan, cla-signed

#1332 Sequencer tests
  etherman/types/sequence.go
  sequencer/batchbuilder.go
  sequencer/closingchecker.go
  sequencer/mocks/mock_dbtx.go
  sequencer/mocks/mock_gaspriceestimator.go
  sequencer/mocks/mock_pool.go
  sequencer/mocks/mock_state.go
  sequencer/mocks/mock_txmanager.go
  sequencer/sequencer.go
  sequencer/sequencer_internal_test.go
  test/Makefile
Labels: cla-signed

#1340 PoC: retrying connection to executor
  state/runtime/executor/client.go
Labels: cla-signed

#1344 Add check for too many args
  jsonrpc/handler.go
  test/e2e/jsonrpc_test.go
Labels: cla-signed

#1342 improve: removing redundant db connections and running of migrations in Approve command.
  cmd/approve.go
Labels: cmd, Improvement, cla-signed

#1329 Feature/#1270 multi gasprice provider
  .github/workflows/test-e2e.yml
  aggregator/aggregator_internal_test.go
  cmd/approve.go
  config/default.go
  config/environments/local/debug.node.config.toml
  config/environments/local/local.node.config.toml
  config/environments/public/public.node.config.toml
  encoding/encoding.go
  etherman/config.go
  etherman/etherman.go
  etherman/etherman_test.go
  etherman/etherscan/etherscan.go
  etherman/etherscan/etherscan_test.go
  etherman/ethgasstation/ethgasstation.go
  etherman/ethgasstation/ethgasstation_test.go
  etherman/mock_etherscan.go
  etherman/mock_ethgasstation.go
  etherman/simulated.go
  ethtxmanager/ethtxmanager.go
  ethtxmanager/interfaces.go
  sequencer/sequencer_test.go
  test/Makefile
Labels: cla-signed

#1348 Feature/ger update
  config/config_test.go
  config/default.go
  config/environments/local/debug.node.config.toml
  config/environments/local/local.node.config.toml
  sequencer/batchbuilder.go
  sequencer/closingchecker.go
  sequencer/config.go
  sequencer/interfaces.go
  sequencer/mocks/mock_state.go
  sequencer/mocks/mock_txmanager.go
  sequencer/sequencer.go
  sequencer/sequencer_internal_test.go
  state/pgstatestorage.go
  state/state.go
  state/state_test.go
  test/Makefile
  test/config/test.node.config.toml
Labels: cla-signed
