Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2022-11, with the labels that each got.

#1352 revert reason
  test/operations/wait.go
Labels: cla-signed

#1321 Etherman optionally readonly.
  Makefile
  aggregator/aggregator.go
  aggregator/aggregator_internal_test.go
  aggregator/interfaces.go
  aggregator/mocks/mock_etherman.go
  cmd/run.go
  config/config_test.go
  config/default.go
  docker-compose.yml
  etherman/etherman.go
  etherman/etherman_test.go
  etherman/simulated.go
  ethtxmanager/ethtxmanager_test.go
  test/config/test.node.config.toml
Labels: Improvement, EtherMan, cla-signed

#1336 improve: making the timeout of the RPC server to be configurable and fixing deprecated func for creating temp file.
  config/config_test.go
  config/default.go
  config/environments/local/debug.node.config.toml
  config/environments/local/local.node.config.toml
  config/environments/public/public.node.config.toml
  jsonrpc/config.go
  jsonrpc/server.go
  test/config/test.node.config.toml
Labels: cla-signed

#1351 moves constants from batchbuilder to cfg
  config/config_test.go
  config/default.go
  config/environments/local/debug.node.config.toml
  config/environments/local/local.node.config.toml
  sequencer/batchbuilder.go
  sequencer/closingchecker.go
  sequencer/config.go
  sequencer/sequencer_internal_test.go
  test/config/test.node.config.toml
Labels: cla-signed

#1338 Fix debug_traceTransaction endpoint
  jsonrpc/debug.go
  jsonrpc/debug_test.go
  state/state.go
  test/tracers/tracer.json
Labels: cla-signed

#1335 Switch to infura RPC URL
  config/environments/local/local.node.config.toml
  config/environments/public/public.node.config.toml
Labels: EtherMan, cla-signed

#1362 Check for discrepancy: no contract code at given address
  test/e2e/jsonrpc_test.go
Labels: cla-signed

#1356 delay retry to connect to executor
  state/runtime/executor/client.go
Labels: cla-signed

#1359 improve: logging id of succesfully generated proof.
  aggregator/aggregator.go
Labels: Aggregator, Improvement, cla-signed

#1358 feat: adding new JSON-RPC enpoint 'BatchNumberOfL2Block'.
  jsonrpc/interfaces.go
  jsonrpc/mock_state_test.go
  jsonrpc/zkevm.go
  jsonrpc/zkevm_test.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
Labels: enhancement, RPC, cla-signed

#1376 test: fix test-full-non-e2e recipe
  config/config_test.go
  jsonrpc/eth_test.go
  state/state_test.go
  test/Makefile
Labels: bug, test, cla-signed

#892 Prometheus endpoint with metrics
  cmd/run.go
  config/config.go
  config/config_test.go
  config/default.go
  config/environments/local/debug.node.config.toml
  config/environments/local/local.node.config.toml
  config/environments/public/public.node.config.toml
  config/metrics/prometheus/prometheus.yml
  docker-compose.yml
  go.mod
  go.sum
  metrics/config.go
  metrics/prometheus.go
  metrics/prometheus_test.go
  test/Makefile
  test/config/test.node.config.toml
  test/docker-compose.yml
Labels: enhancement, cla-signed

#1383 fix: passing the empty txs array to the executor to update the state on closing a batch
  sequencer/batchbuilder.go
Labels: Sequencer, cla-signed

#1330 Revamp sequencer and aggregator integration with ethtxmanager
  aggregator/aggregator.go
  aggregator/interfaces.go
  aggregator/mocks/mock_ethtxmanager.go
  cmd/run.go
  config/config_test.go
  config/default.go
  config/environments/local/debug.node.config.toml
  config/environments/local/local.node.config.toml
  db/migrations/state/0002.sql
  db/migrations/state/0003.sql
  etherman/etherman.go
  etherman/etherman_test.go
  etherman/types/sequence.go
  ethtxmanager/config.go
  ethtxmanager/ethtxmanager.go
  ethtxmanager/ethtxmanager_test.go
  ethtxmanager/interfaces.go
  sequencer/batchbuilder.go
  sequencer/closingchecker.go
  sequencer/config.go
  sequencer/interfaces.go
  sequencer/mocks/mock_etherman.go
  sequencer/mocks/mock_state.go
  sequencer/mocks/mock_txmanager.go
  sequencer/profitabilitychecker/profitabilitychecker.go
  sequencer/profitabilitychecker/profitabilitychecker_test.go
  sequencer/sequencer.go
  sequencer/sequencer_internal_test.go
  sequencer/sequencer_test.go
  sequencer/sequencesender.go
  state/pgstatestorage.go
  state/proof.go
  state/sequence.go
  test/Makefile
  test/config/test.node.config.toml
  test/scripts/send_transfers/main.go
Labels: cla-signed

#1366 Batchsender script
  test/scripts/batchsender/README.md
  test/scripts/batchsender/main.go
Labels: cmd, cla-signed

#1384 Update/executor proto
  aggregator/prover/client.go
  db/migrations/state/0003.sql
  etherman/etherman_test.go
  go.mod
  go.sum
  proto/src/proto/executor/v1/executor.proto
  proverclient/pb/zk_prover.pb.go
  proverclient/pb/zk_prover_grpc.pb.go
  state/batch.go
  state/converters.go
  state/pgstatestorage.go
  state/runtime/executor/errors.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/executor/pb/executor_grpc.pb.go
  state/runtime/runtime.go
  state/state.go
  state/state_test.go
  state/types.go
  test/config/test.prover.config.json
  test/docker-compose.yml
  tools/executor/main.go
  tools/executor/vectors/fail-deploy-uniswap-repeated-nonce.json
Labels: cla-signed

#1347 Prod/running local Documentation updates
  config/environments/public/public.node.config.toml
  docs/networks.md
  docs/production-setup.md
  docs/running_local.md
Labels: cla-signed

#1391 Fix wrong vector folder in docker compose file
  test/docker-compose.yml
Labels: cla-signed

#1403 Update/executor proto
  config/environments/public/public.prover.config.json
  db/migrations/state/0003.sql
  db/scripts/init_prover_db.sql
  docker-compose.yml
  state/state_test.go
Labels: cla-signed

#1396 [batchsender] wait txs to be mined only once per tx
  test/scripts/batchsender/main.go
Labels: bug, cmd, cla-signed

#1399 fix: making 'tryParseError' to check if contains when no exact match.
  etherman/errors.go
  etherman/errors_test.go
Labels: bug, EtherMan, cla-signed

#1414 Correct gas estimation
  .gitignore
  state/state.go
  state/state_test.go
  test/contracts/auto/Storage.sol
  test/contracts/compiled/ERC20Token/ERC20Token.abi
  test/contracts/compiled/ERC20Token/ERC20Token.bin
  test/contracts/compiled/MultiSigWallet/MultiSigWallet.abi
  test/contracts/compiled/MultiSigWallet/MultiSigWallet.bin
Labels: cla-signed

#1417 Remove PrivateKey config keys from public node config file
  config/environments/public/public.node.config.toml
Labels: cla-signed

#1412 Feature/latest smc
  db/migrations/pool/0001.sql
  db/migrations/pool/0002.sql
  db/migrations/state/0001.sql
  db/migrations/state/0002.sql
  db/migrations/state/0003.sql
  etherman/etherman.go
  etherman/etherman_test.go
  etherman/simulated.go
  etherman/smartcontracts/abi/bridge.abi
  etherman/smartcontracts/abi/globalexitrootmanager.abi
  etherman/smartcontracts/abi/proofofefficiency.abi
  etherman/smartcontracts/bin/bridge.bin
  etherman/smartcontracts/bin/globalexitrootmanager.bin
  etherman/smartcontracts/bin/mockverifier.bin
  etherman/smartcontracts/bin/proofofefficiency.bin
  etherman/smartcontracts/bridge/bridge.go
  etherman/smartcontracts/globalexitrootmanager/globalexitrootmanager.go
  etherman/smartcontracts/mockverifier/mockverifier.go
  etherman/smartcontracts/proofofefficiency/proofofefficiency.go
  etherman/types.go
  merkletree/pb/statedb.pb.go
  merkletree/pb/statedb_grpc.pb.go
  proto/src/proto/broadcast/v1/broadcast.proto
  proverclient/pb/zk_prover.pb.go
  proverclient/pb/zk_prover_grpc.pb.go
  sequencer/broadcast/pb/broadcast.pb.go
  sequencer/broadcast/pb/broadcast_grpc.pb.go
  sequencer/broadcast/server.go
  sequencer/sequencer_internal_test.go
  sequencer/sequencer_test.go
  sequencer/sequencesender.go
  state/batch.go
  state/globalexitroot.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/executor/pb/executor_grpc.pb.go
  state/state_test.go
  synchronizer/synchronizer.go
  test/e2e/broadcast_test.go
Labels: cla-signed

#1416 Do not force amd64 architecture
  Makefile
Labels: cla-signed

#1424 Hotfix/sync2
  .gitignore
  aggregator/aggregator.go
  aggregator/aggregator_internal_test.go
  aggregator/interfaces.go
  aggregator/mocks/mock_state.go
  cmd/approve.go
  cmd/dumpstate.go
  cmd/main.go
  cmd/run.go
  config/config.debug.toml
  config/config.go
  config/config.local.toml
  config/config_test.go
  config/default.go
  config/genesis.go
  config/genesis.local.json
  config/network.go
  config/network_test.go
  db/migrations/state/0002.sql
  docker-compose.yml
  etherman/config.go
  etherman/etherman.go
  ethtxmanager/ethtxmanager.go
  go.mod
  go.sum
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/transaction.go
  sequencer/batchbuilder.go
  sequencer/config.go
  sequencer/sequencer.go
  sequencer/sequencer_test.go
  state/batch.go
  state/converters.go
  state/pgstatestorage.go
  state/proof.go
  state/state.go
  state/state_test.go
  synchronizer/config.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/config/config.test.toml
  test/constants/environment_variables.go
  test/e2e/broadcast_test.go
  test/operations/manager.go
  tools/genesis/generator.go
Labels: cla-signed

#1418 WaitTxToBeSynced
  cmd/run.go
  config/config_test.go
  config/default.go
  config/environments/local/debug.node.config.toml
  config/environments/local/local.node.config.toml
  ethtxmanager/config.go
  ethtxmanager/ethtxmanager.go
  ethtxmanager/ethtxmanager_test.go
  ethtxmanager/interfaces.go
  sequencer/sequencer_test.go
  state/pgstatestorage.go
  state/state.go
  state/state_test.go
Labels: cla-signed

#1413 Review some logging levels in JSON-RPC component
  jsonrpc/debug.go
  jsonrpc/eth.go
  jsonrpc/handler.go
Labels: RPC, cla-signed

#1425 Hotfix Synchronization
  state/converters.go
  state/state.go
Labels: cla-signed

#1426 add wait txs methods to state
  aggregator/aggregator.go
  aggregator/interfaces.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/prover/client.go
  aggregator/prover/prover.go
  cmd/run.go
  config/config.debug.toml
  config/config.local.toml
  config/config_test.go
  config/default.go
  ethtxmanager/config.go
  ethtxmanager/ethtxmanager.go
  ethtxmanager/interfaces.go
  sequencer/interfaces.go
  sequencer/mocks/mock_txmanager.go
  sequencer/sequencer_test.go
  sequencer/sequencesender.go
  state/pgstatestorage.go
  state/state.go
  test/config/config.test.toml
Labels: cla-signed

#1427 Improve prover integration with aggregator
  aggregator/aggregator.go
  aggregator/prover/client.go
  aggregator/prover/prover.go
Labels: cla-signed
