Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2022-12, with the labels that each got.

#1406 batchsender script: add --sequences flag
  test/scripts/batchsender/README.md
  test/scripts/batchsender/main.go
Labels: cmd, cla-signed

#1387 Fix: typos
  docs/production-setup.md
Labels: cla-signed

#1398 move debug config in test folder
  test/config/debug.node.config.toml
Labels: test, cla-signed

#1428 Doc node execution modes
  docs/components/account_keystore.md
  docs/components/aggregator.md
  docs/components/databases.md
  docs/components/prover.md
  docs/components/rpc.md
  docs/components/sequencer.md
  docs/components/synchronizer.md
  docs/modes.md
  docs/production-setup.md
Labels: documentation, cla-signed

#1419 Recursive Aggregator
  Makefile
  aggregator/aggregator.go
  aggregator/aggregator_internal_test.go
  aggregator/config.go
  aggregator/interfaces.go
  aggregator/mocks/mock_etherman.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_profitabilitychecker.go
  aggregator/mocks/mock_prover.go
  aggregator/mocks/mock_proverclient.go
  aggregator/mocks/mock_state.go
  aggregator/pb/aggregator.pb.go
  aggregator/pb/aggregator_grpc.pb.go
  aggregator/prover/client.go
  aggregator/prover/prover.go
  cmd/run.go
  config/config.go
  config/config_test.go
  config/default.go
  config/environments/local/debug.node.config.toml
  config/environments/local/local.node.config.toml
  db/migrations/state/0001.sql
  db/migrations/state/0002.sql
  db/scripts/init_prover_db.sql
  docs/production-setup.md
  etherman/converters.go
  etherman/etherman.go
  ethtxmanager/ethtxmanager.go
  ethtxmanager/ethtxmanager_test.go
  ethtxmanager/interfaces.go
  merkletree/pb/statedb.pb.go
  merkletree/pb/statedb_grpc.pb.go
  proto/src/proto/aggregator/v1/aggregator.proto
  proto/src/proto/zkprover/v1/zk_prover.proto
  proverclient/config.go
  proverclient/pb/zk_prover.pb.go
  proverclient/pb/zk_prover_grpc.pb.go
  sequencer/broadcast/pb/broadcast.pb.go
  sequencer/broadcast/pb/broadcast_grpc.pb.go
  sequencer/sequencer_test.go
  state/pgstatestorage.go
  state/proof.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/executor/pb/executor_grpc.pb.go
  state/state_test.go
  test/Makefile
  test/config/test.genesis.config.json
  test/config/test.node.config.toml
  test/config/test.prover.config.json
  test/docker-compose.yml
  test/scripts/batchsender/main.go
Labels: Aggregator, cla-signed

#1373 Add metrics in sequencer package
  metrics/prometheus.go
  metrics/prometheus_test.go
  sequencer/batchbuilder.go
  sequencer/interfaces.go
  sequencer/metrics/metrics.go
  sequencer/mocks/mock_state.go
  sequencer/profitabilitychecker/profitabilitychecker.go
  sequencer/sequencer.go
  sequencer/sequencer_internal_test.go
  sequencer/sequencesender.go
  state/metrics/metrics.go
  state/state.go
  state/state_test.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: Improvement, cla-signed

#1421 Add Grafana docker for visualization
  test/Makefile
  test/config/grafana/dashboard-dockers.json
  test/config/grafana/dashboard-node.json
  test/config/grafana/dashboards.yml
  test/config/grafana/datasources.yml
  test/config/telegraf.conf
  test/docker-compose.yml
Labels: cla-signed

#1361 Txsender script
  test/e2e/ethtransfer_test.go
  test/e2e/state_test.go
  test/operations/manager.go
  test/scripts/txsender/README.md
  test/scripts/txsender/main.go
Labels: cmd, cla-signed

#1439 Add preliminary Goreleaser config
  .goreleaser.yaml
Labels: cla-signed

#1441 Fix erroneous return in VerifyBatches function
  aggregator/aggregator.go
  ethtxmanager/ethtxmanager.go
Labels: bug, cla-signed

#1443 [Ethtxmanager] Fix VerifyBatches return
  aggregator/aggregator.go
  ethtxmanager/ethtxmanager.go
Labels: bug, cla-signed

#1401 Revamp logs
  Dockerfile
  Makefile
  cmd/main.go
  cmd/run.go
  cmd/version.go
  config/config.go
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/public/public.node.config.toml
  etherman/etherman.go
  etherman/etherman_test.go
  etherman/etherscan/etherscan_test.go
  etherman/ethgasstation/ethgasstation_test.go
  jsonrpc/handler.go
  log/config.go
  log/log.go
  log/log_test.go
  metrics/prometheus.go
  pool/pool_test.go
  test/Makefile
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/scripts/batchsender/main.go
  test/scripts/txsender/main.go
  version.go
  version.mk
Labels: Improvement, cla-signed

#1452 Update MaxBatchBytesSize
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  sequencer/sequencer_internal_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#1459 fix acc inputhash 2
  etherman/types/sequence.go
  sequencer/batchbuilder.go
Labels: cla-signed

#1455 [Aggregator] Send pub address on final proof request
  .goreleaser.yaml
  aggregator/aggregator.go
  aggregator/interfaces.go
  aggregator/mocks/mock_etherman.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_prover.go
  aggregator/mocks/mock_state.go
  aggregator/pb/aggregator.pb.go
  aggregator/prover/prover.go
  etherman/etherman.go
  etherman/types/finalproofinputs.go
  etherman/types/sequence.go
  ethtxmanager/ethtxmanager.go
  ethtxmanager/interfaces.go
  proto/src/proto/aggregator/v1/aggregator.proto
  sequencer/batchbuilder.go
Labels: bug, Aggregator, cla-signed

#1463 Backport RC3 changes into develop branch
  .goreleaser.yaml
  aggregator/aggregator.go
  aggregator/interfaces.go
  aggregator/mocks/mock_etherman.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_prover.go
  aggregator/mocks/mock_state.go
  aggregator/pb/aggregator.pb.go
  aggregator/prover/prover.go
  etherman/etherman.go
  etherman/types/finalproofinputs.go
  ethtxmanager/ethtxmanager.go
  ethtxmanager/interfaces.go
  proto/src/proto/aggregator/v1/aggregator.proto
Labels: cla-signed

#1447 test: adding sequencer benchmark test for - 'measuring the time needed to select 10000 txs from the pool'.
  .gitignore
  cmd/run.go
  metrics/api.go
  test/Makefile
  test/benchmarks/interfaces.go
  test/benchmarks/sequencer/pool_processing_test.go
  test/benchmarks/sequencer_test.go
  test/operations/manager.go
  test/testutils/utils.go
Labels: Sequencer, test, cla-signed

#1467 update poe sc to security mechanisms version
  aggregator/pb/aggregator.pb.go
  aggregator/pb/aggregator_grpc.pb.go
  config/environments/local/local.genesis.config.json
  config/network.go
  config/network_test.go
  db/migrations/state/0001.sql
  docker-compose.yml
  etherman/etherman.go
  etherman/etherman_test.go
  etherman/simulated.go
  etherman/smartcontracts/abi/bridge.abi
  etherman/smartcontracts/abi/proofofefficiency.abi
  etherman/smartcontracts/bin/bridge.bin
  etherman/smartcontracts/bin/proofofefficiency.bin
  etherman/smartcontracts/bridge/bridge.go
  etherman/smartcontracts/proofofefficiency/proofofefficiency.go
  etherman/types.go
  ethtxmanager/ethtxmanager.go
  ethtxmanager/interfaces.go
  merkletree/pb/statedb.pb.go
  merkletree/pb/statedb_grpc.pb.go
  proto/src/proto/broadcast/v1/broadcast.proto
  proto/src/proto/executor/v1/executor.proto
  sequencer/broadcast/pb/broadcast.pb.go
  sequencer/broadcast/pb/broadcast_grpc.pb.go
  sequencer/broadcast/server.go
  sequencer/interfaces.go
  sequencer/mocks/mock_etherman.go
  sequencer/profitabilitychecker/interfaces.go
  sequencer/profitabilitychecker/mocks/mock_etherman.go
  sequencer/profitabilitychecker/profitabilitychecker.go
  sequencer/profitabilitychecker/profitabilitychecker_test.go
  sequencer/sequencer_internal_test.go
  sequencer/sequencer_test.go
  state/globalexitroot.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  state/runtime/executor/errors.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/executor/pb/executor_grpc.pb.go
  state/runtime/runtime.go
  state/state.go
  synchronizer/synchronizer.go
  test/docker-compose.yml
  test/e2e/broadcast_test.go
  test/scripts/batchsender/main.go
  tools/rlp/main.go
Labels: cla-signed

#1460 Update uniswap v2 script
  test/scripts/uniswap/main.go
Labels: cla-signed

#1473 Fix/1472 verify batches timeout
  aggregator/aggregator.go
  test/config/test.prover.config.json
Labels: bug, Aggregator, cla-signed

#1483 Backport RC4 & RC5 to develop
  aggregator/aggregator.go
  aggregator/pb/aggregator.pb.go
  aggregator/pb/aggregator_grpc.pb.go
  config/environments/local/local.genesis.config.json
  config/network.go
  config/network_test.go
  db/migrations/state/0001.sql
  docker-compose.yml
  etherman/etherman.go
  etherman/etherman_test.go
  etherman/simulated.go
  etherman/smartcontracts/abi/bridge.abi
  etherman/smartcontracts/abi/proofofefficiency.abi
  etherman/smartcontracts/bin/bridge.bin
  etherman/smartcontracts/bin/proofofefficiency.bin
  etherman/smartcontracts/bridge/bridge.go
  etherman/smartcontracts/proofofefficiency/proofofefficiency.go
  etherman/types.go
  ethtxmanager/ethtxmanager.go
  ethtxmanager/interfaces.go
  merkletree/pb/statedb.pb.go
  merkletree/pb/statedb_grpc.pb.go
  proto/src/proto/broadcast/v1/broadcast.proto
  proto/src/proto/executor/v1/executor.proto
  sequencer/broadcast/pb/broadcast.pb.go
  sequencer/broadcast/pb/broadcast_grpc.pb.go
  sequencer/broadcast/server.go
  sequencer/interfaces.go
  sequencer/mocks/mock_etherman.go
  sequencer/profitabilitychecker/interfaces.go
  sequencer/profitabilitychecker/mocks/mock_etherman.go
  sequencer/profitabilitychecker/profitabilitychecker.go
  sequencer/profitabilitychecker/profitabilitychecker_test.go
  sequencer/sequencer_internal_test.go
  sequencer/sequencer_test.go
  state/globalexitroot.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  state/runtime/executor/errors.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/executor/pb/executor_grpc.pb.go
  state/runtime/runtime.go
  state/state.go
  synchronizer/synchronizer.go
  test/config/test.prover.config.json
  test/docker-compose.yml
  test/e2e/broadcast_test.go
  test/scripts/batchsender/main.go
  tools/rlp/main.go
Labels: cla-signed

#1475 fix unpack the revert reason
  docs/components/databases.md
  test/Makefile
  test/config/grafana/dashboard-dockers.json
  test/docker-compose.yml
  test/operations/wait.go
Labels: cla-signed

#1489 fix: update the genesis file
  config/environments/local/local.genesis.config.json
  test/config/test.genesis.config.json
Labels: cla-signed
