Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2023-10, with the labels that each got.

#2600 fix deadlock
  .github/workflows/jsonschema.yml
  cmd/run.go
  docs/config-file/node-config-doc.md
  synchronizer/ext_control.go
  synchronizer/l1_rollup_info_consumer.go
  synchronizer/l1_rollup_info_consumer_statistics.go
  synchronizer/l1_rollup_info_consumer_test.go
  synchronizer/l1_rollup_info_producer.go
  synchronizer/l1_sync_orchestration.go
  synchronizer/l1_sync_orchestration_test.go
  synchronizer/l1_worker_etherman.go
  synchronizer/l1_workers.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: synchronizer, cla-signed

#2605 fix error check returned by the executor when debug tracing a block
  jsonrpc/endpoints_debug.go
Labels: cla-signed

#2606 remove deprecated TraceBatchUseHTTPS config
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  jsonrpc/config.go
Labels: cla-signed

#2613 Populate stream file on sequencer startup
  .gitignore
  go.mod
  go.sum
  sequencer/datastream.go
  sequencer/datastream_test.go
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  state/datastream.go
  state/pgstatestorage.go
  state/test/datastream_test.go
  tools/datastreamer/Makefile
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/db/config.go
  tools/datastreamer/db/db.go
  tools/datastreamer/db/logger.go
  tools/datastreamer/main.go
Labels: cla-signed

#2614 Populate stream file on sequencer startup (#2613)
  .gitignore
  go.mod
  go.sum
  sequencer/datastream.go
  sequencer/datastream_test.go
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  state/datastream.go
  state/pgstatestorage.go
  state/test/datastream_test.go
  tools/datastreamer/Makefile
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/db/config.go
  tools/datastreamer/db/db.go
  tools/datastreamer/db/logger.go
  tools/datastreamer/main.go
Labels: cla-signed, cherry-pick

#2616 Feature/2595 l1 sync deadlock
  docs/design/synchronizer/l1_sync_channels_flow_v2.drawio.png
  docs/design/synchronizer/l1_synchronization.md
  synchronizer/l1_rollup_info_producer.go
  synchronizer/l1_rollup_info_producer_test.go
  synchronizer/l1_sync_orchestration.go
  synchronizer/l1_sync_orchestration_test.go
  synchronizer/l1_syncstatus.go
  synchronizer/l1_syncstatus_test.go
  synchronizer/l1_worker_etherman.go
  synchronizer/l1_workers.go
  synchronizer/l1_workers_decorator_limit_retries_by_time.go
  synchronizer/mock_l1_rollup_producer_interface.go
  synchronizer/synchronizer.go
Labels: cla-signed

#2575 add random ContextId when calling executor.ProcessBatch
  proto/src/proto/executor/v1/executor.proto
  state/batch.go
  state/runtime/executor/executor.pb.go
  state/state_test.go
  state/transaction.go
  tools/executor/main.go
Labels: cla-signed

#2593 add unit test to validate jRPC max request limit per ip and second
  jsonrpc/handler.go
  jsonrpc/server_test.go
Labels: cla-signed

#2609 renaming: renaming dbManager.checkIfReorg to checkStateInconsistency.
  sequencer/dbmanager.go
Labels: sequencer, improvement, cla-signed

#2572 Feature/jrpc log limit
  cmd/dumpstate.go
  cmd/run.go
  config/config_test.go
  config/default.go
  db/migrations/state/0011.sql
  db/migrations/state/0011_test.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  jsonrpc/config.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/server.go
  jsonrpc/server_test.go
  jsonrpc/storage.go
  pool/pool_test.go
  sequencer/closingsignalsmanager_test.go
  sequencer/dbmanager_test.go
  state/config.go
  state/errors.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  state/state_test.go
  test/operations/manager.go
  tools/state/reprocess_cmd.go
Labels: cla-signed, config

#2615 cherry-pick commit 310d4eb into release/v0.3.2
  jsonrpc/endpoints_debug.go
Labels: cla-signed

#2625 migration + tests and queries
  db/migrations/state/0010.sql
  db/migrations/state/0010_test.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
Labels: cla-signed

#2626 migration + tests and queries (#2625)
  db/migrations/state/0010.sql
  db/migrations/state/0010_test.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
Labels: cla-signed

#2629 Fix encodng tx in stream
  sequencer/dbmanager.go
  sequencer/sequencer.go
Labels: cla-signed

#2630 Update mock files using mockery v2.22.1 to v2.32.0
  aggregator/mocks/mock_dbtx.go
  aggregator/mocks/mock_etherman.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_profitabilitychecker.go
  aggregator/mocks/mock_prover.go
  aggregator/mocks/mock_state.go
  etherman/mock_etherscan.go
  etherman/mock_ethgasstation.go
  ethtxmanager/mock_etherman_test.go
  ethtxmanager/mock_state_test.go
  gasprice/mock_etherman.go
  gasprice/mock_pool.go
  jsonrpc/mock_storage.go
  jsonrpc/mocks/mock_dbtx.go
  jsonrpc/mocks/mock_etherman.go
  jsonrpc/mocks/mock_pool.go
  jsonrpc/mocks/mock_state.go
  sequencer/mock_db_manager.go
  sequencer/mock_dbtx.go
  sequencer/mock_etherman.go
  sequencer/mock_pool.go
  sequencer/mock_state.go
  sequencer/mock_worker.go
Labels: cla-signed

#2631 Fix encoding tx in stream
  sequencer/dbmanager.go
  sequencer/sequencer.go
Labels: cla-signed, cherry-pick

#2634 Fix encode into stream
  .gitignore
  sequencer/dbmanager.go
  tools/datastreamer/Makefile
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed

#2633 Delete duplicate values
  db/migrations/state/0010.sql
Labels: cla-signed

#2636 Fix encode into stream
  .gitignore
  sequencer/dbmanager.go
  tools/datastreamer/Makefile
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed, cherry-pick

#2638 Fix release docker-compose
  .github/workflows/release.yml
Labels: cla-signed

#2639 Cherrypick/#2632 #2637
  .github/workflows/release.yml
  db/migrations/state/0010.sql
Labels: cla-signed

#2642 Add bookmarks to streamer
  .gitignore
  go.mod
  go.sum
  sequencer/dbmanager.go
  sequencer/sequencer.go
  state/datastream.go
  tools/datastreamer/Makefile
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/db/db.go
  tools/datastreamer/main.go
Labels: cla-signed

#2647 fix tool
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/db/db.go
Labels: cla-signed

#2648 Cherrypick/2642 2647
  .gitignore
  go.mod
  go.sum
  sequencer/dbmanager.go
  sequencer/sequencer.go
  state/datastream.go
  tools/datastreamer/Makefile
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/db/db.go
  tools/datastreamer/main.go
Labels: cla-signed, cherry-pick

#2345 Fix debug tracer error message
  pool/pool.go
  state/transaction.go
  test/contracts/auto/ConstructorMap.sol
  test/contracts/auto/FFFFFFFF.sol
  test/contracts/bin/ConstructorMap/ConstructorMap.go
  test/contracts/bin/FFFFFFFF/FFFFFFFF.go
  test/e2e/debug_calltracer_test.go
  test/e2e/debug_shared.go
  test/e2e/debug_test.go
Labels: cla-signed

#2649 Fix debug tracer error message (#2345)
  pool/pool.go
  state/transaction.go
  test/contracts/auto/ConstructorMap.sol
  test/contracts/auto/FFFFFFFF.sol
  test/contracts/bin/ConstructorMap/ConstructorMap.go
  test/contracts/bin/FFFFFFFF/FFFFFFFF.go
  test/e2e/debug_calltracer_test.go
  test/e2e/debug_shared.go
  test/e2e/debug_test.go
Labels: cla-signed

#2653 Refactor data stream tool
  go.mod
  go.sum
  log/log.go
  state/pgstatestorage.go
  tools/datastreamer/Makefile
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/db/config.go
  tools/datastreamer/db/db.go
  tools/datastreamer/db/logger.go
  tools/datastreamer/main.go
Labels: cla-signed

#2670 check for bookmark entry in data stream file
  go.mod
  go.sum
  sequencer/sequencer.go
  tools/datastreamer/Makefile
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed

#2657 Refactor data stream tool (#2653)
  log/log.go
  state/pgstatestorage.go
  tools/datastreamer/Makefile
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/db/config.go
  tools/datastreamer/db/db.go
  tools/datastreamer/db/logger.go
  tools/datastreamer/main.go
Labels: cla-signed

#2672 L1 parallel sync: avoid get stuck when there are a lot of errors
  synchronizer/l1_rollup_info_consumer.go
  synchronizer/l1_rollup_info_consumer_test.go
  synchronizer/l1_rollup_info_producer.go
  synchronizer/l1_sync_orchestration.go
  synchronizer/l1_sync_orchestration_test.go
  synchronizer/l1_worker_etherman.go
  synchronizer/mock_l1_rollup_consumer_interface.go
  synchronizer/synchronizer.go
Labels: cla-signed

#2652 implementation EGP for RPC
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  pool/pool.go
  pool/pool_test.go
Labels: cla-signed

#2677 + add logs to batches
  synchronizer/l1_rollup_info_consumer.go
  synchronizer/l1_rollup_info_consumer_statistics.go
  synchronizer/l1_rollup_info_consumer_statistics_test.go
  synchronizer/l1_rollup_info_consumer_test.go
  synchronizer/l1_rollup_info_producer.go
  synchronizer/l1_sync_orchestration.go
  synchronizer/l1_sync_orchestration_test.go
  synchronizer/mock_l1_rollup_consumer_interface.go
  synchronizer/synchronizer.go
  test/Makefile
  test/config/test.node.config.toml
Labels: cla-signed

#2680 Update prover to v3.0.0
  ci/e2e-group10/forced_batches_test.go
  ci/e2e-group10/forced_batches_vector_group2_test.go
  ci/e2e-group10/shared.go
  ci/e2e-group11/forced_batches_vector_group3_test.go
  ci/e2e-group11/shared.go
  ci/e2e-group9/forced_batches_vector_group1_test.go
  ci/e2e-group9/shared.go
  config/environments/local/local.genesis.config.json
  config/network.go
  docker-compose.yml
  etherman/etherman_test.go
  go.mod
  go.sum
  jsonrpc/endpoints_zkevm_test.go
  pool/pool_test.go
  sequencer/sequencer.go
  state/transaction.go
  test/config/test.genesis.config.json
  test/docker-compose.yml
  test/e2e/forced_batches_test.go
  test/e2e/forced_batches_vector_group1_test.go
  test/e2e/forced_batches_vector_group2_test.go
  test/e2e/forced_batches_vector_group3_test.go
  test/e2e/shared.go
  test/e2e/state_test.go
  test/operations/manager.go
  tools/datastreamer/main.go
Labels: cla-signed

#2688 Cherrypick/2680
  ci/e2e-group10/forced_batches_test.go
  ci/e2e-group10/forced_batches_vector_group2_test.go
  ci/e2e-group10/shared.go
  ci/e2e-group11/forced_batches_vector_group3_test.go
  ci/e2e-group11/shared.go
  ci/e2e-group9/forced_batches_vector_group1_test.go
  ci/e2e-group9/shared.go
  config/environments/local/local.genesis.config.json
  config/network.go
  docker-compose.yml
  etherman/etherman_test.go
  go.mod
  go.sum
  jsonrpc/endpoints_zkevm_test.go
  pool/pool_test.go
  sequencer/sequencer.go
  test/config/test.genesis.config.json
  test/docker-compose.yml
  test/e2e/forced_batches_test.go
  test/e2e/forced_batches_vector_group1_test.go
  test/e2e/forced_batches_vector_group2_test.go
  test/e2e/forced_batches_vector_group3_test.go
  test/e2e/shared.go
  test/e2e/state_test.go
  test/operations/manager.go
  tools/datastreamer/main.go
Labels: cla-signed, cherry-pick

#2689 Update prover image to v3.0.0
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed

#2661 add new endpoint zkevm_getNativeBlockHashesInRange
  cmd/run.go
  config/config_test.go
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  docs/json-rpc-endpoints.md
  jsonrpc/config.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm.openrpc.json
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/mocks/mock_state.go
  jsonrpc/query.go
  jsonrpc/server_test.go
  jsonrpc/storage.go
  jsonrpc/types/interfaces.go
  state/config.go
  state/errors.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
Labels: cla-signed, config

#2695 Add UpdateGER entry to stream
  aggregator/mocks/mock_dbtx.go
  aggregator/mocks/mock_etherman.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_profitabilitychecker.go
  aggregator/mocks/mock_prover.go
  aggregator/mocks/mock_state.go
  etherman/mock_etherscan.go
  etherman/mock_ethgasstation.go
  ethtxmanager/mock_etherman_test.go
  ethtxmanager/mock_state_test.go
  gasprice/mock_etherman.go
  gasprice/mock_pool.go
  jsonrpc/mock_storage.go
  jsonrpc/mocks/mock_dbtx.go
  jsonrpc/mocks/mock_etherman.go
  jsonrpc/mocks/mock_pool.go
  jsonrpc/mocks/mock_state.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_dbtx.go
  sequencer/mock_etherman.go
  sequencer/mock_pool.go
  sequencer/mock_state.go
  sequencer/mock_worker.go
  sequencer/sequencer.go
  state/datastream.go
  state/helper.go
  state/pgstatestorage.go
  synchronizer/mock_dbtx.go
  synchronizer/mock_etherman.go
  synchronizer/mock_ethtxmanager.go
  synchronizer/mock_pool.go
  synchronizer/mock_state.go
  synchronizer/mock_zkevmclient.go
  tools/datastreamer/Makefile
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed

#2697 start metrics http server before node components
  cmd/run.go
Labels: cla-signed

#2698 Start streamserver before update the file
  sequencer/sequencer.go
Labels: cla-signed

#2699 add entries decode
  cmd/run.go
  go.mod
  go.sum
  sequencer/sequencer.go
  state/datastream.go
  tools/datastreamer/main.go
Labels: cla-signed

#2701 Fix/update ger open batch
  go.mod
  go.sum
  state/datastream.go
  state/pgstatestorage.go
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed

#2703 update code owners
  .github/CODEOWNERS
Labels: cla-signed

#2702 Cherrypick/v0.3.3-RC6
  go.mod
  go.sum
  sequencer/interfaces.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  state/datastream.go
  state/helper.go
  state/pgstatestorage.go
  tools/datastreamer/Makefile
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed, cherry-pick

#2704 Add pool.whitelisted table
  db/migrations/pool/0011.sql
Labels: cla-signed

#2685 + rollupinfo request for lastest block, add previous block to check L…
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  sonar-project.properties
  synchronizer/block_range.go
  synchronizer/config.go
  synchronizer/ext_control.go
  synchronizer/generic_cache.go
  synchronizer/generic_cache_test.go
  synchronizer/l1_filter_send_orderer_results_to_synchronizer.go
  synchronizer/l1_filter_send_orderer_results_to_synchronizer_test.go
  synchronizer/l1_live_block_ranges.go
  synchronizer/l1_live_block_ranges_test.go
  synchronizer/l1_rollup_info_consumer.go
  synchronizer/l1_rollup_info_producer.go
  synchronizer/l1_rollup_info_producer_statistics.go
  synchronizer/l1_rollup_info_producer_test.go
  synchronizer/l1_sync_orchestration.go
  synchronizer/l1_syncstatus.go
  synchronizer/l1_syncstatus_test.go
  synchronizer/l1_worker_etherman.go
  synchronizer/l1_worker_etherman_test.go
  synchronizer/l1_workers.go
  synchronizer/l1_workers_decorator_limit_retries_by_time.go
  synchronizer/l1_workers_decorator_limit_retries_by_time_test.go
  synchronizer/mock_l1_rollup_producer_interface.go
  synchronizer/mock_l1_worker.go
  synchronizer/mock_workers.go
  synchronizer/synchronizer.go
  synchronizer/time_provider.go
Labels: cla-signed

#2706 + add coverage report to sonarcloud
  .github/workflows/sonarqube.yml
  sonar-project.properties
  test/Makefile
Labels: cla-signed

#2712 Add online tooling for data stream
  .github/workflows/jsonschema.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test-from-prover.yml
  .github/workflows/test-full-non-e2e.yml
  .github/workflows/updatedeps.yml
  Dockerfile
  Makefile
  README.md
  docs/ci/groups.md
  etherman/etherman_test.go
  go.mod
  go.sum
  sequencer/finalizer_test.go
  tools/datastreamer/Makefile
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
  tools/zkevmprovermock/Dockerfile
Labels: cla-signed

#2715 Add online tooling for data stream (#2712) (Cherry-Pick v0.3.3-RC7)
  go.mod
  go.sum
  tools/datastreamer/Makefile
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed, cherry-pick

#2717 fix streamer tool logs
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed

#2713 add LDFLAGS to goreleaser to include in the binary the right, version
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: cla-signed

#2725 revert changes on config file
  test/config/test.node.config.toml
Labels: cla-signed

#2729 support genesis config with pointer to BatchData
  config/gen_json_schema.go
  config/gen_json_schema_test.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
Labels: cla-signed

#2723 Update zkevm-data-streamer to v0.1.8
  go.mod
  go.sum
Labels: cla-signed

#2673 review l2 block and batch tags: earliest, latest, pending, safe and finalized
  jsonrpc/endpoints_debug.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/mocks/mock_state.go
  jsonrpc/types/codec.go
  jsonrpc/types/codec_test.go
  jsonrpc/types/interfaces.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
Labels: cla-signed

#2730 fix nil pointer when fails etherman call
  synchronizer/l1_rollup_info_producer.go
  synchronizer/l1_rollup_info_producer_statistics.go
  synchronizer/l1_rollup_info_producer_statistics_test.go
  synchronizer/l1_rollup_info_producer_test.go
  synchronizer/l1_worker_etherman.go
  synchronizer/l1_worker_etherman_test.go
  synchronizer/synchronizer.go
Labels: cla-signed

#2731 add pool indexes
  db/migrations/pool/0011.sql
  db/migrations/pool/0011_test.go
  db/migrations/pool/utils_test.go
Labels: cla-signed, zkevm-seq-agg

#2718 GHA docker update
  .github/workflows/push-docker-develop.yml
  .github/workflows/push-docker-tagged.yml
  .github/workflows/test-from-prover.yml
Labels: cla-signed

#2737 fix new error handling
  state/runtime/executor/errors.go
Labels: cla-signed

#2733 delete failed txs during pool cleanup
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  sequencer/interfaces.go
  sequencer/mock_pool.go
  sequencer/sequencer.go
Labels: bug, cla-signed, pool, zkevm-seq-agg

#2690 Improve effective gas price implementation (RPC filter, gasprice/balance opcodes flags, new formula)
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  db/migrations/state/0011.sql
  db/migrations/state/0011_test.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  pool/config.go
  pool/effectivegasprice.go
  pool/effectivegasprice_test.go
  pool/errors.go
  pool/pool.go
  pool/pool_test.go
  proto/src/proto/executor/v1/executor.proto
  sequencer/config.go
  sequencer/dbmanager.go
  sequencer/effective_gas_price.go
  sequencer/effective_gas_price_test.go
  sequencer/errors.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_pool.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  sequencer/txtracker.go
  sequencer/worker.go
  sequencesender/sequencesender.go
  state/batch.go
  state/converters.go
  state/genesis.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  state/runtime/executor/errors.go
  state/runtime/executor/executor.pb.go
  state/runtime/executor/executor_grpc.pb.go
  state/runtime/runtime.go
  state/state_test.go
  state/transaction.go
  state/types.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/contracts/auto/HasOpCode.sol
  test/contracts/bin/HasOpCode/HasOpCode.go
  test/docker-compose.yml
  test/e2e/effectivegasprice_test.go
  test/e2e/pool_test.go
Labels: cla-signed, config, zkevm-bridge-sync-rpc, zkevm-seq-agg

#2738 Fix GlobalQueue/AccountQueue pool config
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/node.config.toml
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed, zkevm-seq-agg
