Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2023-06, with the labels that each got.

#2152 Hotfix/v0.1.1
  docker-compose.yml
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/txtracker_test.go
  state/batch.go
  state/helper.go
  state/helper_test.go
  state/transaction.go
  test/contracts/auto/ChainCallLevel1.sol
  test/contracts/auto/ChainCallLevel2.sol
  test/contracts/auto/ChainCallLevel3.sol
  test/contracts/auto/ChainCallLevel4.sol
  test/contracts/auto/Memory.sol
  test/contracts/bin/ChainCallLevel1/ChainCallLevel1.go
  test/contracts/bin/ChainCallLevel2/ChainCallLevel2.go
  test/contracts/bin/ChainCallLevel3/ChainCallLevel3.go
  test/contracts/bin/ChainCallLevel4/ChainCallLevel4.go
  test/contracts/bin/Memory/Memory.go
  test/docker-compose.yml
  test/e2e/debug_calltracer_test.go
  test/e2e/debug_shared.go
  test/e2e/debug_test.go
  test/scripts/check_trace/main.go
Labels: cla-signed

#2155 improve: adding missing counting of metric for expired transactions in the sequencer.
  sequencer/metrics/metrics.go
  sequencer/sequencer.go
Labels: sequencer, cla-signed, metrics

#2153 Hotfix/v0.1.1 (#2152)
  docker-compose.yml
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/txtracker_test.go
  state/batch.go
  state/helper.go
  state/helper_test.go
  state/transaction.go
  test/contracts/auto/ChainCallLevel1.sol
  test/contracts/auto/ChainCallLevel2.sol
  test/contracts/auto/ChainCallLevel3.sol
  test/contracts/auto/ChainCallLevel4.sol
  test/contracts/auto/Memory.sol
  test/contracts/bin/ChainCallLevel1/ChainCallLevel1.go
  test/contracts/bin/ChainCallLevel2/ChainCallLevel2.go
  test/contracts/bin/ChainCallLevel3/ChainCallLevel3.go
  test/contracts/bin/ChainCallLevel4/ChainCallLevel4.go
  test/contracts/bin/Memory/Memory.go
  test/docker-compose.yml
  test/e2e/debug_calltracer_test.go
  test/e2e/debug_shared.go
  test/e2e/debug_test.go
  test/scripts/check_trace/main.go
Labels: cla-signed

#2159 Fix gRPC message size
  state/runtime/executor/client.go
Labels: cla-signed

#2179 Make max grpc message size configurable
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/public.node.config.toml
  config/environments/public/public.node.config.toml
  pool/pool_test.go
  sequencer/closingsignalsmanager_test.go
  state/runtime/executor/client.go
  state/runtime/executor/config.go
  state/state_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/operations/manager.go
  tools/executor/main.go
Labels: cla-signed

#2177 Add block reason
  db/migrations/pool/0009.sql
Labels: cla-signed

#2182 Get SequencerNodeURI from SC
  cmd/run.go
Labels: cla-signed

#2192 Change position of the log.Info for the best fitting tx
  sequencer/worker.go
Labels: cla-signed

#2176 Retry on resource exhausted
  cmd/run.go
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/public.node.config.toml
  config/environments/public/public.node.config.toml
  state/config.go
  state/runtime/executor/config.go
  state/runtime/runtime.go
  state/transaction.go
Labels: cla-signed, config

#2120 Remove pricegetter
  config/config.go
  config/config_test.go
  config/default.go
  pricegetter/config.go
  pricegetter/pricegetter.go
  pricegetter/priceprovider/abi/uniswap.abi
  pricegetter/priceprovider/config.go
  pricegetter/priceprovider/priceprovider.go
  pricegetter/priceprovider/script.sh
  pricegetter/priceprovider/uniswap/client.go
  pricegetter/priceprovider/uniswap/uniswap.go
Labels: cla-signed, config

#1973 Fix BlockExplorer L2 Port in Local documentation
  docs/running_local.md
Labels: cla-signed

#2104 create index on pool.gas_price timestamp
  db/migrations/pool/0009.sql
Labels: cla-signed

#2193 Rename Public to Testnet
  .github/workflows/release.yml
  Dockerfile
  config/environments/testnet/example.env
  config/environments/testnet/postgresql.conf
  config/environments/testnet/testnet.node.config.toml
  config/environments/testnet/testnet.prover.config.json
  docker-compose.yml
  docs/modes.md
  docs/production-setup.md
Labels: cla-signed, config

#2206 Optimize trace (#2183)
  docker-compose.yml
  jsonrpc/endpoints_debug.go
  proto/src/proto/executor/v1/executor.proto
  state/converters.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/executor/pb/executor_grpc.pb.go
  state/runtime/fakevm/memory.go
  state/runtime/instrumentation/executortrace.go
  state/runtime/instrumentation/structlog.go
  state/transaction.go
  test/docker-compose.yml
  test/e2e/sc_test.go
Labels: cla-signed

#2199 Fix default zk counters limits
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  sequencer/closingsignalsmanager_test.go
  sequencer/dbmanager_test.go
  sequencer/finalizer_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed, config

#2211 Fix/group8
  state/runtime/instrumentation/js/goja.go
  state/runtime/instrumentation/tracers/native/call.go
  state/runtime/instrumentation/tracers/tracers.go
Labels: cla-signed

#2210 Fix load zkCounters from pool
  pool/pgpoolstorage/pgpoolstorage.go
Labels: cla-signed

#2209 change ports for explorer db to remove conflict
  test/docker-compose.yml
Labels: cla-signed

#2214 Fix GetWIPBatch when previous last batch is a forced batch
  sequencer/dbmanager.go
  sequencer/worker.go
Labels: cla-signed

#2216 Hotfix/forced batch
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/types/types.go
  jsonrpc/types/types_test.go
  synchronizer/synchronizer.go
Labels: cla-signed

#2189 add pool limits
  config/config_test.go
  config/default.go
  pool/config.go
  pool/errors.go
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/pool_test.go
  test/benchmarks/sequencer/common/transactions/transactions.go
Labels: cla-signed, config

#2219 Use forkID while encoding/decoding txs
  ci/e2e-group10/forced_batches_test.go
  ci/e2e-group10/forced_batches_vector_group2_test.go
  ci/e2e-group11/forced_batches_vector_group3_test.go
  ci/e2e-group9/forced_batches_vector_group1_test.go
  cmd/run.go
  etherman/etherman_test.go
  jsonrpc/endpoints_zkevm_test.go
  pool/pool_test.go
  sequencer/config.go
  sequencer/dbmanager.go
  sequencer/finalizer.go
  state/batch.go
  state/helper.go
  state/helper_test.go
  state/state_test.go
  state/transaction.go
  test/e2e/forced_batches_test.go
  test/e2e/forced_batches_vector_test.go
  tools/executor/main.go
  tools/rlp/README.md
  tools/rlp/main.go
Labels: cla-signed

#2223 Hotfix/batch l2 data
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/types/types.go
  jsonrpc/types/types_test.go
  synchronizer/synchronizer.go
Labels: cla-signed

#2222 Add effective_gas_price to receipt
  db/migrations/state/0007.sql
  state/helper.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
Labels: cla-signed

#2207 Feature/#2201 sync metrics
  docker-compose.yml
  etherman/etherman.go
  etherman/metrics/metrics.go
  synchronizer/metrics/metrics.go
  synchronizer/synchronizer.go
  test/docker-compose.yml
Labels: cla-signed

#2173 Hotfix/v0.1.3
  cmd/run.go
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/public.node.config.toml
  config/environments/public/public.node.config.toml
  docker-compose.yml
  jsonrpc/endpoints_debug.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/server.go
  jsonrpc/types/types.go
  jsonrpc/types/types_test.go
  pool/config.go
  pool/errors.go
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/pool_test.go
  proto/src/proto/executor/v1/executor.proto
  sequencer/closingsignalsmanager_test.go
  sequencer/dbmanager.go
  sequencer/worker.go
  state/converters.go
  state/runtime/executor/client.go
  state/runtime/executor/config.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/fakevm/memory.go
  state/runtime/instrumentation/executortrace.go
  state/runtime/instrumentation/structlog.go
  state/state_test.go
  state/transaction.go
  synchronizer/synchronizer.go
  test/benchmarks/sequencer/common/transactions/transactions.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/contracts/auto/DeployCreate0.sol
  test/contracts/auto/Depth.sol
  test/contracts/auto/OpCallAux.sol
  test/contracts/bin/DeployCreate0/DeployCreate0.go
  test/contracts/bin/Depth/Depth.go
  test/contracts/bin/OpCallAux/OpCallAux.go
  test/docker-compose.yml
  test/e2e/debug_calltracer_test.go
  test/e2e/debug_shared.go
  test/e2e/debug_test.go
  test/e2e/jsonrpc2_test.go
  test/operations/manager.go
  tools/executor/main.go
Labels: cla-signed, config

#2228 Hotfix/v0.1.3 (#2173)
  cmd/run.go
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/public.node.config.toml
  config/environments/testnet/testnet.node.config.toml
  docker-compose.yml
  jsonrpc/endpoints_debug.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/server.go
  jsonrpc/types/types.go
  jsonrpc/types/types_test.go
  pool/config.go
  pool/errors.go
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/pool_test.go
  proto/src/proto/executor/v1/executor.proto
  sequencer/closingsignalsmanager_test.go
  sequencer/dbmanager.go
  sequencer/worker.go
  state/converters.go
  state/runtime/executor/client.go
  state/runtime/executor/config.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/fakevm/memory.go
  state/runtime/instrumentation/executortrace.go
  state/runtime/instrumentation/structlog.go
  state/state_test.go
  state/transaction.go
  synchronizer/synchronizer.go
  test/benchmarks/sequencer/common/transactions/transactions.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/contracts/auto/DeployCreate0.sol
  test/contracts/auto/Depth.sol
  test/contracts/auto/OpCallAux.sol
  test/contracts/bin/DeployCreate0/DeployCreate0.go
  test/contracts/bin/Depth/Depth.go
  test/contracts/bin/OpCallAux/OpCallAux.go
  test/docker-compose.yml
  test/e2e/debug_calltracer_test.go
  test/e2e/debug_shared.go
  test/e2e/debug_test.go
  test/e2e/jsonrpc2_test.go
  test/operations/manager.go
  tools/executor/main.go
Labels: cla-signed

#2233 remove failed txs from the pool limit check
  pool/pool.go
Labels: cla-signed

#2235 Feature/hotfix/v0.1.x/debug trace by batch number rpc
  docker-compose.yml
  jsonrpc/endpoints_debug.go
  jsonrpc/endpoints_eth.go
  jsonrpc/server.go
  test/docker-compose.yml
Labels: cla-signed

#2232 add validateTx logs
  pool/pool.go
Labels: cla-signed

#2171 Feature/#2102 snap restore
  cmd/approve.go
  cmd/dumpstate.go
  cmd/main.go
  cmd/readme.md
  cmd/restore.go
  cmd/run.go
  cmd/snapshot.go
  config/config.go
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/public.node.config.toml
  config/environments/testnet/testnet.node.config.toml
  config/network.go
  db/scripts/init_prover_db.sql
  go.mod
  go.sum
  synchronizer/synchronizer.go
  test/config/test.node.config.toml
  test/config/test.prover.config.json
  test/e2e/uniswap_test.go
Labels: cla-signed, config

#2237 Support fork id upgrades without down time for the trusted state
  aggregator/config.go
  cmd/run.go
  config/config.go
  config/default.go
  config/environments/local/local.node.config.toml
  sequencesender/config.go
  sequencesender/sequencesender.go
  state/batch.go
  state/config.go
  state/forkid.go
  state/transaction.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed, config

#2226 Feature/#2220 sync optimizations
  state/pgstatestorage.go
  synchronizer/interfaces.go
  synchronizer/metrics/metrics.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#2234 effective gas price comparation
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/testnet/testnet.node.config.toml
  pool/config.go
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/pool_test.go
  pool/transaction.go
  sequencer/config.go
  sequencer/dbmanager.go
  sequencer/effective_gas_price.go
  sequencer/effective_gas_price_test.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_pool.go
  sequencer/txtracker.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#2240 Avoid Reprocess the full batch
  etherman/etherman.go
  state/transaction.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#2244 fix trace batch remote requests in parallel limitation
  jsonrpc/endpoints_debug.go
Labels: cla-signed
