Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2023-01, with the labels that each got.

#1471 upgrade git hub actions to the latest versions
  .github/workflows/lint.yml
  .github/workflows/push-docker-develop.yml
  .github/workflows/push-docker.yml
  .github/workflows/release.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test-from-prover.yml
  .github/workflows/test-full-non-e2e.yml
  .github/workflows/updatedeps.yml
  docs/ci/ok-to-test.md
Labels: cla-signed

#1494 fatals changed to return error
  synchronizer/synchronizer.go
Labels: cla-signed

#1502 [Aggregator] Add metrics package and ConnectedProvers metric
  aggregator/aggregator.go
  aggregator/metrics/metrics.go
  metrics/prometheus.go
  metrics/prometheus_test.go
  test/docker-compose.yml
Labels: Aggregator, cla-signed, Metrics

#1504 feat: add WorkingProvers gauge metric
  aggregator/aggregator.go
  aggregator/metrics/metrics.go
  aggregator/prover/prover.go
Labels: Aggregator, cla-signed, Metrics

#1512 DBManager WIP
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/transaction.go
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/sequencer.go
  sequencer/worker.go
  state/batch.go
  state/pgstatestorage.go
  state/state.go
Labels: cla-signed

#1520 Fix/rc4
  ethtxmanager/ethtxmanager.go
  sequencer/batchbuilder.go
  sequencer/sequencesender.go
  state/state.go
Labels: cla-signed

#1523 Feature/#1506 forced batch
  db/migrations/state/0003.sql
  sequencer/broadcast/interfaces.go
  sequencer/broadcast/mocks/mock_state.go
  sequencer/broadcast/server.go
  sequencer/broadcast/server_test.go
  state/batch.go
  state/forcedbatch.go
  state/pgstatestorage.go
  state/state.go
  state/state_test.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/e2e/broadcast_test.go
Labels: cla-signed

#1528 Handle and log ROM OOC errors in executor
  db/migrations/state/0003.sql
  db/migrations/state/0004.sql
  state/converters.go
  state/pgstatestorage.go
  state/state.go
  state/state_test.go
  state/types.go
Labels: cla-signed

#1509 [Sequencer] Check if enough time passed to close a sequence
  config/default.go
  config/environments/local/local.node.config.toml
  sequencer/closingchecker.go
  sequencer/config.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: Sequencer, cla-signed

#1537 Update prover
  config/environments/public/public.prover.config.json
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed

#1533 Fix consecutive proofs verifications. Verify proof including batches lower than last verified batch
  aggregator/aggregator.go
Labels: bug, Aggregator, cla-signed

#1540 Initial sequencer.worker implementation (WIP)
  config/default.go
  config/environments/local/local.node.config.toml
  sequencer/addrqueue.go
  sequencer/addrqueue_test.go
  sequencer/batchresources.go
  sequencer/config.go
  sequencer/dbmanager.go
  sequencer/efficiencylist.go
  sequencer/efficiencylist_test.go
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/sequencer.go
  sequencer/txtracker.go
  sequencer/txtracker_test.go
  sequencer/worker.go
  sequencer/worker_test.go
  state/state.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#1524 Feature/dbmanager
  aggregator/mocks/mock_etherman.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_profitabilitychecker.go
  aggregator/mocks/mock_prover.go
  aggregator/mocks/mock_state.go
  cmd/run.go
  db/migrations/state/0003.sql
  etherman/mock_etherscan.go
  etherman/mock_ethgasstation.go
  jsonrpc/mock_dbtx_test.go
  jsonrpc/mock_gasPriceEstimator_test.go
  jsonrpc/mock_pool_test.go
  jsonrpc/mock_state_test.go
  jsonrpc/mock_storage_test.go
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  sequencer/broadcast/interfaces.go
  sequencer/broadcast/mocks/mock_state.go
  sequencer/broadcast/server.go
  sequencer/broadcast/server_test.go
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_dbtx.go
  sequencer/mock_etherman.go
  sequencer/mock_pool.go
  sequencer/mock_state.go
  sequencer/mock_tx_manager.go
  sequencer/mock_worker.go
  sequencer/sequencer.go
  sequencer/txtracker.go
  sequencer/worker.go
  state/batch.go
  state/converters.go
  state/forcedbatch.go
  state/helper.go
  state/pgstatestorage.go
  state/state.go
  state/state_test.go
  state/types.go
  synchronizer/interfaces.go
  synchronizer/mock_dbtx.go
  synchronizer/mock_etherman.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/e2e/broadcast_test.go
Labels: cla-signed

#1542 implement last methods
  sequencer/dbmanager.go
  sequencer/sequencer.go
  state/state.go
Labels: cla-signed

#1531 Feature/#1515 migration
  cmd/main.go
  cmd/run.go
  config/config.go
  db/db.go
  jsonrpc/interfaces.go
  jsonrpc/mock_state_test.go
  jsonrpc/server.go
  jsonrpc/server_test.go
  state/state.go
  test/Makefile
Labels: cla-signed

#1543 added getLastStateRoot
  sequencer/closingsignalsmanager.go
  sequencer/dbmanager.go
  sequencer/dbmanager_test.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_state.go
  sequencer/worker.go
  state/pgstatestorage.go
  state/state.go
Labels: cla-signed

#1546 genesis + smc addresses
  config/environments/public/public.genesis.config.json
  config/environments/public/public.node.config.toml
Labels: cla-signed

#1550 Closing Signals Manager first implementation
  db/migrations/state/0003.sql
  sequencer/closingsignalsmanager.go
  sequencer/config.go
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_state.go
  state/pgstatestorage.go
Labels: cla-signed

#1556 Change getLastGer implementation
  sequencer/closingsignalsmanager.go
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
Labels: cla-signed

#1555 Added worker unit testing. Missing TODOs implementation done
  sequencer/addrqueue.go
  sequencer/addrqueue_test.go
  sequencer/batchresources.go
  sequencer/sequencer.go
  sequencer/txtracker.go
  sequencer/txtracker_test.go
  sequencer/worker.go
  sequencer/worker_test.go
Labels: cla-signed

#1560 Handle new executor rom errors
  db/migrations/state/0003.sql
  docker-compose.yml
  proto/src/proto/executor/v1/executor.proto
  sequencer/sequencer_internal_test.go
  state/converters.go
  state/helper.go
  state/pgstatestorage.go
  state/runtime/executor/errors.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/executor/pb/executor_grpc.pb.go
  state/state.go
  state/state_test.go
  state/types.go
  test/docker-compose.yml
  tools/zkevmprovermock/server/executor.go
Labels: cla-signed

#1553 allow array config params to be set via env vars
  config/config.go
  config/config_test.go
Labels: cla-signed

#1567 Fix: typos
  README.md
  docs/components/aggregator.md
  docs/components/databases.md
  docs/components/rpc.md
  docs/components/sequencer.md
  docs/components/synchronizer.md
  docs/running_local.md
Labels: cla-signed

#1544 Fix encoding bug in AddForcedBatch
  state/pgstatestorage.go
Labels: cla-signed

#1566 Feature/executor error
  aggregator/mocks/mock_etherman.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_profitabilitychecker.go
  aggregator/mocks/mock_prover.go
  aggregator/mocks/mock_state.go
  db/migrations/state/0003.sql
  docker-compose.yml
  etherman/mock_etherscan.go
  etherman/mock_ethgasstation.go
  jsonrpc/mock_dbtx_test.go
  jsonrpc/mock_gasPriceEstimator_test.go
  jsonrpc/mock_pool_test.go
  jsonrpc/mock_state_test.go
  jsonrpc/mock_storage_test.go
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  proto/src/proto/executor/v1/executor.proto
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_dbtx.go
  sequencer/mock_etherman.go
  sequencer/mock_pool.go
  sequencer/mock_state.go
  sequencer/mock_tx_manager.go
  sequencer/mock_worker.go
  sequencer/sequencer.go
  sequencer/worker.go
  sequencer/worker_test.go
  state/converters.go
  state/helper.go
  state/pgstatestorage.go
  state/runtime/executor/errors.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/executor/pb/executor_grpc.pb.go
  state/runtime/runtime.go
  state/state.go
  state/state_test.go
  state/types.go
  synchronizer/mock_dbtx.go
  synchronizer/mock_etherman.go
  synchronizer/mock_state.go
  tools/zkevmprovermock/server/executor.go
Labels: cla-signed

#1570 fix: wip fix of prepareProcessRequestFromState to fetch txs when repr…
  sequencer/finalizer.go
  sequencer/finalizer_test.go
Labels: cla-signed

#1572 fix: fixing benchmark test and several bugs.
  aggregator/mocks/mock_etherman.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_profitabilitychecker.go
  aggregator/mocks/mock_prover.go
  aggregator/mocks/mock_state.go
  etherman/mock_etherscan.go
  etherman/mock_ethgasstation.go
  jsonrpc/mock_dbtx_test.go
  jsonrpc/mock_gasPriceEstimator_test.go
  jsonrpc/mock_pool_test.go
  jsonrpc/mock_state_test.go
  jsonrpc/mock_storage_test.go
  sequencer/addrqueue.go
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_dbtx.go
  sequencer/mock_etherman.go
  sequencer/mock_pool.go
  sequencer/mock_state.go
  sequencer/mock_tx_manager.go
  sequencer/mock_worker.go
  sequencer/sequencer.go
  sequencer/worker.go
  state/state.go
  synchronizer/mock_dbtx.go
  synchronizer/mock_etherman.go
  synchronizer/mock_state.go
  test/Makefile
  test/benchmarks/sequencer/pool_processing_test.go
Labels: cla-signed

#1575 Db flag to identify trusted verified batches
  db/migrations/state/0005.sql
  state/batch.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  state/state.go
  synchronizer/synchronizer.go
Labels: cla-signed

#1574 Feature/#1549 genesis txs
  config/environments/public/public.genesis.config.json
  config/network.go
  state/genesis.go
  state/pgstatestorage.go
  state/state.go
  test/Makefile
Labels: cla-signed

#1548 Feature/#1486 l2gasprice
  cmd/main.go
  cmd/run.go
  config/config.go
  config/config_test.go
  config/default.go
  config/environments/public/public.node.config.toml
  etherman/etherman.go
  etherman/etherman_test.go
  gasprice/allbatches.go
  gasprice/config.go
  gasprice/default.go
  gasprice/default_test.go
  gasprice/follower.go
  gasprice/follower_test.go
  gasprice/gaspricesuggester.go
  gasprice/interfaces.go
  gasprice/lastnbatches.go
  gasprice/mock_etherman.go
  gasprice/mock_pool.go
  jsonrpc/eth.go
  jsonrpc/eth_test.go
  jsonrpc/interfaces.go
  jsonrpc/mock_gasPriceEstimator_test.go
  jsonrpc/server.go
  jsonrpc/server_test.go
  sequencer/batchbuilder.go
  sequencer/interfaces.go
  sequencer/mocks/mock_gaspriceestimator.go
  sequencer/mocks/mock_pool.go
  sequencer/sequencer.go
  sequencer/sequencer_internal_test.go
  test/Makefile
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/docker-compose.yml
Labels: cla-signed

#1554 jRPC - Batch methods
  README.md
  docs/zkEVM-custom-endpoints.md
  hex/hex.go
  hex/hex_test.go
  jsonrpc/codec.go
  jsonrpc/endpoints_debug.go
  jsonrpc/endpoints_debug_test.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_net.go
  jsonrpc/endpoints_txpool.go
  jsonrpc/endpoints_web3.go
  jsonrpc/endpoints_web3_test.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm.openrpc.json
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/handler.go
  jsonrpc/interfaces.go
  jsonrpc/mock_state_test.go
  jsonrpc/server.go
  jsonrpc/server_test.go
  jsonrpc/types.go
  jsonrpc/zkevm.go
  jsonrpc/zkevm_test.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  test/e2e/jsonrpc_test.go
  test/operations/wait.go
Labels: cla-signed

#1576 Fix linter and tests
  aggregator/mocks/mock_etherman.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_profitabilitychecker.go
  aggregator/mocks/mock_prover.go
  aggregator/mocks/mock_state.go
  etherman/mock_etherscan.go
  etherman/mock_ethgasstation.go
  jsonrpc/mock_dbtx_test.go
  jsonrpc/mock_gasPriceEstimator_test.go
  jsonrpc/mock_pool_test.go
  jsonrpc/mock_state_test.go
  jsonrpc/mock_storage_test.go
  pool/transaction.go
  sequencer/closingsignalsmanager.go
  sequencer/dbmanager.go
  sequencer/dbmanager_test.go
  sequencer/efficiencylist.go
  sequencer/errors.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/mock_db_manager.go
  sequencer/mock_dbtx.go
  sequencer/mock_etherman.go
  sequencer/mock_pool.go
  sequencer/mock_state.go
  sequencer/mock_tx_manager.go
  sequencer/mock_worker.go
  sequencer/sequencer.go
  sequencer/worker.go
  sequencer/worker_test.go
  state/converters.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  state/state.go
  state/state_test.go
  synchronizer/mock_dbtx.go
  synchronizer/mock_etherman.go
  synchronizer/mock_state.go
  synchronizer/synchronizer_test.go
  test/e2e/broadcast_test.go
  test/e2e/ethtransfer_test.go
Labels: cla-signed

#1585 Remove testMain in dbmanager tests
  sequencer/dbmanager_test.go
Labels: cla-signed

#1586 Fix errors found while running bridge/GER tests
  sequencer/closingsignalsmanager.go
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_state.go
  state/pgstatestorage.go
Labels: cla-signed

#1581 New smc version
  config/environments/local/local.genesis.config.json
  config/environments/local/local.node.config.toml
  config/environments/public/public.node.config.toml
  etherman/etherman.go
  etherman/etherman_test.go
  etherman/simulated.go
  etherman/smartcontracts/abi/polygonzkevm.abi
  etherman/smartcontracts/abi/polygonzkevmbridge.abi
  etherman/smartcontracts/abi/polygonzkevmglobalexitroot.abi
  etherman/smartcontracts/bin/bridge.bin
  etherman/smartcontracts/bin/globalexitrootmanager.bin
  etherman/smartcontracts/bin/polygonzkevm.bin
  etherman/smartcontracts/bin/polygonzkevmbridge.bin
  etherman/smartcontracts/bin/polygonzkevmglobalexitroot.bin
  etherman/smartcontracts/bin/proofofefficiency.bin
  etherman/smartcontracts/bridge/bridge.go
  etherman/smartcontracts/globalexitrootmanager/globalexitrootmanager.go
  etherman/smartcontracts/polygonzkevm/polygonzkevm.go
  etherman/smartcontracts/polygonzkevmbridge/polygonzkevmbridge.go
  etherman/smartcontracts/polygonzkevmglobalexitroot/polygonzkevmglobalexitroot.go
  etherman/smartcontracts/proofofefficiency/proofofefficiency.go
  etherman/smartcontracts/script.sh
  etherman/types.go
  synchronizer/synchronizer_test.go
  test/aggregator.keystore
  test/config/debug.node.config.toml
  test/config/test.genesis.config.json
  test/config/test.node.config.toml
  test/docker-compose.yml
  tools/rlp/main.go
Labels: cla-signed

#1593 Add forced batch closing signal unit test
  sequencer/closingsignalsmanager_test.go
  sequencer/finalizer_test.go
  state/pgstatestorage.go
Labels: cla-signed

#1582 add support to pre-EIP155 txs
  ci/e2e-group1/preEIP155_test.go
  pool/pool.go
  pool/pool_test.go
  state/crypto.go
  state/helper.go
  state/transaction.go
  test/docker-compose.yml
  test/e2e/debug_test.go
  test/e2e/preEIP155_test.go
Labels: cla-signed

#1596 remove dependency of iden3 package from jrpc
  jsonrpc/endpoints_web3.go
Labels: cla-signed

#1599 Feature/#1577 force
  test/scripts/sendForcedBatch/README.md
  test/scripts/sendForcedBatch/main.go
  test/scripts/sequenceForcedBatch/README.md
  test/scripts/sequenceForcedBatch/main.go
Labels: cla-signed

#1600 adding missing mutex lock in woker.MoveTxToNotReady
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/worker.go
  test/benchmarks/sequencer/common/metrics/metrics.go
Labels: cla-signed

#1591 Improve container startup order in docker-compose
  docker-compose.yml
Labels: cla-signed
