Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2023-03, with the labels that each got.

#1719 new public data
  config/environments/public/public.genesis.config.json
  config/environments/public/public.node.config.toml
  docker-compose.yml
Labels: cla-signed

#1712 fix mining reverted txs
  jsonrpc/codec.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/errors.go
  jsonrpc/server.go
  sequencer/finalizer.go
  state/state.go
  state/state_test.go
  test/e2e/jsonrpc_test.go
Labels: cla-signed

#1724 sequencer fixes
  sequencer/efficiencylist.go
  sequencer/finalizer.go
  test/e2e/jsonrpc_test.go
Labels: cla-signed

#1728 Remove default fork id from config files
  config/config.go
  config/default.go
  config/environments/local/local.node.config.toml
  state/forkid.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#1727 fix
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  sequencer/config.go
  sequencer/sequencesender.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#1729 fix forkID
  cmd/run.go
  docker-compose.yml
  pool/pool_test.go
  state/config.go
  state/state.go
  state/state_test.go
  test/config/test.prover.config.json
  test/docker-compose.yml
Labels: cla-signed

#1730 fix error handling in sequencer
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  state/runtime/executor/errors.go
Labels: cla-signed

#1735 fix log reorg
  synchronizer/synchronizer.go
Labels: cla-signed

#1739 add check stateroot in reprocessfull
  sequencer/finalizer.go
Labels: cla-signed

#1740 fix stateroot on first run
  sequencer/dbmanager.go
  sequencer/finalizer.go
Labels: cla-signed

#1733 fix tests
  aggregator/aggregator.go
  aggregator/config.go
  config/default.go
  config/environments/local/local.node.config.toml
  sequencer/finalizer_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/docker-compose.yml
  tools/executor/main.go
Labels: cla-signed

#1744 allow reverted tx to be added to the pool
  pool/pool_test.go
  state/state.go
Labels: cla-signed

#1756 Fix/reorg pool
  pool/pool.go
  sequencer/dbmanager.go
  sequencer/finalizer_test.go
  sequencer/mock_worker.go
  state/pgstatestorage.go
  synchronizer/interfaces.go
  synchronizer/mock_pool.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#1722 Broadcast URI
  sequencer/broadcast/client.go
  sequencer/dbmanager.go
  state/state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/e2e/broadcast_test.go
Labels: cla-signed

#1650 JRPC - debug methods review
  .github/workflows/test-e2e.yml
  aggregator/mocks/mock_dbtx.go
  aggregator/mocks/mock_etherman.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_profitabilitychecker.go
  aggregator/mocks/mock_prover.go
  aggregator/mocks/mock_state.go
  aggregator/pb/aggregator.pb.go
  aggregator/pb/aggregator_grpc.pb.go
  ci/e2e-group5/debug_test.go
  ci/e2e-group5/shared.go
  docker-compose.yml
  docs/ci/groups.md
  etherman/mock_etherscan.go
  etherman/mock_ethgasstation.go
  ethtxmanager/mock_etherman_test.go
  ethtxmanager/mock_state_test.go
  gasprice/mock_etherman.go
  gasprice/mock_pool.go
  jsonrpc/endpoints_debug.go
  jsonrpc/endpoints_debug_test.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/interfaces.go
  jsonrpc/mock_dbtx_test.go
  jsonrpc/mock_pool_test.go
  jsonrpc/mock_state_test.go
  jsonrpc/mock_storage_test.go
  proto/src/proto/aggregator/v1/aggregator.proto
  proto/src/proto/executor/v1/executor.proto
  sequencer/broadcast/mocks/mock_state.go
  sequencer/mock_db_manager.go
  sequencer/mock_dbtx.go
  sequencer/mock_pool.go
  sequencer/mock_state.go
  sequencer/mock_worker.go
  state/runtime/executor/pb/executor.pb.go
  state/state.go
  state/types.go
  synchronizer/mock_dbtx.go
  synchronizer/mock_etherman.go
  synchronizer/mock_ethtxmanager.go
  synchronizer/mock_pool.go
  synchronizer/mock_state.go
  test/Makefile
  test/config/test.node.config.toml
  test/docker-compose.yml
  test/e2e/debug_test.go
  test/operations/manager.go
  test/operations/wait.go
Labels: cla-signed

#1737 Fix revert message for sc deployment tx reverted on the constructor
  docker-compose.yml
  test/e2e/jsonrpc_test.go
Labels: cla-signed

#1764 Change %w to %v in logs
  aggregator/aggregator.go
  aggregator/prover/prover.go
  ci/e2e-group1/forced_batches_test.go
  sequencer/closingsignalsmanager.go
  sequencer/finalizer.go
  state/state.go
  test/e2e/forcedbatches_test.go
  test/operations/manager.go
  test/scripts/sendForcedBatch/main.go
  tools/executor/main.go
Labels: cla-signed

#1718 [Aggregator] More fine-grained logs in case of prover errors
  aggregator/aggregator.go
Labels: Aggregator, cla-signed

#1768 Fix formatting in error logs
  log/log.go
Labels: cla-signed

#1765 Expire transactions
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  sequencer/addrqueue.go
  sequencer/closingsignalsmanager_test.go
  sequencer/config.go
  sequencer/dbmanager.go
  sequencer/dbmanager_test.go
  sequencer/efficiencylist.go
  sequencer/interfaces.go
  sequencer/mock_worker.go
  sequencer/sequencer.go
  sequencer/txtracker.go
  sequencer/worker.go
  sequencer/worker_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#1772 update prover image
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed

#1771 Fix/reorg
  ci/e2e-group1/constants.go
  ci/e2e-group1/forced_batches_test.go
  db/migrations/state/0003.sql
  pool/pool.go
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  state/helper.go
  state/pgstatestorage.go
Labels: cla-signed

#1738 add json rpc endpoints list
  README.md
  docs/json-rpc-endpoints.md
Labels: cla-signed

#1777 fix log
  sequencer/finalizer.go
Labels: cla-signed

#1786 fix claim pre execution
  aggregator/mocks/mock_dbtx.go
  aggregator/mocks/mock_etherman.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_profitabilitychecker.go
  aggregator/mocks/mock_prover.go
  aggregator/mocks/mock_state.go
  etherman/mock_etherscan.go
  etherman/mock_ethgasstation.go
  ethtxmanager/mock_etherman_test.go
  ethtxmanager/mock_state_test.go
  gasprice/mock_etherman.go
  gasprice/mock_pool.go
  jsonrpc/mock_dbtx_test.go
  jsonrpc/mock_pool_test.go
  jsonrpc/mock_state_test.go
  jsonrpc/mock_storage_test.go
  pool/pool.go
  sequencer/broadcast/mocks/mock_state.go
  sequencer/mock_db_manager.go
  sequencer/mock_dbtx.go
  sequencer/mock_pool.go
  sequencer/mock_state.go
  sequencer/mock_worker.go
  state/runtime/executor/errors.go
  state/state.go
  synchronizer/interfaces.go
  synchronizer/mock_dbtx.go
  synchronizer/mock_etherman.go
  synchronizer/mock_ethtxmanager.go
  synchronizer/mock_pool.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#1788 gas offset
  ethtxmanager/ethtxmanager.go
Labels: cla-signed

#1792 add support to jrpc to accept short hashes and addresses
  jsonrpc/endpoints_debug.go
  jsonrpc/endpoints_eth.go
  jsonrpc/types.go
  jsonrpc/types_test.go
Labels: cla-signed

#1797 Add restart policy to main docker-compose
  docker-compose.yml
Labels: cla-signed

#1804 log
  sequencer/finalizer.go
Labels: cla-signed

#1816 close grpc connection
  synchronizer/synchronizer.go
Labels: cla-signed

#1793 chore: remove `io/ioutil` package
  cmd/dumpstate.go
  config/network.go
  config/network_test.go
  etherman/etherman.go
  etherman/etherscan/etherscan.go
  etherman/ethgasstation/ethgasstation.go
  go.mod
  go.sum
  jsonrpc/server.go
  state/runtime/instrumentation/intrumentation_test.go
  state/state_test.go
  test/operations/wait.go
  test/scripts/cmd/compilesc/manager.go
  test/vectors/smartcontract.go
  test/vectors/statetransition.go
  tools/executor/main.go
Labels: cla-signed

#1802 Fix/hash address short string unmarshal
  encoding/encoding.go
  hex/hex.go
  jsonrpc/endpoints_eth.go
  jsonrpc/types.go
  jsonrpc/types_test.go
  state/helper.go
  tools/zkevmprovermock/server/executor.go
Labels: cla-signed

#1811 add check for not found tx and block for trace endpoints
  jsonrpc/endpoints_debug.go
  test/e2e/debug_test.go
Labels: cla-signed

#1799 Log startup info as JSON in production
  cmd/run.go
Labels: cla-signed

#1767 Relay jRPC methods to TrustedSequencer if pool info is needed
  db/scripts/single_db_server.sql
  docker-compose.yml
  jsonrpc/codec.go
  jsonrpc/codec_test.go
  jsonrpc/endpoints_eth.go
  test/Makefile
  test/config/test.permissionless.prover.config.json
  test/docker-compose.yml
Labels: cla-signed

#1814 fix: moving print for storing tx in finalizer.
  sequencer/finalizer.go
Labels: bug, Sequencer, cla-signed, blue-berry

#1837 Fix boot condition for GER signal being sent
  sequencer/closingsignalsmanager.go
Labels: cla-signed

#1831 Flush state db
  docker-compose.yml
  merkletree/pb/statedb.pb.go
  merkletree/pb/statedb_grpc.pb.go
  merkletree/tree.go
  proto/src/proto/statedb/v1/statedb.proto
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_state.go
  state/state.go
  test/docker-compose.yml
Labels: cla-signed, blue-berry

#1829 improve: adding additional info for txs moved to not ready
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/worker.go
Labels: Sequencer, Improvement, cla-signed, blue-berry

#1803 ForkID logic for an old batch and fix error handling in execute batch
  cmd/run.go
  etherman/etherman.go
  etherman/etherman_test.go
  etherman/types.go
  state/pgstatestorage.go
  state/state.go
  synchronizer/interfaces.go
  synchronizer/mock_etherman.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
Labels: Synchronizer, cla-signed, blue-berry

#1836 Prevent sequencer from getting blocked by sync if trusted state is more advanced than virtual state
  sequencer/sequencer.go
Labels: cla-signed

#1817 Add IP to Pool txs
  db/migrations/pool/0003.sql
  db/migrations/state/0004.sql
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/handler.go
  jsonrpc/interfaces.go
  jsonrpc/mock_pool_test.go
  jsonrpc/server.go
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/pool_test.go
  pool/transaction.go
  sequencer/worker.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  state/types.go
  synchronizer/interfaces.go
  synchronizer/mock_pool.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed, blue-berry

#1841 Avoid changes on go.mod
  .github/workflows/release.yml
Labels: cla-signed

#1842 fix pool ip
  db/migrations/pool/0004.sql
Labels: cla-signed

#1844 Reorg txs into the pool as pending wip
  aggregator/mocks/mock_dbtx.go
  aggregator/mocks/mock_etherman.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_profitabilitychecker.go
  aggregator/mocks/mock_prover.go
  aggregator/mocks/mock_state.go
  etherman/mock_etherscan.go
  etherman/mock_ethgasstation.go
  ethtxmanager/mock_etherman_test.go
  ethtxmanager/mock_state_test.go
  gasprice/mock_etherman.go
  gasprice/mock_pool.go
  jsonrpc/mock_dbtx_test.go
  jsonrpc/mock_pool_test.go
  jsonrpc/mock_state_test.go
  jsonrpc/mock_storage_test.go
  pool/pool.go
  sequencer/broadcast/mocks/mock_state.go
  sequencer/mock_db_manager.go
  sequencer/mock_dbtx.go
  sequencer/mock_pool.go
  sequencer/mock_state.go
  sequencer/mock_worker.go
  synchronizer/interfaces.go
  synchronizer/mock_dbtx.go
  synchronizer/mock_etherman.go
  synchronizer/mock_ethtxmanager.go
  synchronizer/mock_pool.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#1846 add fault tolerance when failed to get revert message
  test/operations/wait.go
Labels: cla-signed

#1840 Sync Trusted State via jRPC instead of Broadcast
  cmd/run.go
  hex/hex.go
  jsonrpc/client/client.go
  jsonrpc/client/zkevm.go
  jsonrpc/dbtxmanager.go
  jsonrpc/dbtxmanager_test.go
  jsonrpc/endpoints_debug.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_net.go
  jsonrpc/endpoints_txpool.go
  jsonrpc/endpoints_web3.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/errors.go
  jsonrpc/errors_test.go
  jsonrpc/handler.go
  jsonrpc/interfaces.go
  jsonrpc/mock_storage.go
  jsonrpc/mocks/mock_dbtx.go
  jsonrpc/mocks/mock_pool.go
  jsonrpc/mocks/mock_state.go
  jsonrpc/query.go
  jsonrpc/server.go
  jsonrpc/server_test.go
  jsonrpc/types.go
  jsonrpc/types/codec.go
  jsonrpc/types/codec_test.go
  jsonrpc/types/errors.go
  jsonrpc/types/errors_test.go
  jsonrpc/types/interfaces.go
  jsonrpc/types/query.go
  jsonrpc/types/types.go
  jsonrpc/types/types_test.go
  jsonrpc/types_test.go
  state/types.go
  synchronizer/interfaces.go
  synchronizer/mock_zkevmclient.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/Makefile
  test/e2e/debug_test.go
  test/e2e/jsonrpc_test.go
  test/operations/wait.go
Labels: cla-signed

#1868 New Logs and fix to GER Closing Signal
  sequencer/closingsignalsmanager.go
  sequencer/closingsignalsmanager_test.go
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_etherman.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  sequencer/worker.go
  state/pgstatestorage.go
  test/Makefile
Labels: cla-signed, blue-berry

#1866 Add logs to follow sequencer flow
  sequencer/finalizer.go
Labels: cla-signed, blue-berry

#1863 fix pool migration
  db/migrations/pool/0004.sql
  db/migrations/pool/0005.sql
Labels: cla-signed, blue-berry

#1865 Improve EthTxManager error handling
  ethtxmanager/ethtxmanager.go
Labels: cla-signed

#1876 Log OOC on reprocess full batch
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_state.go
  state/types.go
Labels: cla-signed, blue-berry

#1861 enable uncle tests and fix uncle enpoint parameters
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
Labels: cla-signed

#1878 fix
  sequencer/finalizer.go
  state/types.go
Labels: cla-signed

#1880 Fix substract bytes
  sequencer/batchresources.go
Labels: cla-signed, blue-berry

#1879 Halt finalizer in case of full execution error
  sequencer/finalizer.go
  sequencer/worker.go
  state/helper.go
  state/types.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/Makefile
Labels: cla-signed, blue-berry

#1882 check response before checking internal responses
  state/state.go
Labels: cla-signed

#1881 add debug endpoints to docs
  docs/json-rpc-endpoints.md
Labels: cla-signed

#1877 fix eth_getTransactionByBlockNumberAndIndex
  state/pgstatestorage.go
  test/e2e/jsonrpc_test.go
Labels: cla-signed

#1860 Improve E2E test time
  test/benchmarks/sequencer/common/setup/setup.go
  test/e2e/jsonrpc_test.go
  test/e2e/uniswap_test.go
  test/operations/manager.go
Labels: cla-signed

#1845 Update documentation software requirements to Ubuntu 22.04
  docs/production-setup.md
Labels: cla-signed

#1897 create group 7 and split e2e json rpc tests
  .github/workflows/test-e2e.yml
  ci/e2e-group4/jsonrpc1_test.go
  ci/e2e-group4/jsonrpc_test.go
  ci/e2e-group7/jsonrpc2_test.go
  ci/e2e-group7/shared.go
  test/Makefile
  test/e2e/jsonrpc1_test.go
  test/e2e/jsonrpc2_test.go
  test/e2e/shared.go
Labels: cla-signed

#1903 docker contracts update
  config/environments/local/local.genesis.config.json
  config/environments/local/local.node.config.toml
  docker-compose.yml
  etherman/etherman.go
  etherman/simulated.go
  etherman/smartcontracts/abi/polygonzkevm.abi
  etherman/smartcontracts/bin/polygonzkevm.bin
  etherman/smartcontracts/bin/polygonzkevmbridge.bin
  etherman/smartcontracts/bin/polygonzkevmglobalexitroot.bin
  etherman/smartcontracts/matic/matic.go
  etherman/smartcontracts/mockverifier/mockverifier.go
  etherman/smartcontracts/polygonzkevm/polygonzkevm.go
  etherman/smartcontracts/polygonzkevmbridge/polygonzkevmbridge.go
  etherman/smartcontracts/polygonzkevmglobalexitroot/polygonzkevmglobalexitroot.go
  jsonrpc/endpoints_debug.go
  test/config/debug.node.config.toml
  test/config/test.genesis.config.json
  test/config/test.node.config.toml
  test/docker-compose.yml
  test/e2e/debug_test.go
Labels: cla-signed

#1890 Truncate value in follower
  gasprice/follower.go
Labels: cla-signed

#1885 add a check to validate eth_call params
  jsonrpc/endpoints_eth.go
  test/e2e/jsonrpc2_test.go
Labels: cla-signed

#1907 feat: adding check gas price of tx to be greater that min gas price and min suggested gas price before adding to pool.
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/public/public.node.config.toml
  pool/config.go
  pool/errors.go
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/pool_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: RPC, Improvement, cla-signed, Pool

#1834 Feature/#1833 execute batch
  jsonrpc/client/zkevm.go
  state/state.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed, blue-berry

#1891 fix eth_call and eth_estimateGas parameters
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/mocks/mock_state.go
  jsonrpc/types/codec.go
  jsonrpc/types/interfaces.go
  jsonrpc/types/types.go
  state/state.go
  state/state_test.go
Labels: cla-signed, blue-berry

#1914 fix: fixing comments.
  cmd/run.go
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/public/public.node.config.toml
  jsonrpc/config.go
  pool/config.go
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/pool_test.go
  test/benchmarks/sequencer/common/setup/setup.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: RPC, cla-signed, Pool, blue-berry

#1908 Flush state db after setting genesis
  sequencer/closingsignalsmanager_test.go
  sequencer/dbmanager_test.go
  sequencer/finalizer_test.go
  state/state.go
Labels: cla-signed

#1920 Fix log L1 tx too big
  sequencer/sequencesender.go
Labels: cla-signed

#1917 fix missing return on ProcessUnsignedTransaction
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/mocks/mock_state.go
  jsonrpc/types/interfaces.go
  state/state.go
  state/state_test.go
Labels: cla-signed, blue-berry

#1922 fix: removing check for low gas price for claims.
  pool/pool.go
  pool/transaction.go
Labels: bug, RPC, cla-signed, Pool, blue-berry

#1925 fix forkID
  etherman/etherman.go
  etherman/etherman_test.go
  synchronizer/synchronizer.go
Labels: cla-signed

#1929 update docker prover forkid 4 + pql cfg improvements
  config/environments/public/postgresql.conf
  config/environments/public/public.prover.config.json
  docker-compose.yml
Labels: cla-signed

#1936 update license
  LICENSE
  README.md
Labels: cla-signed

#1941 Feature/mainnet config
  config/environments/mainnet/public.genesis.config.json
  config/environments/mainnet/public.node.config.toml
Labels: cla-signed

#1942 handle fea2scalar error
  proto/src/proto/executor/v1/executor.proto
  state/runtime/executor/pb/executor.pb.go
  state/runtime/executor/pb/executor_grpc.pb.go
  state/state.go
Labels: cla-signed

#1956 trustedsequencer url as config param
  cmd/run.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/public.node.config.toml
  synchronizer/config.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#1958 add deposit_counter to pool
  db/migrations/pool/0006.sql
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/pool_test.go
  pool/transaction.go
  sequencer/dbmanager.go
  test/Makefile
  test/e2e/pool_test.go
Labels: cla-signed

#1961 add EIP-1898 support to eth_call
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/types/codec.go
Labels: cla-signed

#1959 tos32 error handling
  proto/src/proto/executor/v1/executor.proto
  state/runtime/executor/errors.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/runtime.go
Labels: cla-signed

#1970 fix log without topics response
  db/migrations/state/0003.sql
  state/pgstatestorage.go
  state/state_test.go
  test/contracts/auto/EmitLog2.sol
  test/contracts/bin/EmitLog2/EmitLog2.go
  test/e2e/sc_test.go
Labels: cla-signed

#1964 fix BatchNumberByBlockNumber when batch is not found
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm_test.go
Labels: cla-signed

#1977 fix claims
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/mocks/mock_state.go
  jsonrpc/types/interfaces.go
  state/state.go
  state/state_test.go
Labels: cla-signed
