Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2023-05, with the labels that each got.

#2021 Do not use zkcounters on eth_Call
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
Labels: cla-signed

#2066 fix default trace values for custom tracers
  state/transaction.go
  test/e2e/debug_test.go
Labels: cla-signed

#2049 add support to safe and finalized blocks for jRPC block parameters
  jsonrpc/endpoints_zkevm.go
  jsonrpc/mocks/mock_state.go
  jsonrpc/types/codec.go
  jsonrpc/types/codec_test.go
  jsonrpc/types/interfaces.go
  state/pgstatestorage.go
  test/Makefile
Labels: cla-signed

#2030 cmd/approve
  cmd/approve.go
  cmd/main.go
  config/config.go
Labels: cla-signed

#2055 fix sync_info table
  state/pgstatestorage.go
  synchronizer/interfaces.go
  synchronizer/mock_etherman.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#2068 remove unit suffix from duration config params
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/public.node.config.toml
  config/environments/public/public.node.config.toml
  config/types/duration_test.go
  jsonrpc/config.go
  jsonrpc/server.go
  sequencer/config.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#2051 New sequence sender component
  cmd/main.go
  cmd/run.go
  config/config.go
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  event/event.go
  sequencer/config.go
  sequencer/sequencer.go
  sequencesender/config.go
  sequencesender/interfaces.go
  sequencesender/sequencesender.go
  test/Makefile
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/docker-compose.yml
  test/e2e/permissionlessrpc_test.go
  test/e2e/state_test.go
  test/e2e/uniswap_test.go
  test/operations/manager.go
Labels: cla-signed

#2076 Fix/deployment
  cmd/run.go
  config/environments/local/local.genesis.config.json
  db/scripts/init_prover_db.sql
  docker-compose.yml
  docs/production-setup.md
  etherman/etherman.go
  etherman/etherman_test.go
  synchronizer/interfaces.go
  synchronizer/mock_etherman.go
  synchronizer/synchronizer.go
  test/config/test.genesis.config.json
  test/scripts/sendForcedBatch/main.go
Labels: cla-signed

#2083 Review jRPC default configuration
  cmd/run.go
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/public.node.config.toml
  config/environments/public/public.node.config.toml
  jsonrpc/config.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_net.go
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/server.go
  jsonrpc/server_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#2090 config default values
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/public.node.config.toml
  config/environments/public/public.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#2091 Fix decode txs
  state/helper.go
Labels: cla-signed

#2094 configuration fixes
  config/default.go
  config/environments/local/local.node.config.toml
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed

#2093 Test/forced batches vectors
  .github/workflows/test-e2e.yml
  ci/e2e-group1/forced_batches_test.go
  ci/e2e-group9/forced_batches_test.go
  ci/e2e-group9/forced_batches_vector_test.go
  ci/e2e-group9/shared.go
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/sequencer.go
  state/batch.go
  state/runtime/executor/errors.go
  state/state_test.go
  test/Makefile
  test/benchmarks/sequencer/erc20-transfers/tx_sender.go
  test/benchmarks/sequencer/eth-transfers/tx_sender.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/config/test.prover.config.json
  test/constants/smart_contracts.go
  test/dbutils/dbutils.go
  test/e2e/forced_batches_test.go
  test/e2e/forced_batches_vector_test.go
  test/e2e/shared.go
  test/e2e/state_test.go
  test/operations/manager.go
  test/scripts/sendForcedBatch/main.go
  test/vectors/src/state-transition/forced-tx/erc20_0.json
  test/vectors/src/state-transition/forced-tx/eth-CallEcrecoverInvalidSignature.json
  test/vectors/src/state-transition/forced-tx/general_0.json
  test/vectors/src/state-transition/forced-tx/general_1.json
  test/vectors/src/state-transition/forced-tx/general_2.json
  test/vectors/src/state-transition/forced-tx/general_3.json
  test/vectors/src/state-transition/forced-tx/general_4.json
  test/vectors/src/state-transition/forced-tx/general_5.json
  test/vectors/src/state-transition/forced-tx/general_6.json
  test/vectors/src/state-transition/forced-tx/general_7.json
  test/vectors/src/state-transition/forced-tx/mynft_0.json
  test/vectors/src/state-transition/forced-tx/test-deploy_0.json
  test/vectors/src/state-transition/forced-tx/test-deploy_1.json
  test/vectors/src/state-transition/forced-tx/test-deploy_2.json
  test/vectors/src/state-transition/forced-tx/test-deploy_3.json
  test/vectors/src/state-transition/forced-tx/test-deploy_4.json
  test/vectors/src/state-transition/forced-tx/test-deploy_5.json
  test/vectors/src/state-transition/forced-tx/test-deploy_6.json
  test/vectors/src/state-transition/forced-tx/test-deploy_7.json
  test/vectors/src/state-transition/forced-tx/test-deploy_8.json
  test/vectors/src/state-transition/forced-tx/test-deploy_9.json
  test/vectors/src/state-transition/forced-tx/uniswapv2_1.json
  test/vectors/statetransition_v2.go
  test/vectors/vectors_v2.go
Labels: sequencer, improvement, e2e, test, cla-signed

#2095 Update link to protocol specification
  README.md
Labels: cla-signed

#2096 remove error logs when the error is related to the tx
  jsonrpc/endpoints_eth.go
Labels: cla-signed

#2100 fix: fixing forced batches error handling and normal batches transaction level error handling.
  pool/pool.go
  sequencer/finalizer.go
  state/converters.go
  state/runtime/executor/errors.go
  state/types.go
Labels: sequencer, state, cla-signed

#2105 Refactor state errors
  pool/pool.go
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  state/batch.go
  state/converters.go
  state/pgstatestorage.go
  state/state_test.go
  state/transaction.go
  state/types.go
  test/Makefile
Labels: cla-signed

#2108 Fix sequencer error
  sequencer/dbmanager.go
  state/batch.go
Labels: cla-signed

#2107 Disable auto release on GHA
  .goreleaser.yaml
Labels: cla-signed

#2112 Set timestamp resolution to 10s
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#2122 update executor proto
  proto/src/proto/executor/v1/executor.proto
  state/converters.go
  state/runtime/executor/pb/executor.pb.go
  state/types.go
Labels: cla-signed

#2125 Fix/main
  .gitignore
  aggregator/aggregator.go
  aggregator/aggregator_internal_test.go
  aggregator/interfaces.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_state.go
  aggregator/prover/client.go
  aggregator/prover/prover.go
  cmd/approve.go
  cmd/dumpstate.go
  cmd/main.go
  cmd/run.go
  config/config.debug.toml
  config/config.go
  config/config.local.toml
  config/config_test.go
  config/default.go
  config/genesis.go
  config/genesis.local.json
  config/network.go
  config/network_test.go
  db/migrations/state/0002.sql
  docker-compose.yml
  etherman/config.go
  etherman/etherman.go
  ethtxmanager/config.go
  ethtxmanager/ethtxmanager.go
  ethtxmanager/interfaces.go
  go.mod
  go.sum
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/transaction.go
  sequencer/batchbuilder.go
  sequencer/config.go
  sequencer/interfaces.go
  sequencer/mocks/mock_txmanager.go
  sequencer/sequencer.go
  sequencer/sequencer_test.go
  sequencer/sequencesender.go
  state/batch.go
  state/converters.go
  state/pgstatestorage.go
  state/proof.go
  state/state.go
  state/state_test.go
  synchronizer/config.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/config/config.test.toml
  test/constants/environment_variables.go
  test/e2e/broadcast_test.go
  test/operations/manager.go
  tools/genesis/generator.go
Labels: cla-signed

#2129 improve: splitting the forced batches tests in 3 groups
  .github/workflows/test-e2e.yml
  ci/e2e-group10/forced_batches_test.go
  ci/e2e-group10/forced_batches_vector_group2_test.go
  ci/e2e-group11/forced_batches_vector_group3_test.go
  ci/e2e-group9/forced_batches_vector_group1_test.go
  ci/e2e-group9/shared.go
  test/Makefile
  test/vectors/src/state-transition/forced-tx/group1/general_0.json
  test/vectors/src/state-transition/forced-tx/group1/general_1.json
  test/vectors/src/state-transition/forced-tx/group1/general_2.json
  test/vectors/src/state-transition/forced-tx/group1/general_3.json
  test/vectors/src/state-transition/forced-tx/group1/general_4.json
  test/vectors/src/state-transition/forced-tx/group1/general_5.json
  test/vectors/src/state-transition/forced-tx/group1/general_6.json
  test/vectors/src/state-transition/forced-tx/group1/general_7.json
  test/vectors/src/state-transition/forced-tx/group2/erc20_0.json
  test/vectors/src/state-transition/forced-tx/group2/eth-CallEcrecoverInvalidSignature.json
  test/vectors/src/state-transition/forced-tx/group2/mynft_0.json
  test/vectors/src/state-transition/forced-tx/group2/test-deploy_0.json
  test/vectors/src/state-transition/forced-tx/group2/test-deploy_1.json
  test/vectors/src/state-transition/forced-tx/group2/test-deploy_2.json
  test/vectors/src/state-transition/forced-tx/group2/uniswapv2_1.json
  test/vectors/src/state-transition/forced-tx/group3/test-deploy_3.json
  test/vectors/src/state-transition/forced-tx/group3/test-deploy_4.json
  test/vectors/src/state-transition/forced-tx/group3/test-deploy_5.json
  test/vectors/src/state-transition/forced-tx/group3/test-deploy_6.json
  test/vectors/src/state-transition/forced-tx/group3/test-deploy_7.json
  test/vectors/src/state-transition/forced-tx/group3/test-deploy_8.json
  test/vectors/src/state-transition/forced-tx/group3/test-deploy_9.json
Labels: e2e, test, cla-signed

#2148 Check for overflow while decoding txs
  docker-compose.yml
  state/helper.go
  state/helper_test.go
  test/docker-compose.yml
Labels: cla-signed
