Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2023-02, with the labels that each got.

#1603 [Aggregator] Add recovery mechanism for stuck proofs
  aggregator/aggregator.go
  aggregator/aggregator_test.go
  aggregator/config.go
  aggregator/interfaces.go
  aggregator/mocks/mock_state.go
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  db/migrations/state/0006.sql
  gasprice/mock_etherman.go
  gasprice/mock_pool.go
  go.sum
  sequencer/mocks/mock_pool.go
  state/errors.go
  state/helper.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  state/proof.go
  test/Makefile
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/scripts/batchsender/main.go
Labels: Aggregator, cla-signed

#1620 Fix RLP not working properly on executor
  state/converters.go
Labels: cla-signed

#1616 Feature/new sequencer finalizer
  cmd/run.go
  config/environments/local/local.node.config.toml
  config/environments/public/public.node.config.toml
  metrics/api.go
  metrics/config.go
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  test/benchmarks/sequencer/common/metrics/metrics.go
  test/benchmarks/sequencer/erc20-transfers/pool_processing_erc20_test.go
  test/benchmarks/sequencer/eth-transfers/pool_processing_eth_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/docker-compose.yml
Labels: cla-signed

#1623 Fix closing signals
  sequencer/closingsignalsmanager_test.go
  state/pgstatestorage.go
  test/config/test.node.config.toml
Labels: cla-signed

#1604 [Aggregator] Add new prover_name field
  aggregator/aggregator.go
  aggregator/aggregator_test.go
  aggregator/interfaces.go
  aggregator/mocks/mock_prover.go
  aggregator/pb/aggregator.pb.go
  aggregator/pb/aggregator_grpc.pb.go
  aggregator/prover/prover.go
  db/migrations/state/0006.sql
  merkletree/pb/statedb.pb.go
  merkletree/pb/statedb_grpc.pb.go
  proto/src/proto/aggregator/v1/aggregator.proto
  sequencer/broadcast/pb/broadcast.pb.go
  sequencer/broadcast/pb/broadcast_grpc.pb.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  state/proof.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/executor/pb/executor_grpc.pb.go
  test/config/test.prover.config.json
Labels: Aggregator, cla-signed

#1612 Feature/#1579 migrations index
  cmd/run.go
  db/migrations/state/0002_test.go
  db/migrations/state/0003_test.go
  db/migrations/state/0004_test.go
  db/migrations/state/0005.sql
  db/migrations/state/0005_test.go
  db/migrations/state/0006.sql
  db/migrations/state/0006_test.go
  db/migrations/state/utils_test.go
  state/pgstatestorage.go
  test/dbutils/dbutils.go
Labels: cla-signed

#1625 adding wip fixes and the closing signal emit from the sequencesender
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  state/state.go
Labels: cla-signed

#1606 migration test + indexes
  cmd/run.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/public/public.node.config.toml
  db/migrations/state/0002_test.go
  db/migrations/state/0003_test.go
  db/migrations/state/0004_test.go
  db/migrations/state/0005.sql
  db/migrations/state/0005_test.go
  db/migrations/state/0006.sql
  db/migrations/state/0006_test.go
  db/migrations/state/utils_test.go
  state/pgstatestorage.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/dbutils/dbutils.go
Labels: cla-signed

#1630 fix forced batch query
  sequencer/closingsignalsmanager.go
  sequencer/finalizer.go
  state/pgstatestorage.go
Labels: cla-signed

#1633 log RLP decoding error
  state/converters.go
  state/state.go
  state/state_test.go
  state/types.go
Labels: cla-signed

#1635 L1Timeout
  sequencer/closingsignalsmanager.go
  sequencer/closingsignalsmanager_test.go
  sequencer/dbmanager.go
  sequencer/dbmanager_test.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_state.go
  state/pgstatestorage.go
  test/config/test.node.config.toml
Labels: cla-signed

#1639 wip: fixing forced batches.
  sequencer/closingsignalsmanager.go
  sequencer/finalizer.go
Labels: Sequencer, cla-signed

#1637 Implement fork id in node
  aggregator/aggregator.go
  aggregator/config.go
  aggregator/pb/aggregator.pb.go
  aggregator/pb/aggregator_grpc.pb.go
  aggregator/prover/prover.go
  cmd/run.go
  config/config.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/public/public.prover.config.json
  docker-compose.yml
  etherman/errors.go
  etherman/etherman.go
  merkletree/pb/statedb.pb.go
  merkletree/pb/statedb_grpc.pb.go
  proto/src/proto/aggregator/v1/aggregator.proto
  proto/src/proto/executor/v1/executor.proto
  sequencer/broadcast/pb/broadcast.pb.go
  sequencer/broadcast/pb/broadcast_grpc.pb.go
  state/config.go
  state/forkid.go
  state/runtime/executor/errors.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/runtime.go
  state/state.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/config/test.prover.config.json
  test/docker-compose.yml
Labels: cla-signed

#1641 Support fork Id in V2
  aggregator/aggregator.go
  aggregator/config.go
  aggregator/pb/aggregator.pb.go
  aggregator/pb/aggregator_grpc.pb.go
  aggregator/prover/prover.go
  cmd/run.go
  config/config.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/public/public.prover.config.json
  docker-compose.yml
  etherman/errors.go
  etherman/etherman.go
  merkletree/pb/statedb.pb.go
  merkletree/pb/statedb_grpc.pb.go
  proto/src/proto/aggregator/v1/aggregator.proto
  proto/src/proto/executor/v1/executor.proto
  sequencer/broadcast/pb/broadcast.pb.go
  sequencer/broadcast/pb/broadcast_grpc.pb.go
  state/config.go
  state/forkid.go
  state/runtime/executor/errors.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/runtime.go
  state/state.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/config/test.prover.config.json
  test/docker-compose.yml
Labels: cla-signed

#1644 bring changes from v0.0.2 rc2
  aggregator/aggregator.go
  aggregator/config.go
  aggregator/pb/aggregator.pb.go
  aggregator/pb/aggregator_grpc.pb.go
  aggregator/prover/prover.go
  cmd/run.go
  config/config.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/public/public.prover.config.json
  docker-compose.yml
  etherman/errors.go
  etherman/etherman.go
  merkletree/pb/statedb.pb.go
  merkletree/pb/statedb_grpc.pb.go
  proto/src/proto/aggregator/v1/aggregator.proto
  proto/src/proto/executor/v1/executor.proto
  sequencer/broadcast/pb/broadcast.pb.go
  sequencer/broadcast/pb/broadcast_grpc.pb.go
  state/config.go
  state/forkid.go
  state/runtime/executor/errors.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/runtime.go
  state/state.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/config/test.prover.config.json
  test/docker-compose.yml
Labels: cla-signed

#1645 decode txs
  sequencer/dbmanager.go
Labels: cla-signed

#1642 Cherry-pick RLP fix into release/v0.0.2
  state/converters.go
  state/state.go
  state/state_test.go
  state/types.go
Labels: cla-signed

#1643 Cherry-pick RLP fix into develop
  state/converters.go
  state/state.go
  state/state_test.go
  state/types.go
Labels: cla-signed

#1617 Feature/#1615 rlp
  config/environments/public/public.node.config.toml
  state/state_test.go
  test/scripts/sendForcedBatch/main.go
  test/vectors/src/tx-hash-ethereum/rlp.json
  tools/rlp/main.go
Labels: cla-signed

#1647 update executor image to e7ac5c4
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed

#1651 Feature/new sequencer finalizer
  aggregator/mocks/mock_etherman.go
  aggregator/mocks/mock_ethtxmanager.go
  aggregator/mocks/mock_profitabilitychecker.go
  aggregator/mocks/mock_prover.go
  aggregator/mocks/mock_state.go
  etherman/mock_etherscan.go
  etherman/mock_ethgasstation.go
  ethtxmanager/mock_etherman_test.go
  ethtxmanager/mock_state_test.go
  gasprice/mock_etherman.go
  gasprice/mock_pool.go
  jsonrpc/mock_dbtx_test.go
  jsonrpc/mock_pool_test.go
  jsonrpc/mock_state_test.go
  jsonrpc/mock_storage_test.go
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_dbtx.go
  sequencer/mock_pool.go
  sequencer/mock_state.go
  sequencer/mock_worker.go
  sequencer/mocks/mock_etherman.go
  sequencer/mocks/mock_ethtxmanager.go
  sequencer/sequencer.go
  sequencer/sequencesender.go
  state/state.go
  synchronizer/interfaces.go
  synchronizer/mock_dbtx.go
  synchronizer/mock_etherman.go
  synchronizer/mock_ethtxmanager.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  test/benchmarks/sequencer/eth-transfers/pool_processing_eth_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/e2e/ethtransfer_test.go
Labels: Sequencer, cla-signed

#1638 genesis block check
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/public/public.node.config.toml
  etherman/errors.go
  etherman/etherman.go
  synchronizer/interfaces.go
  synchronizer/mock_etherman.go
  synchronizer/synchronizer.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#1654 Feature/new sequencer finalizer
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: Sequencer, cla-signed

#1648 Feature/new smc fork
  cmd/run.go
  config/config_test.go
  config/default.go
  config/environments/local/local.genesis.config.json
  config/environments/local/local.node.config.toml
  config/environments/public/public.genesis.config.json
  config/network.go
  config/network_test.go
  db/migrations/state/0006.sql
  db/migrations/state/0006_test.go
  docker-compose.yml
  docs/running_local.md
  etherman/etherman.go
  etherman/etherman_test.go
  etherman/simulated.go
  etherman/smartcontracts/abi/polygonzkevm.abi
  etherman/smartcontracts/abi/polygonzkevmbridge.abi
  etherman/smartcontracts/abi/polygonzkevmglobalexitroot.abi
  etherman/smartcontracts/bin/mockverifier.bin
  etherman/smartcontracts/bin/polygonzkevm.bin
  etherman/smartcontracts/bin/polygonzkevmbridge.bin
  etherman/smartcontracts/bin/polygonzkevmglobalexitroot.bin
  etherman/smartcontracts/mockverifier/mockverifier.go
  etherman/smartcontracts/polygonzkevm/polygonzkevm.go
  etherman/smartcontracts/polygonzkevmbridge/polygonzkevmbridge.go
  etherman/smartcontracts/polygonzkevmglobalexitroot/polygonzkevmglobalexitroot.go
  etherman/types.go
  pool/pool.go
  sequencer/sequencer_test.go
  state/batch.go
  state/forkid.go
  state/genesis.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  state/state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/config/debug.node.config.toml
  test/config/test.genesis.config.json
  test/config/test.node.config.toml
  test/docker-compose.yml
  test/operations/manager.go
  test/scripts/batchsender/main.go
Labels: cla-signed

#1664 wip fixes
  sequencer/finalizer.go
  sequencer/worker.go
  state/pgstatestorage.go
  state/transaction.go
  test/operations/manager.go
Labels: cla-signed

#1656 Fix migrations check at startup with a read-only connection
  db/db.go
Labels: bug, cla-signed

#1661 fix zkevm response to hex and open-rpc refs
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm.openrpc.json
  jsonrpc/endpoints_zkevm_test.go
Labels: cla-signed

#1671 Fix closing signals manager and pool
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  pool/pgpoolstorage/pgpoolstorage.go
  sequencer/closingsignalsmanager.go
  sequencer/config.go
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_state.go
  state/pgstatestorage.go
  synchronizer/mock_etherman.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#1668 Fix/random forced
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test-from-prover.yml
  .github/workflows/test-full-non-e2e.yml
  .github/workflows/updatedeps.yml
  Dockerfile
  README.md
  docs/ci/groups.md
  etherman/etherman.go
  etherman/etherman_test.go
  etherman/types/sequence.go
  go.mod
  go.sum
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/sequencesender.go
  state/errors.go
  state/helper.go
  state/helper_test.go
  state/runtime/fakevm/fakevm.go
  state/runtime/instrumentation/js/goja.go
  state/state.go
  synchronizer/synchronizer.go
  test/scripts/batchsender/main.go
  test/scripts/sendForcedBatch/README.md
  tools/zkevmprovermock/Dockerfile
Labels: cla-signed

#1377 WIP: E2E Filter tests
  jsonrpc/endpoints_eth.go
  test/e2e/jsonrpc_test.go
Labels: cla-signed

#1663 Remove MtServer from config
  config/default.go
  config/environments/local/local.node.config.toml
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#1677 Feature/#1676 trusted reorg
  cmd/run.go
  db/migrations/state/0002.sql
  db/migrations/state/0002_test.go
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/pool_test.go
  pool/transaction.go
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_pool.go
  sequencer/sequencer.go
  sequencer/worker.go
  state/helper.go
  state/pgstatestorage.go
  state/state.go
  state/state_test.go
  state/types.go
  synchronizer/interfaces.go
  synchronizer/mock_pool.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/Makefile
Labels: cla-signed

#1681 Port migrations-check fix into develop
  db/db.go
Labels: bug, cla-signed

#1682 Fixes executor ip in pool tests
  pool/pool_test.go
Labels: cla-signed

#1684 comment l2 reorg
  sequencer/dbmanager.go
Labels: cla-signed

#1683 Tests/benchmark scripts
  .gitignore
  state/pgstatestorage.go
  test/benchmarks/sequencer/common/metrics/metrics.go
  test/benchmarks/sequencer/common/params/constants.go
  test/benchmarks/sequencer/common/params/variables.go
  test/benchmarks/sequencer/common/setup/setup.go
  test/benchmarks/sequencer/common/transactions/transactions.go
  test/benchmarks/sequencer/erc20-transfers/pool_processing_erc20_test.go
  test/benchmarks/sequencer/erc20-transfers/tx_sender.go
  test/benchmarks/sequencer/eth-transfers/pool_processing_eth_test.go
  test/benchmarks/sequencer/eth-transfers/tx_sender.go
  test/benchmarks/sequencer/scripts/common/environment/constants.go
  test/benchmarks/sequencer/scripts/common/environment/init.go
  test/benchmarks/sequencer/scripts/common/results/print.go
  test/benchmarks/sequencer/scripts/erc20-transfers/main.go
  test/benchmarks/sequencer/scripts/eth-transfers/main.go
Labels: Sequencer, benchmark, test, cla-signed

#1686 do not sequence empty batches
  sequencer/finalizer.go
  sequencer/finalizer_test.go
Labels: cla-signed

#1688 Detect L2 reorgs by counting number of reorgs
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_state.go
  state/pgstatestorage.go
Labels: cla-signed

#1692 New Sequencer Strategy
  ethtxmanager/ethtxmanager.go
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  state/state.go
  state/state_test.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#1700 Fix final proof encoding
  etherman/etherman.go
Labels: cla-signed

#1687 Intrinsic gas too low
  pool/errors.go
  pool/pool.go
  pool/pool_test.go
  pool/transaction.go
  pool/transaction_test.go
Labels: cla-signed

#1703 approve command with wei
  cmd/approve.go
  config/config_test.go
  config/default.go
  etherman/etherman.go
  test/Makefile
  test/docker-compose.yml
  test/operations/manager.go
  test/scripts/sendForcedBatch/README.md
Labels: cla-signed

#1696 bugfix: adding deletion of invalid txs from pool db in the finalizer.
  sequencer/addrqueue.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_worker.go
  sequencer/worker.go
Labels: cla-signed

#1706 allow forcing gas in eth tx manager
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  etherman/etherman.go
  ethtxmanager/config.go
  ethtxmanager/ethtxmanager.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#1698 improve: adding logging to Worker
  sequencer/addrqueue.go
  sequencer/worker.go
  test/Makefile
Labels: cla-signed

#1704 fix pool pre-execution nonce
  db/migrations/pool/0002.sql
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/pool_test.go
  pool/transaction.go
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_pool.go
Labels: cla-signed

#1707 improve: adding check for claims in Worker to have efficiency=MaxFloa…
  sequencer/txtracker.go
Labels: cla-signed

#1708 fix mock prover
  test/docker-compose.yml
  test/operations/manager.go
Labels: cla-signed

#1691 [Aggregator] Do not return in case of final proof error
  aggregator/aggregator.go
  aggregator/aggregator_test.go
Labels: bug, Aggregator, cla-signed

#1710 get nonce from state
  pool/interfaces.go
  pool/pool.go
  state/state.go
Labels: cla-signed
