Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2023-11, with the labels that each got.

#2742 Properly handle sequenced empty batches with GER Update
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/sequencer.go
Labels: cla-signed

#2743 Properly handle sequenced empty batches with GER Update (#2742)
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/sequencer.go
Labels: cla-signed

#2746 update stream library
  go.mod
  go.sum
  sequencer/sequencer.go
  tools/datastreamer/main.go
Labels: cla-signed

#2747 Cherrypick/stream fromv0.3.3
  go.mod
  go.sum
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/sequencer.go
  tools/datastreamer/main.go
Labels: cla-signed

#2751 Fix release process: version binaries, patch > 9, testnet.zip file
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: cla-signed

#2749 Reduce vulnerabilities
  Dockerfile
  go.mod
  go.sum
Labels: cla-signed, zkevm-seq-agg

#2741 Fix missing pool.Config parameter when creating a new Sequencer
  cmd/run.go
  pool/effectivegasprice.go
  sequencer/finalizer.go
  sequencer/sequencer.go
Labels: cla-signed, zkevm-seq-agg

#2766 Cherry pick effective gas prices fixes (#2738, #2741) to develop branch
  cmd/run.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/node.config.toml
  pool/effectivegasprice.go
  sequencer/finalizer.go
  sequencer/sequencer.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#2768 + renamed config vars for L1 parallel sync
  cmd/run.go
  config/config_test.go
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  docs/design/synchronizer/l1_synchronization.md
  synchronizer/config.go
  synchronizer/l1_rollup_info_consumer.go
  synchronizer/l1_rollup_info_consumer_statistics.go
  synchronizer/l1_rollup_info_consumer_statistics_test.go
  synchronizer/l1_rollup_info_consumer_test.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/config/test.node.config.toml
Labels: synchronizer, cla-signed, config, zkevm-bridge-sync-rpc

#2750 Fix e2e group 10 (forced batches)
  ci/e2e-group10/forced_batches_vector_shared.go
  ci/e2e-group11/forced_batches_vector_shared.go
  ci/e2e-group9/forced_batches_vector_shared.go
  test/Makefile
  test/e2e/forced_batches_test.go
  test/e2e/forced_batches_vector_group1_test.go
  test/e2e/forced_batches_vector_group2_test.go
  test/e2e/forced_batches_vector_group3_test.go
  test/e2e/forced_batches_vector_shared.go
  test/e2e/shared.go
  test/operations/manager.go
Labels: test, cla-signed, zkevm-bridge-sync-rpc

#2773 Refactor State: Step 1
  cmd/dumpstate.go
  cmd/run.go
  pool/pool_test.go
  sequencer/closingsignalsmanager_test.go
  sequencer/dbmanager_test.go
  state/batch.go
  state/forkid.go
  state/genesis.go
  state/helper.go
  state/helper_test.go
  state/interfaces.go
  state/pgstatestorage.go
  state/pgstatestorage/batch.go
  state/pgstatestorage/block.go
  state/pgstatestorage/datastream.go
  state/pgstatestorage/forcedbatch.go
  state/pgstatestorage/forkid.go
  state/pgstatestorage/globalexitroot.go
  state/pgstatestorage/interfaces.go
  state/pgstatestorage/l2block.go
  state/pgstatestorage/pgstatestorage.go
  state/pgstatestorage/pgstatestorage_test.go
  state/pgstatestorage/proof.go
  state/pgstatestorage/syncinginfo.go
  state/pgstatestorage/transaction.go
  state/state.go
  state/state_test.go
  state/transaction.go
  test/e2e/pool_test.go
  test/operations/manager.go
  tools/datastreamer/main.go
  tools/state/reprocess_cmd.go
Labels: cla-signed

#2761 Fix e2e group 8 (debug trace)
  test/e2e/debug_calltracer_test.go
  test/e2e/debug_shared.go
Labels: cla-signed

#2777 Added L2GasPriceSuggesterFactor config parameter to simulate estimated L2 gas price (EGP disabled)
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  pool/config.go
  pool/effectivegasprice.go
  pool/effectivegasprice_test.go
  pool/pool.go
  pool/pool_test.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed, config, zkevm-seq-agg

#2769 add queue to ws subscription filters
  jsonrpc/endpoints_eth.go
  jsonrpc/query.go
  state/l2block.go
  state/pgstatestorage.go
  state/queue.go
  state/queue_test.go
Labels: cla-signed

#2779 add queue to ws subscription filters (#2769)
  jsonrpc/endpoints_eth.go
  jsonrpc/query.go
  state/l2block.go
  state/pgstatestorage/l2block.go
  state/queue.go
  state/queue_test.go
Labels: cla-signed

#2790 replace atomic wsConn by concurrentWsConn (#2782)
  jsonrpc/endpoints_debug.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/handler.go
  jsonrpc/interfaces.go
  jsonrpc/mock_storage.go
  jsonrpc/query.go
  jsonrpc/server.go
  jsonrpc/storage.go
  jsonrpc/wsconn.go
  state/infinite.go
  state/l2block.go
  state/queue.go
  state/state.go
Labels: cla-signed

#2793 Update GER on closed batch without txs
  sequencer/finalizer.go
  sequencer/finalizer_test.go
Labels: cla-signed

#2795 Update GER on closed batch without txs (#2793)
  sequencer/finalizer.go
  sequencer/finalizer_test.go
Labels: cla-signed, cherry-pick

#2794 Update GER on closed batch without txs (#2793)
  sequencer/finalizer.go
  sequencer/finalizer_test.go
Labels: cla-signed, cherry-pick

#2785 Fix data stream tool performance
  go.mod
  go.sum
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  state/datastream.go
  state/interfaces.go
  state/pgstatestorage/datastream.go
  tools/datastreamer/Makefile
Labels: cla-signed

#2796 Fix data stream tool performance (#2785)
  go.mod
  go.sum
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  state/datastream.go
  state/pgstatestorage.go
  tools/datastreamer/Makefile
Labels: cla-signed

#2797 Fix data stream tool performance (#2785)
  go.mod
  go.sum
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  state/datastream.go
  state/pgstatestorage.go
  tools/datastreamer/Makefile
Labels: cla-signed

#2786 L1InfoTree implementation + tests
  l1infotree/hash.go
  l1infotree/hash_test.go
  l1infotree/tree.go
  l1infotree/tree_test.go
  test/vectors/l1infotree.go
  test/vectors/src/merkle-tree/l1-info-tree/root-vectors.json
Labels: cla-signed

#2800 cherry pick the latest WS improvements into v0.4.0
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/interfaces.go
  jsonrpc/mock_storage.go
  jsonrpc/query.go
  jsonrpc/storage.go
  state/l2block.go
  state/pgstatestorage.go
Labels: cla-signed

#2802 Update prover images used in docker compose files to v3.0.2
  db/migrations/pool/0011.sql
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed

#2722 etherman: read tx with blockHash and txIndex instead of txHash
  etherman/etherman.go
Labels: cla-signed

#2804 Fix tx size check (#2799)
  cmd/run.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  pool/config.go
  pool/pool.go
  sequencer/txtracker.go
  state/helper.go
Labels: cla-signed, cherry-pick

#2805 Cherry-pick #2777: Added L2GasPriceSuggesterFactor config parameter to simulate estimated L2 gas price (EGP disabled)
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  pool/config.go
  pool/effectivegasprice.go
  pool/effectivegasprice_test.go
  pool/pool.go
  pool/pool_test.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#2807 set sequential mode as default
  config/config_test.go
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  test/config/test.node.config.toml
Labels: synchronizer, cla-signed, config

#2803 Fix typos
  docs/ci/actions.md
  docs/ci/groups.md
  docs/ci/ok-to-test.md
  docs/configuration.md
  docs/production-setup.md
  docs/running_local.md
  docs/snap_restore.md
  docs/zkEVM-custom-endpoints.md
Labels: cla-signed

#2812 Refactor incaberry L1 event executors to another files to avoid modificate it when implement ETROG fork
  state/forkid.go
  state/forkid_test.go
  synchronizer/actions/actions.go
  synchronizer/actions/incaberry/processor_base.go
  synchronizer/actions/incaberry/processor_l1_forced_batches.go
  synchronizer/actions/incaberry/processor_l1_forced_batches_test.go
  synchronizer/actions/incaberry/processor_l1_forkid.go
  synchronizer/actions/incaberry/processor_l1_global_exit_root.go
  synchronizer/actions/incaberry/processor_l1_sequence_batches.go
  synchronizer/actions/incaberry/processor_l1_sequence_batches_test.go
  synchronizer/actions/incaberry/processor_l1_sequence_force_batches.go
  synchronizer/actions/incaberry/processor_l1_trusted_verify_batch.go
  synchronizer/actions/processor_manager/processor_manager.go
  synchronizer/actions/processor_manager/processor_manager_test.go
  synchronizer/actions/processor_manager/processors_builder.go
  synchronizer/default_l1processors.go
  synchronizer/interfaces.go
  synchronizer/l1event_orders/sequence_extractor.go
  synchronizer/mock_state.go
  synchronizer/mocks/mock_dbtx.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/Makefile
Labels: synchronizer, improvement, cla-signed, zkevm-bridge-sync-rpc

#2658 feature: storing LER in state.batch on successful transaction processing
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  state/pgstatestorage.go
Labels: sequencer, improvement, cla-signed, zkevm-seq-agg

#2825 new ger event
  etherman/etherman.go
Labels: cla-signed

#2663 new tracers
  docker-compose.yml
  jsonrpc/endpoints_debug.go
  proto/src/proto/executor/v1/executor.proto
  state/converters.go
  state/fakedb.go
  state/runtime/executor/executor.pb.go
  state/runtime/instrumentation/executortrace.go
  state/runtime/instrumentation/structlog.go
  state/runtime/instrumentation/tracers/structlogger/structlogger.go
  state/runtime/runtime.go
  state/trace.go
  state/transaction.go
  state/types.go
  test/docker-compose.yml
  test/operations/manager.go
Labels: cla-signed

#2830 add response headers to all http responses (#2829)
  jsonrpc/server.go
  jsonrpc/server_test.go
Labels: rpc, cla-signed

#2818 fork-etrog: synchronizer: update L1InfoTree
  db/migrations/state/0013.sql
  db/migrations/state/0013_test.go
  etherman/etherman.go
  etherman/etherman_test.go
  etherman/types.go
  l1infotree/hash.go
  l1infotree/tree_test.go
  state/interfaces.go
  state/l1infotree.go
  state/pgstatestorage/l1infotree.go
  state/pgstatestorage/pgstatestorage_test.go
  synchronizer/actions/etrog/etrog.go
  synchronizer/actions/etrog/processor_l1_info_tree_update.go
  synchronizer/actions/etrog/processor_l1_info_tree_update_test.go
  synchronizer/actions/incaberry/incaberry.go
  synchronizer/actions/incaberry/processor_l1_forced_batches.go
  synchronizer/actions/incaberry/processor_l1_forkid.go
  synchronizer/actions/incaberry/processor_l1_global_exit_root.go
  synchronizer/actions/incaberry/processor_l1_info_tree_update.go
  synchronizer/actions/incaberry/processor_l1_sequence_batches.go
  synchronizer/actions/incaberry/processor_l1_sequence_batches_test.go
  synchronizer/actions/incaberry/processor_l1_sequence_force_batches.go
  synchronizer/actions/incaberry/processor_l1_verify_batch.go
  synchronizer/actions/processor_base.go
  synchronizer/actions/processor_manager/test/mock_processor.go
  synchronizer/actions/processor_manager/test/processor_manager_test.go
  synchronizer/actions/processor_manager/test/processors_builder_test.go
  synchronizer/default_l1processors.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#2833 udpate hashdb proto
  merkletree/hashdb/hashdb.pb.go
  merkletree/hashdb/hashdb_grpc.pb.go
  merkletree/tree.go
  proto/src/proto/hashdb/v1/hashdb.proto
Labels: cla-signed

#2834 Refactor finalizer: remove use of f.processRequest, move getLastBatchNumAndOldStateRoot function
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/sequencer.go
  sequencer/txsorted_list.go
Labels: cla-signed, zkevm-seq-agg

#2838 fix e2e group 5
  test/e2e/debug_test.go
Labels: ci/cd, cla-signed, zkevm-bridge-sync-rpc

#2835 Refactor finalizer: remove sharedResourcesMux, reduce logs with info level
  sequencer/finalizer.go
  sequencer/finalizer_test.go
Labels: cla-signed, zkevm-seq-agg

#2844 etrog: L1InfoTreeIndex is 32bits
  state/interfaces.go
  state/l1infotree.go
  state/pgstatestorage/l1infotree.go
  state/pgstatestorage/pgstatestorage_test.go
Labels: state, cla-signed, zkevm-bridge-sync-rpc

#2853 expose SkipFirstChangeL2Block
  state/batchV2.go
  state/types.go
Labels: cla-signed, zkevm-seq-agg

#2860 Compute wip batch during stream delta calculation
  sequencer/interfaces.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  state/datastream.go
  state/pgstatestorage.go
  tools/datastreamer/main.go
Labels: cla-signed, zkevm-seq-agg

#2862 fix camelCase to snake_function that fails in MAC
  test/Makefile
Labels: cla-signed

#2861 Compute wip batch during stream delta calculation
  sequencer/interfaces.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  state/datastream.go
  state/pgstatestorage.go
  tools/datastreamer/main.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#2864 compute wip batch during stream delta calculation
  sequencer/interfaces.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  state/datastream.go
  state/interfaces.go
  state/pgstatestorage/datastream.go
  tools/datastreamer/main.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#2867 udpate DS lib
  go.mod
  go.sum
Labels: zkevm-seq-agg

#2866 udpate DS lib
  go.mod
  go.sum
Labels: cla-signed, zkevm-seq-agg

#2855 Compute and store l2 tx hash
  db/migrations/state/0013.sql
  db/migrations/state/0013_test.go
  merkletree/key.go
  merkletree/key_test.go
  merkletree/split.go
  merkletree/split_test.go
  merkletree/tree.go
  state/batch.go
  state/batchV2.go
  state/pgstatestorage/l2block.go
  state/test/l2txhash_test.go
  state/transaction.go
Labels: cla-signed, zkevm-seq-agg

#2865 Feature/#2840 l1 info root
  cmd/run.go
  l1infotree/tree.go
  l1infotree/tree_test.go
  pool/pool_test.go
  sequencer/closingsignalsmanager_test.go
  sequencer/dbmanager_test.go
  state/interfaces.go
  state/l1infotree.go
  state/pgstatestorage/l1infotree.go
  state/pgstatestorage/pgstatestorage_test.go
  state/state.go
  state/state_test.go
  synchronizer/actions/etrog/processor_l1_info_tree_update_test.go
  test/operations/manager.go
  test/vectors/l1infotree.go
  test/vectors/src/merkle-tree/l1-info-tree/proof-vectors.json
  tools/state/reprocess_cmd.go
Labels: cla-signed

#2854 etrog: Decode/coding etrog batches
  state/encoding_batch_v2.go
  state/encoding_batch_v2_test.go
Labels: state, cla-signed, zkevm-bridge-sync-rpc

#2872 update executor proto
  cmd/dumpstate.go
  cmd/run.go
  config/network.go
  config/network_test.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  pool/pool_test.go
  proto/src/proto/executor/v1/executor.proto
  state/batchV2.go
  state/genesis.go
  state/genesis_test.go
  state/runtime/executor/errors.go
  state/runtime/executor/executor.pb.go
  state/runtime/executor/executor_grpc.pb.go
  state/runtime/runtime.go
  state/state_test.go
  state/types.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/e2e/forced_batches_test.go
  test/e2e/forced_batches_vector_shared.go
  test/e2e/state_test.go
  test/operations/manager.go
  test/vectors/src/state-transition/etrog/balances.json
  test/vectors/statetransition_v2.go
  tools/datastreamer/main.go
Labels: cla-signed, zkevm-seq-agg
