Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2023-04, with the labels that each got.

#1968 review jRPC endpoints doc
  docs/json-rpc-endpoints.md
Labels: cla-signed

#1975 mainnet and rollup exit roots
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm.openrpc.json
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/mocks/mock_state.go
  jsonrpc/types/interfaces.go
  jsonrpc/types/types.go
Labels: cla-signed

#1979 fix: adding support for eip-1898 in JSON-RPC for pending methods.
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/handler.go
  jsonrpc/mocks/mock_state.go
  jsonrpc/types/codec.go
  jsonrpc/types/interfaces.go
  jsonrpc/types/types.go
  pool/interfaces.go
  pool/pool.go
  state/state.go
  test/e2e/state_test.go
Labels: rpc, cla-signed, blue-berry

#1986 add a combined log to jRPC requests
  jsonrpc/server.go
Labels: cla-signed

#1985 web3_clientVersion returns the node version
  jsonrpc/endpoints_web3.go
  jsonrpc/endpoints_web3_test.go
Labels: cla-signed

#1984 replace map by sync.Map for jRPC filters
  jsonrpc/storage.go
Labels: cla-signed

#1983 add an example to OPEN RPC doc for zkevm_getBatchByNumber endpoint
  jsonrpc/endpoints_zkevm.openrpc.json
Labels: cla-signed

#1989 event log
  cmd/run.go
  config/config.go
  config/environments/local/local.node.config.toml
  db/migrations/state/0005.sql
  db/scripts/init_event_db.sql
  event/config.go
  event/event.go
  event/eventlog.go
  event/eventlog_test.go
  event/interfaces.go
  event/nileventstorage/nileventstorage.go
  event/pgeventstorage/pgeventstorage.go
  jsonrpc/endpoints_eth.go
  pool/interfaces.go
  pool/pool.go
  pool/pool_test.go
  sequencer/closingsignalsmanager_test.go
  sequencer/dbmanager.go
  sequencer/dbmanager_test.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  state/converters.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  state/state.go
  state/state_test.go
  state/types.go
  test/Makefile
  test/benchmarks/sequencer/common/setup/setup.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/dbutils/dbutils.go
  test/docker-compose.yml
  test/e2e/broadcast_test.go
  test/operations/manager.go
Labels: cla-signed

#1994 replace the state debug tx to execute just the tx that needs the trace
  docker-compose.yml
  state/state.go
  test/docker-compose.yml
Labels: cla-signed

#1988 remove broadcast service
  Makefile
  README.md
  ci/e2e-group2/broadcast_test.go
  cmd/main.go
  cmd/run.go
  config/config.go
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/public.node.config.toml
  config/environments/public/public.node.config.toml
  docs/components/rpc.md
  docs/json-rpc-endpoints.md
  docs/modes.md
  docs/networks.md
  jsonrpc/config.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm.openrpc.json
  proto/src/proto/broadcast/v1/broadcast.proto
  sequencer/broadcast/client.go
  sequencer/broadcast/config.go
  sequencer/broadcast/interfaces.go
  sequencer/broadcast/mocks/mock_state.go
  sequencer/broadcast/pb/broadcast.pb.go
  sequencer/broadcast/pb/broadcast_grpc.pb.go
  sequencer/broadcast/server.go
  sequencer/broadcast/server_test.go
  test/Makefile
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/docker-compose.yml
  test/e2e/broadcast_test.go
  test/e2e/permissionlessrpc_test.go
Labels: cla-signed

#1995 Make stateTree and executor optional in the state.
  cmd/run.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  state/batch.go
  state/errors.go
  state/forkid.go
  state/genesis.go
  state/helper.go
  state/l2block.go
  state/metrics/metrics.go
  state/state.go
  state/state_test.go
  state/transaction.go
  state/types.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#2003 move state SQL queries
  state/pgstatestorage.go
Labels: cla-signed

#2002 Refactor sequencer state interfaces
  sequencer/dbmanager.go
  sequencer/interfaces.go
Labels: cla-signed

#2018 Add more details on the compatibility of eth_call
  docs/json-rpc-endpoints.md
Labels: cla-signed

#2007 Improve timestamp resolution
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  sequencer/closingsignalsmanager.go
  sequencer/config.go
  sequencer/dbmanager.go
  sequencer/dbmanager_test.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/sequencer.go
  state/batch.go
  state/transaction.go
  state/types.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#2011 improve: fixing worker todos.
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  sequencer/addrqueue.go
  sequencer/addrqueue_test.go
  sequencer/config.go
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/mock_worker.go
  sequencer/sequencer.go
  sequencer/txtracker.go
  sequencer/txtracker_test.go
  sequencer/worker.go
  sequencer/worker_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: sequencer, improvement, cla-signed, blue-berry

#2012 improve: fixing dbmanager todos.
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  sequencer/closingsignalsmanager.go
  sequencer/config.go
  sequencer/dbmanager.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: sequencer, improvement, cla-signed, blue-berry

#2010 add callTracer
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test-from-prover.yml
  .github/workflows/test-full-non-e2e.yml
  .github/workflows/updatedeps.yml
  .golangci.yml
  Dockerfile
  Makefile
  README.md
  docker-compose.yml
  docs/ci/groups.md
  etherman/etherman.go
  go.mod
  go.sum
  jsonrpc/endpoints_debug.go
  state/converters.go
  state/fakedb.go
  state/runtime/fakevm/analysis.go
  state/runtime/fakevm/common.go
  state/runtime/fakevm/contract.go
  state/runtime/fakevm/contracts.go
  state/runtime/fakevm/eips.go
  state/runtime/fakevm/errors.go
  state/runtime/fakevm/fakedb.go
  state/runtime/fakevm/fakevm.go
  state/runtime/fakevm/gas.go
  state/runtime/fakevm/gas_table.go
  state/runtime/fakevm/instructions.go
  state/runtime/fakevm/interpreter.go
  state/runtime/fakevm/jump_table.go
  state/runtime/fakevm/logger.go
  state/runtime/fakevm/memory.go
  state/runtime/fakevm/memory_table.go
  state/runtime/fakevm/opcodes.go
  state/runtime/fakevm/operations_acl.go
  state/runtime/fakevm/stack.go
  state/runtime/fakevm/stack_table.go
  state/runtime/instrumentation/executortrace.go
  state/runtime/instrumentation/js/goja.go
  state/runtime/instrumentation/tracers/native/4byte.go
  state/runtime/instrumentation/tracers/native/call.go
  state/runtime/instrumentation/tracers/native/call_flat.go
  state/runtime/instrumentation/tracers/native/gen_account_json.go
  state/runtime/instrumentation/tracers/native/gen_callframe_json.go
  state/runtime/instrumentation/tracers/native/gen_flatcallaction_json.go
  state/runtime/instrumentation/tracers/native/gen_flatcallresult_json.go
  state/runtime/instrumentation/tracers/native/mux.go
  state/runtime/instrumentation/tracers/native/noop.go
  state/runtime/instrumentation/tracers/native/prestate.go
  state/runtime/instrumentation/tracers/tracers.go
  state/state.go
  state/types.go
  test/config/debug.node.config.toml
  test/contracts/auto/Creates.sol
  test/contracts/bin/Creates/Creates.go
  test/docker-compose.yml
  test/e2e/debug_test.go
  test/e2e/sc_test.go
  tools/zkevmprovermock/Dockerfile
Labels: cla-signed

#2027 Improve claim checks
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/pool_test.go
Labels: cla-signed

#2028 fix wrong state root when prevlastbatch & lastbatch are empty + restart
  jsonrpc/endpoints_eth_test.go
  sequencer/dbmanager.go
Labels: cla-signed

#2022 check trusted state before L1 data
  synchronizer/synchronizer.go
Labels: cla-signed

#2006 improve: storing 'batch_resources' and 'closing_reason' in 'state.batch' on closing a batch.
  db/migrations/state/0006.sql
  sequencer/addrqueue.go
  sequencer/batchresources.go
  sequencer/dbmanager.go
  sequencer/errors.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_worker.go
  sequencer/sequencer.go
  sequencer/txtracker.go
  sequencer/txtracker_test.go
  sequencer/worker.go
  sequencer/worker_test.go
  state/batch.go
  state/errors.go
  state/helper.go
  state/pgstatestorage.go
  state/state_test.go
  state/transaction.go
  state/types.go
Labels: sequencer, state, improvement, cla-signed

#2040 Fix db prover permissions to allow create PL/SQL functions
  db/scripts/init_prover_db.sql
Labels: cla-signed

#2036 improve: adding missing usages of TxStatus metric.
  sequencer/finalizer.go
  test/benchmarks/sequencer/common/transactions/transactions.go
Labels: sequencer, cla-signed, metrics

#2031 Improve GHA
  .github/workflows/ok-to-test.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test-from-prover.yml
  .github/workflows/test-full-non-e2e.yml
  docs/ci/actions.md
  test/Makefile
  test/operations/wait.go
  tools/zkevmprovermock/Dockerfile
  tools/zkevmprovermock/cmd/client.go
  tools/zkevmprovermock/cmd/main.go
  tools/zkevmprovermock/cmd/server.go
  tools/zkevmprovermock/server/executor.go
  tools/zkevmprovermock/server/statedb.go
  tools/zkevmprovermock/testvector/main.go
  tools/zkevmprovermock/testvector/testvector_test.go
Labels: cla-signed

#1999 Feature/split network config
  cmd/approve.go
  cmd/dumpstate.go
  cmd/main.go
  cmd/run.go
  config/config.go
  config/config_test.go
  config/default.go
  config/environments/local/local.genesis.config.json
  config/environments/local/local.node.config.toml
  config/environments/mainnet/example.env
  config/environments/mainnet/public.node.config.toml
  config/environments/public/example.env
  config/environments/public/public.node.config.toml
  config/mainnetgenesis.go
  config/network.go
  config/network_test.go
  config/testnetgenesis.go
  docker-compose.yml
  etherman/config.go
  etherman/etherman.go
  etherman/etherman_test.go
  etherman/simulated.go
  pool/pool_test.go
  state/genesis.go
  state/genesis_test.go
  state/state_test.go
  synchronizer/config.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/config/debug.node.config.toml
  test/config/test.genesis.config.json
  test/config/test.node.config.toml
  test/docker-compose.yml
  test/operations/manager.go
  test/scripts/batchsender/main.go
Labels: cla-signed

#2054 Merge noClaimTxs into release v0.0.7
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/public.node.config.toml
  config/environments/public/public.node.config.toml
  jsonrpc/mocks/mock_pool.go
  jsonrpc/types/interfaces.go
  pool/config.go
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/pool_test.go
  pool/transaction.go
  pool/transaction_test.go
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/mock_pool.go
  sequencer/mock_worker.go
  sequencer/txtracker.go
  sequencer/worker.go
  test/benchmarks/sequencer/common/setup/setup.go
  test/e2e/pool_test.go
Labels: cla-signed

#2057 fix prover image
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed

#2048 Remove claim txs
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/public.node.config.toml
  config/environments/public/public.node.config.toml
  jsonrpc/mocks/mock_pool.go
  jsonrpc/types/interfaces.go
  pool/config.go
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool.go
  pool/pool_test.go
  pool/transaction.go
  pool/transaction_test.go
  sequencer/dbmanager.go
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/mock_pool.go
  sequencer/mock_worker.go
  sequencer/txtracker.go
  sequencer/worker.go
  test/benchmarks/sequencer/common/setup/setup.go
  test/e2e/pool_test.go
Labels: cla-signed
