Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2023-07, with the labels that each got.

#2250 Hotfix v0.1.4 to main
  config/default.go
  jsonrpc/config.go
  jsonrpc/endpoints_debug.go
  jsonrpc/endpoints_eth.go
  jsonrpc/server.go
  pool/pool.go
Labels: cla-signed

#2247 Effective GasPrice refactor+fixes
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  pool/config.go
  pool/errors.go
  pool/pool.go
  pool/pool_test.go
  sequencer/config.go
  sequencer/dbmanager.go
  sequencer/effective_gas_price.go
  sequencer/effective_gas_price_test.go
  sequencer/errors.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_pool.go
  sequencer/txtracker.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#2258 Fix/#2257 effective gas price receipt
  jsonrpc/types/types.go
Labels: cla-signed

#2260 bugfix: fixing l2blocks timestamp for the fist batch
  sequencer/finalizer.go
  sequencer/finalizer_test.go
Labels: cla-signed

#2269 Skip migration check for aggregator
  cmd/run.go
Labels: cla-signed

#2264 Fix/#2263 gas used
  pool/pool.go
  sequencer/effective_gas_price.go
  sequencer/finalizer.go
Labels: cla-signed

#2270 Fix pending tx when duplicate nonce
  pool/pgpoolstorage/pgpoolstorage.go
  sequencer/addrqueue.go
  sequencer/addrqueue_test.go
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/mock_worker.go
  sequencer/worker.go
  sequencer/worker_test.go
Labels: bug, sequencer, cla-signed

#2273 Only return a tx from the pool if tx is in pending status
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
Labels: cla-signed

#2275 improve: adding check to skip appending effectivePercentage if current forkId is under 5.
  sequencer/finalizer.go
  sequencer/finalizer_test.go
Labels: sequencer, improvement, cla-signed

#2278 Fix effectiveGasprice unsigned txs with forkId lower than 5
  state/helper.go
  state/transaction.go
Labels: cla-signed

#2282 feat: adding functionality to stop sequencer on specific batch num from config param.
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  sequencer/config.go
  sequencer/finalizer.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: sequencer, improvement, cla-signed, config

#2289 Fix checkIfSynced
  synchronizer/synchronizer.go
Labels: cla-signed

#2286 patch: adding print for X-Real-IP in JSON-RPC
  jsonrpc/endpoints_eth.go
Labels: rpc, test, cla-signed

#2287 flushID synchronizer
  state/batch.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#2299 Executor error refactor
  pool/pool.go
  sequencer/finalizer.go
Labels: cla-signed

#2297 handle invalid rlp ROM error
  proto/src/proto/executor/v1/executor.proto
  state/runtime/executor/errors.go
  state/runtime/executor/pb/executor.pb.go
  state/runtime/runtime.go
Labels: cla-signed

#2294 add maxL2GasPrice
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  gasprice/config.go
  gasprice/follower.go
  gasprice/follower_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed, config

#2302 Error refactor
  Makefile
  cmd/run.go
  event/eventlog.go
  proto/src/proto/executor/v1/executor.proto
  sequencer/closingsignalsmanager_test.go
  sequencer/dbmanager_test.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  state/batch.go
  state/converters.go
  state/runtime/executor/client.go
  state/runtime/executor/errors.go
  state/runtime/executor/executor.pb.go
  state/runtime/executor/executor_grpc.pb.go
  state/state.go
  state/state_test.go
  state/transaction.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer_test.go
  tools/executor/main.go
Labels: cla-signed

#2309 log reprocess need
  sequencer/finalizer.go
Labels: cla-signed

#2306 Feature/2300 synchronizer detect if executor restart
  cmd/run.go
  event/event.go
  go.mod
  go.sum
  state/batch.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#2311 Update prover images
  config/environments/mainnet/public.prover.config.json
  config/environments/testnet/testnet.prover.config.json
  docker-compose.yml
  test/config/test.permissionless.prover.config.json
  test/config/test.prover.config.json
  test/docker-compose.yml
Labels: cla-signed

#2315 add doc, and fix dockers to be able to use snap/restore feature
  Dockerfile
  docs/snap_restore.md
  test/docker-compose.yml
Labels: cla-signed

#2334 Merge/v0.2.1 into develop
  pool/pool.go
Labels: cla-signed

#2204 fix estimate gas nonce computation to deal with sequencer concurrency
  state/transaction.go
Labels: cla-signed
