Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2023-08, with the labels that each got.

#2349 rename config files
  .github/workflows/release.yml
  Dockerfile
  config/config.go
  config/environments/mainnet/node.config.toml
  config/environments/mainnet/prover.config.json
  config/environments/testnet/node.config.toml
  config/environments/testnet/prover.config.json
  config/gen_json_schema_test.go
  docker-compose.yml
  docs/configuration.md
  docs/modes.md
  docs/production-setup.md
Labels: cla-signed

#2303 Update README diagram
  README.md
  docs/architecture.drawio.png
  test/docker-compose.yml
  tools/zkevmprovermock/Dockerfile
Labels: cla-signed

#2348 fix closing batch + logs
  event/event.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#2353 Merge Release/v0.2.2 into develop
  .github/workflows/release.yml
  Dockerfile
  README.md
  config/config.go
  config/environments/mainnet/node.config.toml
  config/environments/mainnet/prover.config.json
  config/environments/testnet/node.config.toml
  config/environments/testnet/prover.config.json
  config/gen_json_schema_test.go
  docker-compose.yml
  docs/configuration.md
  docs/modes.md
  docs/production-setup.md
  event/event.go
  go.mod
  go.sum
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/sequencer.go
  sequencer/worker.go
  sequencer/worker_test.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/config/test.permissionless.prover.config.json
  test/config/test.prover.config.json
Labels: cla-signed

#2358 Store batchL2Data when the batch is opened
  state/batch.go
  state/pgstatestorage.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#2360 add GasPriceMarginFactor and MaxGasPrice to eth-tx-manager
  config/config_test.go
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  ethtxmanager/config.go
  ethtxmanager/ethtxmanager.go
  ethtxmanager/ethtxmanager_test.go
Labels: cla-signed

#2373 improve: adding logs
  sequencer/finalizer.go
  sequencer/worker.go
Labels: sequencer, improvement, cla-signed

#2375 bugfix: fixing finalizer's `lastPendingFlushId` handling."
  sequencer/finalizer.go
  sequencer/finalizer_test.go
Labels: bug, sequencer, improvement, cla-signed

#2376 Merge v0.2.4 (includes v0.2.3) into Develop
  Makefile
  config/config_test.go
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  ethtxmanager/config.go
  ethtxmanager/ethtxmanager.go
  ethtxmanager/ethtxmanager_test.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/worker.go
  state/batch.go
  state/pgstatestorage.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#2367 Adaptation to new HashDB interface
  Makefile
  aggregator/aggregator.go
  aggregator/aggregator_test.go
  aggregator/interfaces.go
  aggregator/mocks/mock_prover.go
  aggregator/prover/aggregator.pb.go
  aggregator/prover/aggregator_grpc.pb.go
  aggregator/prover/prover.go
  config/environments/mainnet/prover.config.json
  config/environments/testnet/prover.config.json
  docker-compose.yml
  etherman/types/finalproofinputs.go
  merkletree/client.go
  merkletree/hashdb/hashdb.pb.go
  merkletree/hashdb/hashdb_grpc.pb.go
  merkletree/tree.go
  proto/src/proto/aggregator/v1/aggregator.proto
  proto/src/proto/hashdb/v1/hashdb.proto
  sequencer/closingsignalsmanager_test.go
  sequencer/dbmanager_test.go
  state/genesis.go
  state/state.go
  state/state_test.go
  synchronizer/mock_state.go
  test/config/test.permissionless.prover.config.json
  test/config/test.prover.config.json
  test/docker-compose.yml
  test/scripts/send_transfers/main.go
Labels: cla-signed, config

#2382 Refactor nonce calculation for addQueue
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/sequencer.go
  sequencer/worker.go
  sequencer/worker_test.go
Labels: cla-signed

#2383 fix script
  test/scripts/send_transfers/main.go
Labels: cla-signed

#2387 check to avoid data inconsistencies
  synchronizer/synchronizer.go
Labels: cla-signed

#2285 avoid double unlock in sequencer AddTxTracker
  sequencer/worker.go
Labels: cla-signed

#2267 Fix criadoperez
  CONTRIBUTING.md
  docs/modes.md
  sequencer/addrqueue.go
  sequencer/txtracker.go
  sequencer/worker_test.go
  state/runtime/instrumentation/js/internal/tracers/4byte_tracer_legacy.js
  state/runtime/instrumentation/js/internal/tracers/call_tracer_legacy.js
Labels: cla-signed

#2391 Refactor: avoid delete addrQueue if it has pending txs to store
  sequencer/addrqueue.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_worker.go
  sequencer/worker.go
Labels: cla-signed

#2385 fix http request instance null for websocket requests
  jsonrpc/handler.go
  jsonrpc/server.go
Labels: cla-signed

#2392 Sort txs in worker by gasPrice (remove efficiency sort)
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  sequencer/addrqueue.go
  sequencer/config.go
  sequencer/efficiencylist.go
  sequencer/efficiencylist_test.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_worker.go
  sequencer/sequencer.go
  sequencer/txsorted_list.go
  sequencer/txsorted_list_test.go
  sequencer/txtracker.go
  sequencer/txtracker_test.go
  sequencer/worker.go
  sequencer/worker_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed, config

#2393 use useMainExecGenerated
  config/environments/mainnet/prover.config.json
  config/environments/testnet/prover.config.json
  test/config/test.permissionless.prover.config.json
  test/config/test.prover.config.json
  tools/executor/prover.config.json
Labels: cla-signed, config

#2394 Fix "nil ponter reference" when storing a forced batch tx
  sequencer/finalizer.go
Labels: cla-signed

#2406 Check flushID != 0 in synchronizer
  sequencer/finalizer.go
  synchronizer/synchronizer.go
Labels: cla-signed

#2413 Merge/v0.2.5
  cmd/run.go
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/prover.config.json
  config/environments/testnet/prover.config.json
  config/gen_json_schema.go
  config/gen_json_schema_test.go
  docker-compose.yml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  etherman/etherman.go
  etherman/etherman_test.go
  sequencer/addrqueue.go
  sequencer/config.go
  sequencer/efficiencylist.go
  sequencer/efficiencylist_test.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_etherman.go
  sequencer/mock_worker.go
  sequencer/sequencer.go
  sequencer/txsorted_list.go
  sequencer/txsorted_list_test.go
  sequencer/txtracker.go
  sequencer/txtracker_test.go
  sequencer/worker.go
  sequencer/worker_test.go
  sequencesender/config.go
  sequencesender/interfaces.go
  sequencesender/sequencesender.go
  state/batch.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/config/test.permissionless.prover.config.json
  test/config/test.prover.config.json
  test/docker-compose.yml
  test/scripts/batchsender/main.go
  tools/executor/prover.config.json
Labels: cla-signed

#2416 Show tx.GasPrice in the worker logs (instead of tx.Cost)
  sequencer/finalizer.go
  sequencer/worker.go
Labels: cla-signed

#2415 Check flushID != 0 in Sequencer
  sequencer/finalizer.go
Labels: cla-signed

#2418 Update config params used in Prover v2.1.0
  config/environments/mainnet/prover.config.json
  config/environments/testnet/prover.config.json
  test/config/test.permissionless.prover.config.json
  test/config/test.prover.config.json
Labels: cla-signed, config

#2245 fix safe and finalized l2 block to consider l1 safe and finalized blocks respectively
  cmd/run.go
  etherman/etherman.go
  jsonrpc/endpoints_debug.go
  jsonrpc/endpoints_eth.go
  jsonrpc/mocks/mock_etherman.go
  jsonrpc/mocks/mock_state.go
  jsonrpc/server_test.go
  jsonrpc/types/codec.go
  jsonrpc/types/codec_test.go
  jsonrpc/types/interfaces.go
  state/pgstatestorage.go
  test/Makefile
Labels: cla-signed

#2412 cherry-pick #2385 and #2396 from develop into v0.2.6
  jsonrpc/endpoints_eth.go
  jsonrpc/handler.go
  jsonrpc/server.go
  state/pgstatestorage.go
  test/e2e/sc_test.go
Labels: cla-signed

#2411 new block endpoints and improvements to batch endpoint
  docs/json-rpc-endpoints.md
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm.openrpc.json
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/mocks/mock_state.go
  jsonrpc/types/interfaces.go
  jsonrpc/types/types.go
  state/l2block.go
  state/pgstatestorage.go
Labels: cla-signed

#2327 improve pre-EIP155 check
  pool/pool.go
  pool/pool_test.go
  state/helper.go
  test/e2e/preEIP155_test.go
Labels: cla-signed

#2298 Add IP and ZKCounter Validation, Refactor Batch Configs
  cmd/dumpstate.go
  cmd/restore.go
  cmd/run.go
  cmd/snapshot.go
  config/config.go
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/example.env
  config/environments/mainnet/node.config.toml
  config/environments/testnet/example.env
  config/environments/testnet/node.config.toml
  docker-compose.yml
  docs/components/aggregator.md
  docs/components/rpc.md
  docs/components/sequencer.md
  docs/components/synchronizer.md
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  docs/configuration.md
  pool/config.go
  pool/config_test.go
  pool/errors.go
  pool/pool.go
  pool/pool_test.go
  pool/validation.go
  pool/validation_test.go
  sequencer/closingsignalsmanager_test.go
  sequencer/config.go
  sequencer/dbmanager.go
  sequencer/dbmanager_test.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/sequencer.go
  sequencer/worker.go
  sequencer/worker_test.go
  state/config.go
  test/benchmarks/sequencer/common/setup/setup.go
  test/benchmarks/sequencer/e2e/eth-transfers/tx_sender.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/docker-compose.yml
  test/e2e/uniswap_test.go
Labels: bug, sequencer, rpc, improvement, cla-signed, pool, config

#2419 Makefile improvements
  Makefile
Labels: cla-signed

#2398 Add forced batches tx to addrQueue
  sequencer/addrqueue.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/mock_worker.go
  sequencer/worker.go
Labels: cla-signed

#2432 Update prover images
  docker-compose.yml
  docs/production-setup.md
  test/docker-compose.yml
Labels: cla-signed

#2433 update install doc
  docs/production-setup.md
Labels: cla-signed

#2304 Add WebSocket Read Limit
  config/config_test.go
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  jsonrpc/config.go
  jsonrpc/server.go
  test/e2e/jsonrpc2_test.go
Labels: rpc, improvement, cla-signed, config

#2431 Introduce Config Parameters to Control RPC Batch Requests
  config/config_test.go
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  jsonrpc/client/client.go
  jsonrpc/config.go
  jsonrpc/metrics/metrics.go
  jsonrpc/server.go
  jsonrpc/server_test.go
  jsonrpc/types/errors.go
Labels: rpc, improvement, cla-signed, config

#2452 bugifx: adding missing tx.BreakEvenGasPrice nil check
  sequencer/finalizer.go
Labels: bug, sequencer, cla-signed

#2428 #2420 sync halt sanity check
  event/event.go
  synchronizer/synchronizer.go
Labels: cla-signed

#2447 cherry-pick #2245 and #2424 from develop into v0.2.6
  cmd/run.go
  etherman/etherman.go
  jsonrpc/endpoints_debug.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/mocks/mock_etherman.go
  jsonrpc/mocks/mock_state.go
  jsonrpc/server_test.go
  jsonrpc/types/codec.go
  jsonrpc/types/codec_test.go
  jsonrpc/types/interfaces.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  test/Makefile
Labels: cla-signed

#2438 New executor errors refactor
  docker-compose.yml
  merkletree/hashdb/hashdb.pb.go
  merkletree/tree.go
  proto/src/proto/executor/v1/executor.proto
  proto/src/proto/hashdb/v1/hashdb.proto
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  state/runtime/executor/errors.go
  state/runtime/executor/executor.pb.go
  state/runtime/runtime.go
  state/transaction.go
  test/docker-compose.yml
Labels: cla-signed

#2425 Reprocess full batch in parallel (sanity check)
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  sequencer/config.go
  sequencer/errors.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/sequencer.go
Labels: cla-signed

#2457 Speed up deleting batches from stateDB creating an index for state.receipt.block_num
  db/migrations/state/0008.sql
  db/migrations/state/0008_test.go
Labels: cla-signed

#2450 Feature/#2429 fork id improvement
  ci/e2e-group9/forced_batches_vector_group1_test.go
  cmd/run.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/node.config.toml
  config/environments/testnet/node.config.toml
  db/migrations/state/0008.sql
  db/migrations/state/0008_test.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  etherman/config.go
  etherman/etherman.go
  etherman/etherman_test.go
  etherman/simulated.go
  state/forkid.go
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  synchronizer/interfaces.go
  synchronizer/mock_etherman.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/operations/manager.go
Labels: cla-signed

#2458 fix check storedFlushID
  sequencer/finalizer.go
Labels: cla-signed

#2459 remove stored flush id 0
  sequencer/finalizer.go
Labels: cla-signed

#2464 Update prover version 2.1.2 in docker-compose
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed

#2470 Remove actual user names from PR template
  .github/pull_request_template.md
Labels: cla-signed

#2471 fix postgres version to 15 in docker compose files
  docker-compose.yml
  docs/components/databases.md
  test/docker-compose.yml
  tools/executor/docker-compose.yml
Labels: cla-signed

#2404 Feature/#2403 snap
  cmd/readme.md
  cmd/restore.go
  cmd/snapshot.go
  db/scripts/single_db_server.sql
  docker-compose.yml
  docs/components/databases.md
  test/docker-compose.yml
  tools/executor/docker-compose.yml
Labels: cla-signed

#2473 update prover images
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed

#2476 remove need of decoded txs to process a batch response
  state/batch.go
  state/converters.go
  state/state_test.go
  state/transaction.go
Labels: cla-signed

#2478 Fix state configuration
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/node.config.toml
  config/environments/testnet/node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  state/config.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed

#2481 decode transaction only if rlp is available
  state/converters.go
Labels: cla-signed

#2422 Sequencer Benchmark Scripts Improvement and Documentation
  .gitignore
  go.mod
  go.sum
  test/benchmarks/sequencer/common/metrics/metrics.go
  test/benchmarks/sequencer/common/setup/setup.go
  test/benchmarks/sequencer/common/transactions/transactions.go
  test/benchmarks/sequencer/e2e/erc20-transfers/deployment.go
  test/benchmarks/sequencer/e2e/erc20-transfers/erc20_test.go
  test/benchmarks/sequencer/e2e/erc20-transfers/pool_processing_erc20_test.go
  test/benchmarks/sequencer/e2e/erc20-transfers/tx_sender.go
  test/benchmarks/sequencer/e2e/eth-transfers/eth_test.go
  test/benchmarks/sequencer/e2e/eth-transfers/tx_sender.go
  test/benchmarks/sequencer/e2e/uniswap-transfers/tx_sender.go
  test/benchmarks/sequencer/e2e/uniswap-transfers/uniswap_test.go
  test/benchmarks/sequencer/scripts/.env.example
  test/benchmarks/sequencer/scripts/README.md
  test/benchmarks/sequencer/scripts/common/environment/constants.go
  test/benchmarks/sequencer/scripts/common/results/print.go
  test/benchmarks/sequencer/scripts/environment/constants.go
  test/benchmarks/sequencer/scripts/environment/init.go
  test/benchmarks/sequencer/scripts/erc20-transfers/main.go
  test/benchmarks/sequencer/scripts/exec_erc20_transfers.go
  test/benchmarks/sequencer/scripts/exec_eth_transfers.go
  test/benchmarks/sequencer/scripts/exec_uniswap_transfers.go
  test/benchmarks/sequencer/scripts/main.go
Labels: documentation, sequencer, improvement, benchmark, test, cla-signed

#2482 fix fb convert handling
  state/converters.go
Labels: cla-signed

#2448 add http request content limit
  jsonrpc/client/client.go
  jsonrpc/server.go
  jsonrpc/server_test.go
Labels: cla-signed

#2488 handle invalid rlp error
  sequencer/finalizer.go
  state/converters.go
Labels: cla-signed

#2494 fix INVALID_RLP
  sequencer/finalizer.go
Labels: cla-signed
