Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2023-12, with the labels that each got.

#2856 review Estimate Gas validations and Formulas
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  state/errors.go
  state/state.go
  state/transaction.go
  test/benchmarks/sequencer/common/transactions/transactions.go
  test/e2e/jsonrpc2_test.go
  test/e2e/shared.go
Labels: cla-signed

#2774 improve OOC and OOG errors
  jsonrpc/endpoints_eth.go
  pool/pool.go
  state/runtime/runtime.go
  test/contracts/auto/triggerErrors.sol
  test/contracts/bin/triggerErrors/triggerErrors.go
  test/e2e/jsonrpc1_test.go
  test/e2e/jsonrpc2_test.go
Labels: cla-signed

#2819 cherry pick the latest WS improvements into develop
  jsonrpc/endpoints_debug.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/handler.go
  jsonrpc/interfaces.go
  jsonrpc/mock_storage.go
  jsonrpc/query.go
  jsonrpc/server.go
  jsonrpc/storage.go
  jsonrpc/wsconn.go
  state/infinite.go
  state/interfaces.go
  state/l2block.go
  state/pgstatestorage/pgstatestorage.go
  state/queue.go
  state/state.go
Labels: cla-signed

#2875 Add StoreL2Block (ETROG) function to the state
  state/transaction.go
Labels: cla-signed, zkevm-seq-agg

#2878 Sequencer Etrog refactor
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  sequencer/addrqueue.go
  sequencer/batch.go
  sequencer/closingsignalsmanager.go
  sequencer/config.go
  sequencer/dbmanager.go
  sequencer/errors.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/l2block.go
  sequencer/mock_db_manager.go
  sequencer/mock_etherman.go
  sequencer/mock_state.go
  sequencer/mock_worker.go
  sequencer/sequencer.go
  sequencer/txtracker.go
  sequencer/worker.go
  sequencer/worker_test.go
  sequencesender/sequencesender.go
  state/batchV2.go
  state/helper.go
  state/interfaces.go
  state/pgstatestorage/batch.go
  state/pgstatestorage/l1infotree.go
  state/pgstatestorage/l2block.go
  state/transaction.go
  state/types.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed, zkevm-seq-agg

#2880 Fix generateReceipt call. Use StoreL2Block from the state
  sequencer/batch.go
  sequencer/closingsignalsmanager.go
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/l2block.go
  sequencer/mock_state.go
  state/batchV2.go
  state/helper.go
  state/transaction.go
Labels: cla-signed, zkevm-seq-agg

#2882 Refactor init/get WIP batch in finalizer. Add SHA256 counter. Fixes
  config/default.go
  config/environments/local/local.node.config.toml
  config/environments/mainnet/node.config.toml
  config/environments/testnet/node.config.toml
  db/migrations/state/0013.sql
  db/migrations/state/0013_test.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  pool/config_test.go
  pool/pgpoolstorage/pgpoolstorage.go
  pool/pool_test.go
  sequencer/batch.go
  sequencer/closingsignalsmanager.go
  sequencer/closingsignalsmanager_test.go
  sequencer/datastreamer.go
  sequencer/dbmanager.go
  sequencer/dbmanager_test.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/l2block.go
  sequencer/mock_db_manager.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  sequencer/worker_test.go
  state/batch.go
  state/config.go
  state/interfaces.go
  state/pgstatestorage/batch.go
  state/transaction.go
  state/types.go
  test/Makefile
  test/benchmarks/sequencer/common/setup/setup.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed, zkevm-seq-agg

#2883 jRPC - Review Logs
  event/eventlog.go
  jsonrpc/endpoints_eth.go
  jsonrpc/handler.go
  jsonrpc/metrics/metrics.go
  jsonrpc/server.go
  pool/pool.go
  state/transaction.go
Labels: cla-signed

#2887 Fix final StateRoot for batch when it is closed
  sequencer/addrqueue.go
  sequencer/batch.go
  sequencer/datastreamer.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/l2block.go
  sequencer/sequencer.go
  state/batchV2.go
  state/pgstatestorage/pgstatestorage_test.go
Labels: cla-signed, zkevm-seq-agg

#2893 add im state root to data stream
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/mock_db_manager.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  state/datastream.go
  state/test/datastream_test.go
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed, zkevm-seq-agg

#2896 small fixes
  sequencer/batch.go
  sequencer/finalizer.go
  sequencer/l2block.go
  state/batchV2.go
  state/convertersV2.go
Labels: cla-signed

#2895 Add im state root to data stream (#2893)
  sequencer/batch.go
  sequencer/closingsignalsmanager.go
  sequencer/dbmanager.go
  sequencer/finalizer_test.go
  sequencer/interfaces.go
  sequencer/l2block.go
  sequencer/mock_db_manager.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  state/batchV2.go
  state/datastream.go
  state/helper.go
  state/test/datastream_test.go
  state/transaction.go
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed, cherry-pick

#2898 Feature/fixes2
  state/batchV2.go
Labels: cla-signed

#2897 cherry pick PR #2856 into develop
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  state/errors.go
  state/state.go
  state/transaction.go
  test/benchmarks/sequencer/common/transactions/transactions.go
  test/e2e/jsonrpc2_test.go
  test/e2e/shared.go
Labels: cla-signed

#2899 cherry pick PR #2883 into develop
  event/eventlog.go
  jsonrpc/endpoints_eth.go
  jsonrpc/handler.go
  jsonrpc/metrics/metrics.go
  jsonrpc/server.go
  pool/pool.go
  state/transaction.go
Labels: cla-signed

#2900 fix test
  state/state_test.go
Labels: cla-signed

#2905 fix ProcessBatchV2
  docker-compose.yml
  state/batchV2.go
  state/stateV2_test.go
  test/docker-compose.yml
  test/vectors/src/state-transition/etrog/balances.json
  test/vectors/statetransition_etrog.go
  test/vectors/statetransition_v2.go
  test/vectors/vectors_etrog.go
Labels: cla-signed

#2908 update prover version v4.0.0-RC8
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed

#2911 l1InfoRoot + fixes unsigned tx
  etherman/etherman.go
  etherman/types.go
  state/transaction.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#2912 state transtiion v2 test
  docker-compose.yml
  state/batchV2.go
  state/stateV2_test.go
  state/state_test.go
  test/docker-compose.yml
  test/vectors/src/state-transition/etrog/balances.json
  test/vectors/vectors_etrog.go
Labels: cla-signed, zkevm-seq-agg

#2915 fix forkID in ProcessRequest
  sequencer/finalizer.go
  sequencer/l2block.go
Labels: cla-signed

#2918 Feature/2914 etrog use l1inforoot from event
  state/batchV2.go
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/l2_sync/l2_sync_etrog/sync_trusted_state.go
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#2921 Fix update last L1InfoRoot
  sequencer/finalizer.go
Labels: cla-signed, zkevm-seq-agg

#2916 Update/get wip batch used resources from the state (batch table)
  sequencer/batch.go
  sequencer/finalizer.go
  sequencer/l2block.go
  state/batch.go
  state/pgstatestorage/batch.go
  state/types.go
Labels: cla-signed, zkevm-seq-agg

#2920 Refactor state tests
  db/migrations/state/0013.sql
  state/stateV2_test.go
  state/test/common.go
  state/test/dragonfruit/genesis_test.go
  state/test/dragonfruit/state_test.go
  state/test/etrog/state_test.go
  state/test/helper_test.go
Labels: cla-signed, zkevm-seq-agg

#2910 set ws logs to debug
  jsonrpc/server.go
Labels: cla-signed

#2922 review usigned tx execution and make estimate gas compatible with all forkIDs
  state/transaction.go
Labels: cla-signed

#2924 Fix tx size when calculating egp and checking remaining batch resources
  pool/effectivegasprice.go
  sequencer/finalizer.go
  state/batchV2.go
Labels: cla-signed, zkevm-seq-agg

#2923 etrog: support permissionless sync from scratch
  state/batchV2.go
  state/convertersV2.go
  synchronizer/l2_sync/l2_shared/processor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_shared/trusted_batches_retrieve.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
  synchronizer/synchronizer.go
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#2925 Fix/l1 info root
  config/environments/local/local.genesis.config.json
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/l2block.go
  sequencer/mock_state.go
  state/batchV2.go
  state/interfaces.go
  state/pgstatestorage/l1infotree.go
  state/test/etrog/state_test.go
  state/types.go
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/interfaces.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
Labels: cla-signed

#2927 add WIP to state.batch struct
  jsonrpc/endpoints_zkevm.go
  jsonrpc/types/types.go
  state/batch.go
  state/pgstatestorage/batch.go
  state/pgstatestorage/pgstatestorage_test.go
Labels: state, rpc, cla-signed, zkevm-bridge-sync-rpc

#2931 Fix EGP tx size (remove signature bytes)
  pool/effectivegasprice.go
  pool/effectivegasprice_test.go
Labels: cla-signed, zkevm-seq-agg

#2929 fix TODOs. fix reprocessFullBatch. fix egp tx size
  pool/effectivegasprice.go
  pool/effectivegasprice_test.go
  pool/pool.go
  sequencer/batch.go
  sequencer/closingsignalsmanager.go
  sequencer/datastreamer.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/l2block.go
  sequencer/sequencer.go
  sequencer/txtracker.go
Labels: cla-signed, zkevm-seq-agg

#2933 New state test vectors
  state/test/forkid_etrog/etrog_test.go
  test/vectors/src/etrog/balances.json
  test/vectors/src/etrog/chain-ids.json
  test/vectors/src/etrog/general.json
  test/vectors/src/etrog/nonces.json
  test/vectors/src/etrog/seq-fees.json
Labels: cla-signed, zkevm-seq-agg

#2935 Revert "build(deps): bump github.com/spf13/viper from 1.17.0 to 1.18.1"
  go.mod
  go.sum
Labels: cla-signed

#2941 Update smc + sync init tx
  config/environments/local/local.genesis.config.json
  config/gen_json_schema_test.go
  config/network.go
  config/network_test.go
  docs/config-file/custom_network-config-doc.html
  docs/config-file/custom_network-config-doc.md
  docs/config-file/custom_network-config-schema.json
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  etherman/etherman.go
  etherman/smartcontracts/abi/mockpolygonrollupmanager.abi
  etherman/smartcontracts/abi/polygonrollupmanager.abi
  etherman/smartcontracts/bin/mockpolygonrollupmanager.bin
  etherman/smartcontracts/bin/polygonrollupmanager.bin
  etherman/smartcontracts/bin/polygonzkevmbridge.bin
  etherman/smartcontracts/mockpolygonrollupmanager/mockpolygonrollupmanager.go
  etherman/smartcontracts/polygonrollupmanager/polygonrollupmanager.go
  etherman/smartcontracts/polygonzkevmbridge/polygonzkevmbridge.go
  pool/pool_test.go
  sequencer/closingsignalsmanager_test.go
  state/genesis.go
  state/test/forkid_common/common.go
  state/test/forkid_dragonfruit/dragonfruit_test.go
  state/test/forkid_dragonfruit/genesis_test.go
  state/test/forkid_independent/independent_test.go
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/synchronizer.go
  test/config/test.genesis-v1tov2.config.json
  test/config/test.genesis.config.json
  test/e2e/forced_batches_vector_shared.go
  test/operations/manager.go
Labels: cla-signed

#2936 extend block endpoints to provide the new l2 block information
  jsonrpc/client/eth.go
  jsonrpc/client/zkevm.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/server.go
  jsonrpc/types/codec.go
  jsonrpc/types/errors.go
  jsonrpc/types/types.go
  state/l2block.go
  state/transaction.go
Labels: cla-signed

#2942 Handle new executor errors
  merkletree/hashdb/hashdb.pb.go
  merkletree/hashdb/hashdb_grpc.pb.go
  proto/src/proto/executor/v1/executor.proto
  proto/src/proto/hashdb/v1/hashdb.proto
  state/convertersV2.go
  state/runtime/executor/errors.go
  state/runtime/executor/executor.pb.go
  state/runtime/runtime.go
  state/types.go
Labels: state, cla-signed, zkevm-seq-agg

#2944 expose new V2 executor fields
  sequencer/batch.go
  sequencer/finalizer.go
  sequencer/l2block.go
  state/batchV2.go
  state/test/forkid_etrog/etrog_test.go
  state/types.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
Labels: cla-signed

#2943 Update aggregator for etrog
  aggregator/aggregator.go
  aggregator/interfaces.go
  aggregator/mocks/mock_state.go
  aggregator/prover/aggregator.pb.go
  aggregator/prover/aggregator_grpc.pb.go
  docker-compose.yml
  proto/src/proto/aggregator/v1/aggregator.proto
  state/interfaces.go
  state/pgstatestorage/l1infotree.go
  test/docker-compose.yml
Labels: aggregator, cla-signed, zkevm-seq-agg

#2950 fix genesis sequence
  docker-compose.yml
  merkletree/tree.go
  state/genesis.go
  state/types.go
  test/docker-compose.yml
Labels: cla-signed, zkevm-seq-agg

#2946 Refactor forced batches (ETROG). Fix/Review executor requests
  docker-compose.yml
  merkletree/tree.go
  sequencer/batch.go
  sequencer/datastreamer.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/forcedbatch.go
  sequencer/interfaces.go
  sequencer/l2block.go
  sequencer/mock_state.go
  state/genesis.go
  state/interfaces.go
  state/pgstatestorage/batch.go
  state/pgstatestorage/block.go
  state/state.go
  state/test/forkid_etrog/etrog_test.go
  state/test/forkid_independent/independent_test.go
  state/types.go
  test/docker-compose.yml
  test/vectors/vectors_etrog.go
  tools/datastreamer/main.go
Labels: cla-signed, zkevm-seq-agg

#2955 Fix/none2e tests
  config/config_test.go
  config/default.go
  config/network_test.go
Labels: cla-signed

#2956 Return last L1InfoRoot used in batchL2Data in function GetL1InfoTreeDataFromBatchL2Data
  sequencer/batch.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  state/batch.go
  state/interfaces.go
  state/pgstatestorage/batch.go
Labels: cla-signed, zkevm-seq-agg

#2957 reviews l2 block exit roots and exposes endpoint to get them by ger
  docs/json-rpc-endpoints.md
  jsonrpc/client/zkevm.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm.openrpc.json
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/types/types.go
  state/l2block.go
  state/transaction.go
Labels: cla-signed

#2958 Feature/#2948 v1tov2
  etherman/etherman.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  state/batchV2.go
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  test/Makefile
  test/config/test.genesis-v1tov2.config.json
  test/docker-compose.yml
Labels: cla-signed

#2949 etrog: synchornizer-permisionless: first version working of sync with trusted state
  state/batchV2.go
  state/convertersV2.go
  state/encoding_batch_v2.go
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/actions/incaberry/processor_l1_sequence_batches.go
  synchronizer/common/generic_cache.go
  synchronizer/common/generic_cache_test.go
  synchronizer/common/log_helper.go
  synchronizer/common/log_helper_test.go
  synchronizer/common/syncinterfaces/etherman.go
  synchronizer/common/syncinterfaces/evenlog.go
  synchronizer/common/syncinterfaces/mocks/etherman_get_latest_batch_number.go
  synchronizer/common/syncinterfaces/mocks/event_log_interface.go
  synchronizer/common/syncinterfaces/mocks/state_begin_transaction_interface.go
  synchronizer/common/syncinterfaces/mocks/state_get_batch_by_number_interface.go
  synchronizer/common/syncinterfaces/mocks/sync_trusted_state_executor.go
  synchronizer/common/syncinterfaces/mocks/synchronizer_flush_id_manager.go
  synchronizer/common/syncinterfaces/mocks/zkevm_client_trusted_batches_getter.go
  synchronizer/common/syncinterfaces/state.go
  synchronizer/common/syncinterfaces/sync.go
  synchronizer/common/syncinterfaces/sync_trusted_state_executor.go
  synchronizer/common/syncinterfaces/zkevm_rpc.go
  synchronizer/interfaces.go
  synchronizer/l1_parallel_sync/mock_l1_parallel_etherman_interface.go
  synchronizer/l1_parallel_sync/mock_l1_rollup_consumer_interface.go
  synchronizer/l1_parallel_sync/mock_l1_rollup_producer_interface.go
  synchronizer/l1_parallel_sync/mock_synchronizer_process_block_range_interface.go
  synchronizer/l1_parallel_sync/mock_worker.go
  synchronizer/l1_parallel_sync/mock_workers_interface.go
  synchronizer/l2_sync/l2_shared/mocks/batch_processor.go
  synchronizer/l2_sync/l2_shared/mocks/state_interface.go
  synchronizer/l2_sync/l2_shared/mocks/sync_trusted_batch_executor.go
  synchronizer/l2_sync/l2_shared/processor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_shared/trusted_batches_retrieve.go
  synchronizer/l2_sync/l2_shared/trusted_state.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync_test.go
  synchronizer/l2_sync/l2_sync_etrog/mocks/state_interface.go
  synchronizer/mock_etherman.go
  synchronizer/mock_ethtxmanager.go
  synchronizer/mock_pool.go
  synchronizer/mock_state.go
  synchronizer/mock_zkevmclient.go
  synchronizer/mocks/mock_dbtx.go
  synchronizer/synchronizer.go
  test/Makefile
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#2963 Fix UUID + prover rc16
  merkletree/tree.go
  test/docker-compose.yml
Labels: cla-signed

#2959 Remove accInputHash calculation on finalizer. Fix batch GER
  sequencer/batch.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/forcedbatch.go
  sequencer/l2block.go
  state/batch.go
  state/pgstatestorage/batch.go
Labels: cla-signed, zkevm-seq-agg

#2964 use prover 4.0.0-RC16 for permissionless
  test/docker-compose.yml
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#2965 fix finalizer l1InfoTreeData
  sequencer/finalizer.go
  sequencer/l2block.go
Labels: cla-signed

#2968 aggregate forced batches
  aggregator/aggregator.go
  aggregator/interfaces.go
  aggregator/mocks/mock_state.go
  state/interfaces.go
  state/pgstatestorage/batch.go
Labels: aggregator, cla-signed

#2972 new executor errors
  proto/src/proto/executor/v1/executor.proto
  state/runtime/executor/errors.go
  state/runtime/executor/executor.pb.go
  state/runtime/runtime.go
Labels: cla-signed, zkevm-seq-agg

#2971 Fix/aggregator decoding
  aggregator/aggregator.go
Labels: cla-signed, zkevm-seq-agg

#2975 fix aggregator index 0
  aggregator/aggregator.go
Labels: cla-signed

#2970 add block information to exit roots response
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm.openrpc.json
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/types/types.go
Labels: cla-signed

#2945 add support to tx l2 hash for RPC responses
  cmd/run.go
  docs/json-rpc-endpoints.md
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm.openrpc.json
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/mocks/mock_pool.go
  jsonrpc/mocks/mock_state.go
  jsonrpc/server_test.go
  jsonrpc/types/codec_test.go
  jsonrpc/types/interfaces.go
  jsonrpc/types/types.go
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  state/helper.go
  state/interfaces.go
  state/pgstatestorage/transaction.go
  state/types.go
  test/e2e/jsonrpc2_test.go
  test/e2e/shared.go
Labels: cla-signed

#2967 fix smc
  etherman/smartcontracts/abi/mockpolygonrollupmanager.abi
  etherman/smartcontracts/bin/mockpolygonrollupmanager.bin
  etherman/smartcontracts/mockpolygonrollupmanager/mockpolygonrollupmanager.go
  test/Makefile
Labels: cla-signed

#2590 Added nodes last synced batch number
  synchronizer/metrics/metrics.go
  synchronizer/synchronizer.go
Labels: qa-support

#2978 Remove unused sequencer config parameters. Remove unnecessary empty L2 block execution
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  sequencer/batch.go
  sequencer/config.go
  sequencer/datastreamer.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/l2block.go
  sequencer/sequencer.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed, zkevm-seq-agg

#2987 Update stream lib
  go.mod
  go.sum
Labels: cla-signed, zkevm-seq-agg, datastream

#2985 etrog: synchronizer permissionless: Check that permissionless are enough synchronized with L1 to process Trusted Batch
  synchronizer/common/syncinterfaces/mocks/zkevm_client_global_exit_root_getter.go
  synchronizer/common/syncinterfaces/mocks/zkevm_client_interface.go
  synchronizer/common/syncinterfaces/sync_trusted_state_executor.go
  synchronizer/common/syncinterfaces/zkevm_rpc.go
  synchronizer/interfaces.go
  synchronizer/l2_sync/l2_shared/errors.go
  synchronizer/l2_sync/l2_sync_etrog/check_sync_status_to_process_batch.go
  synchronizer/l2_sync/l2_sync_etrog/check_sync_status_to_process_batch_test.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_sync_etrog/mocks/l1_sync_checker.go
  synchronizer/l2_sync/l2_sync_etrog/mocks/state_ger_inteface.go
  synchronizer/mock_state.go
  synchronizer/mock_zkevmclient.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/Makefile
Labels: cla-signed

#2988 Update datastream lib. Sequencer order batches to send to datastream
  go.mod
  go.sum
  state/pgstatestorage/datastream.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#2990 Fix log batch response when we get an error calling executor
  state/batchV2.go
Labels: cla-signed, zkevm-seq-agg

#2991 adapt debug methods to run v1 and v2 executor requests
  state/trace.go
  state/transaction.go
Labels: cla-signed

#2996 Rename sequencer config parameters to be more consistent
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  sequencer/batch.go
  sequencer/config.go
  sequencer/dbmanager_test.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/forcedbatch.go
  sequencer/sequencer.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed, config, zkevm-seq-agg

#2998 Review sequencer logs to be more consistent. Fix resource sustract in new wip batch
  sequencer/addrqueue.go
  sequencer/batch.go
  sequencer/datastreamer.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/forcedbatch.go
  sequencer/interfaces.go
  sequencer/l2block.go
  sequencer/sequencer.go
  sequencer/txsorted_list.go
  sequencer/worker.go
Labels: cla-signed, zkevm-seq-agg

#3003 Fix sequencer/executor metrics. Rename poolPackage/statePackage to poolIntf/stateIntf.
  cmd/run.go
  db/migrations/state/0013.sql
  db/migrations/state/0013_test.go
  sequencer/batch.go
  sequencer/datastreamer.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/forcedbatch.go
  sequencer/l2block.go
  sequencer/sequencer.go
Labels: cla-signed, zkevm-seq-agg
