Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2023-09, with the labels that each got.

#2499 new rlp error
  state/transaction.go
  synchronizer/synchronizer.go
Labels: cla-signed

#2498 tool to rerun batches
  tools/state/README.md
  tools/state/control_flush_id.go
  tools/state/estimated_time.go
  tools/state/main.go
  tools/state/output_interface.go
  tools/state/output_pretty.go
  tools/state/reprocess_action.go
  tools/state/reprocess_cmd.go
  tools/state/version.go
Labels: cla-signed

#2496 benchmarks: removing the need to get sequencer IP from aws.
  test/benchmarks/sequencer/scripts/.env.example
  test/benchmarks/sequencer/scripts/README.md
  test/benchmarks/sequencer/scripts/main.go
Labels: documentation, improvement, benchmark, test, cla-signed

#2506 fix error detection
  synchronizer/synchronizer.go
Labels: cla-signed

#2507 fix rom level error while syncing
  synchronizer/synchronizer.go
Labels: cla-signed

#2490 improve: adding handling of odd-length hex strings in .
  hex/hex.go
  hex/hex_test.go
Labels: sequencer, improvement, cla-signed

#2511 Fix forkID
  db/migrations/state/0009.sql
  db/migrations/state/0009_test.go
  docker-compose.yml
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  test/docker-compose.yml
Labels: cla-signed

#2522 Update prover image to v2.2.2
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed

#2516 Cherrypick/v0.3.1 to develop
  db/migrations/state/0009.sql
  db/migrations/state/0009_test.go
  docker-compose.yml
  state/pgstatestorage.go
  state/pgstatestorage_test.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  test/docker-compose.yml
Labels: cla-signed

#2525 Remove prover ports (aggregator) from docker-compose
  test/docker-compose.yml
Labels: cla-signed

#2528 Fix rom ooc error detection (#2527)
  state/types.go
  synchronizer/synchronizer.go
Labels: cla-signed

#2529 Fix rom ooc error detection (#2527)
  state/types.go
  synchronizer/synchronizer.go
Labels: cla-signed

#2530 Fix logger
  log/log.go
Labels: cla-signed

#2524 Use ZKEVM_NETWORK variable to specify location of config files in docker compose file
  config/environments/mainnet/example.env
  config/environments/testnet/example.env
  docker-compose.yml
  docs/production-setup.md
Labels: cla-signed

#2531 cherry-pick #2524 from develop into v0.3.1
  docker-compose.yml
  docs/production-setup.md
Labels: cla-signed

#2533 improve: adding handling of odd-length hex strings in .
  hex/hex.go
  hex/hex_test.go
Labels: sequencer, cla-signed

#2485 improve the way the jRPC server log errors when returning an error response to the user
  jsonrpc/dbtxmanager.go
  jsonrpc/endpoints_debug.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/server.go
  pool/pool.go
Labels: cla-signed

#2501 only RPC component will refresh blocked addresses
  cmd/run.go
  pool/pool.go
  pool/pool_test.go
Labels: cla-signed

#2537 fix merges
  jsonrpc/endpoints_eth.go
Labels: cla-signed

#2536 avoid halt syncronization in permissionless nodes
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#2544 Fix nil evaluation
  state/transaction.go
Labels: cla-signed

#2546 avoid halt syncronization in permissionless nodes (#2536)
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#2545 avoid halt syncronization in permissionless nodes (#2536)
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#2547 Fix nil evaluation
  state/runtime/instrumentation/js/goja.go
  state/transaction.go
Labels: cla-signed

#2504 L1 synchronization in parallel
  cmd/run.go
  config/default.go
  config/gen_json_schema.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  docs/design/synchronizer/l1_synchronization.md
  synchronizer/config.go
  synchronizer/control_flush_id.go
  synchronizer/interfaces.go
  synchronizer/l1_data_message.go
  synchronizer/l1_filter_send_orderer_results_to_synchronizer.go
  synchronizer/l1_filter_send_orderer_results_to_synchronizer_test.go
  synchronizer/l1_live_block_ranges.go
  synchronizer/l1_live_block_ranges_test.go
  synchronizer/l1_rollup_info_consumer.go
  synchronizer/l1_rollup_info_consumer_statistics.go
  synchronizer/l1_rollup_info_consumer_test.go
  synchronizer/l1_rollup_info_producer.go
  synchronizer/l1_rollup_info_producer_statistics.go
  synchronizer/l1_rollup_info_producer_test.go
  synchronizer/l1_sync_orchestration.go
  synchronizer/l1_sync_orchestration_test.go
  synchronizer/l1_syncstatus.go
  synchronizer/l1_syncstatus_test.go
  synchronizer/l1_worker.go
  synchronizer/l1_worker_test.go
  synchronizer/l1_workers.go
  synchronizer/mock_l1_rollup_consumer_interface.go
  synchronizer/mock_l1_rollup_producer_interface.go
  synchronizer/mock_synchronizer_process_block_range.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
Labels: synchronizer, cla-signed

#2557 renamed test function to remove underscore
  synchronizer/l1_filter_send_orderer_results_to_synchronizer_test.go
  synchronizer/l1_rollup_info_consumer_test.go
  synchronizer/l1_rollup_info_producer_test.go
  synchronizer/l1_sync_orchestration_test.go
  synchronizer/l1_syncstatus_test.go
  synchronizer/l1_worker_test.go
Labels: synchronizer, cla-signed

#2539 add unit and e2e tests for big batch l2 data
  docker-compose.yml
  jsonrpc/endpoints_eth.go
  proto/src/proto/executor/v1/executor.proto
  state/runtime/executor/errors.go
  state/runtime/executor/executor.pb.go
  state/runtime/executor/executor_grpc.pb.go
  state/runtime/runtime.go
  state/state_test.go
  state/transaction.go
  test/docker-compose.yml
  test/e2e/jsonrpc2_test.go
Labels: cla-signed

#2560 Fix/zero gasprice panic
  ci/e2e-group2/gasless_test.go
  pool/pool.go
  test/e2e/gasless_test.go
  test/operations/manager.go
Labels: cla-signed

#2563 cherry-pick commit 2c00916 into release/v0.3.2
  docker-compose.yml
  jsonrpc/endpoints_eth.go
  proto/src/proto/executor/v1/executor.proto
  state/runtime/executor/errors.go
  state/runtime/executor/executor.pb.go
  state/runtime/executor/executor_grpc.pb.go
  state/runtime/runtime.go
  state/state_test.go
  state/transaction.go
  test/docker-compose.yml
  test/e2e/jsonrpc2_test.go
Labels: cla-signed

#2562 DB index
  db/migrations/state/0010.sql
  db/migrations/state/0010_test.go
Labels: cla-signed

#2565 Enable gasless txs on L2 (#2560)
  ci/e2e-group2/gasless_test.go
  pool/pool.go
  test/e2e/gasless_test.go
  test/operations/manager.go
Labels: cla-signed

#2568 Synchronizer L1 parallel: improve context usage
  synchronizer/l1_common.go
  synchronizer/l1_rollup_info_consumer.go
  synchronizer/l1_rollup_info_consumer_test.go
  synchronizer/l1_rollup_info_producer.go
  synchronizer/l1_rollup_info_producer_test.go
  synchronizer/l1_sync_orchestration.go
  synchronizer/l1_sync_orchestration_test.go
  synchronizer/l1_syncstatus.go
  synchronizer/l1_worker_etherman.go
  synchronizer/l1_worker_etherman_test.go
  synchronizer/l1_worker_test.go
  synchronizer/l1_workers.go
  synchronizer/mock_dbtx.go
  synchronizer/mock_etherman.go
  synchronizer/mock_ethtxmanager.go
  synchronizer/mock_l1_rollup_consumer_interface.go
  synchronizer/mock_l1_rollup_producer_interface.go
  synchronizer/mock_l1_worker.go
  synchronizer/mock_pool.go
  synchronizer/mock_state.go
  synchronizer/mock_zkevmclient.go
  synchronizer/synchronizer.go
  test/Makefile
  test/config/test.node.config.toml
  test/e2e/debug_test.go
Labels: synchronizer, cla-signed

#2577 Fix encode functions
  sequencer/datastream.go
  sequencer/datastream_test.go
  sequencer/dbmanager.go
Labels: cla-signed, cherry-picked

#2553 Fix Makefile: should start synchronizer before eth-tx-manager
  test/Makefile
Labels: cla-signed

#2576 fix trace default values and add condition to define which trace should be returned
  state/transaction.go
Labels: cla-signed

#2579 Synchronizer L1 parallel: fix stuck due error on request
  synchronizer/l1_filter_send_orderer_results_to_synchronizer.go
  synchronizer/l1_rollup_info_consumer_statistics.go
  synchronizer/l1_rollup_info_producer.go
  synchronizer/l1_syncstatus.go
  synchronizer/l1_worker_etherman.go
  synchronizer/l1_workers.go
Labels: synchronizer, cla-signed

#2587 bugfix: fixing L2 Reorg check.
  sequencer/dbmanager.go
Labels: bug, sequencer, cla-signed

#2588 cherry-pick: fixing L2 Reorg check.
  sequencer/dbmanager.go
Labels: cla-signed, cherry-pick

#2581 Refactor sending data to streamer
  cmd/run.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  go.mod
  go.sum
  sequencer/config.go
  sequencer/datastream.go
  sequencer/dbmanager.go
  sequencer/sequencer.go
Labels: cla-signed

#2585 Synchronizer L1 parallel: add control between retries to avoid spamming
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  synchronizer/config.go
  synchronizer/l1_live_block_ranges.go
  synchronizer/l1_live_block_ranges_test.go
  synchronizer/l1_rollup_info_producer.go
  synchronizer/l1_worker_etherman.go
  synchronizer/l1_worker_etherman_test.go
  synchronizer/l1_workers.go
  synchronizer/l1_workers_decorator_limit_retries_by_time.go
  synchronizer/l1_workers_decorator_limit_retries_by_time_test.go
  synchronizer/mock_l1_worker.go
  synchronizer/mock_workers.go
  synchronizer/synchronizer.go
  test/Makefile
Labels: synchronizer, cla-signed

#2570 DB index (#2562)
  db/migrations/state/0010.sql
  db/migrations/state/0010_test.go
Labels: cla-signed

#2569 Data Streamer
  cmd/run.go
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  go.mod
  go.sum
  sequencer/config.go
  sequencer/datastream.go
  sequencer/datastream_test.go
  sequencer/dbmanager.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  state/transaction.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/docker-compose.yml
  tools/rlp/README.md
Labels: cla-signed, config, cherry-pick

#2583 improve: improving benchmark scripts.
  test/benchmarks/sequencer/common/transactions/transactions.go
  test/benchmarks/sequencer/e2e/erc20-transfers/tx_sender.go
  test/benchmarks/sequencer/e2e/eth-transfers/tx_sender.go
  test/benchmarks/sequencer/e2e/uniswap-transfers/tx_sender.go
  test/benchmarks/sequencer/scripts/.env.example
  test/benchmarks/sequencer/scripts/README.md
  test/benchmarks/sequencer/scripts/environment/constants.go
  test/benchmarks/sequencer/scripts/main.go
Labels: sequencer, improvement, benchmark, cla-signed

#2602 race condition: reset trusted state memory var
  docs/config-file/node-config-doc.md
  synchronizer/synchronizer.go
Labels: cla-signed
