Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2024-04, with the labels that each got.

#3485 fix ooc check (cherry pick)
  state/batchV2.go
Labels: cla-signed, cherry-pick

#3476 sort logs by tx hash and then by log index
  state/pgstatestorage/pgstatestorage.go
  state/pgstatestorage/pgstatestorage_test.go
Labels: cla-signed

#3513 cherry-pick synchronizer support forkid 9 (#3496)
  state/forkid.go
  synchronizer/actions/forksids.go
  synchronizer/synchronizer.go
Labels: synchronizer, cla-signed, cherry-pick, zkevm-bridge-sync-rpc

#3524 #3514 Fix l1 info root after reorg (#3515)
  aggregator/aggregator.go
  aggregator/aggregator_test.go
  aggregator/interfaces.go
  aggregator/mocks/mock_state.go
  l1infotree/tree.go
  state/interfaces.go
  state/l1infotree.go
  state/mocks/mock_storage.go
  state/pgstatestorage/l1infotree.go
  state/reset.go
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/common/syncinterfaces/mocks/state_full_interface.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/e2e/forced_batches_vector_shared.go
  test/e2e/state_test.go
  tools/genesis/genesisparser/genesisparser.go
Labels: cla-signed

#3525 cheery-pick Feature/3518 use generic eth client for l2 (#3519)
  cmd/run.go
  synchronizer/actions/check_l2block.go
  synchronizer/actions/check_l2block_test.go
  synchronizer/common/syncinterfaces/mocks/zkevm_client_ethereum_compatible_interface.go
  synchronizer/common/syncinterfaces/zkevm_ethereum_compatible_client.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/Makefile
Labels: synchronizer, cla-signed, cherry-pick, zkevm-bridge-sync-rpc

#3529 fix deltaTimeStamp and TimestampLimit for eth_call
  state/transaction.go
  test/contracts/auto/CounterAndBlock.sol
  test/contracts/bin/CounterAndBlock/CounterAndBlock.go
  test/e2e/sc_test.go
Labels: cla-signed

#3534 New feijoa smc
  etherman/etherman.go
  etherman/etherman_test.go
  etherman/simulated.go
  etherman/smartcontracts/abi/elderberrypolygonzkevm.abi
  etherman/smartcontracts/abi/etrogpolygonrollupmanager.abi
  etherman/smartcontracts/abi/etrogpolygonzkevm.abi
  etherman/smartcontracts/abi/etrogpolygonzkevmbridge.abi
  etherman/smartcontracts/abi/etrogpolygonzkevmglobalexitroot.abi
  etherman/smartcontracts/abi/feijoapolygonrollupmanager.abi
  etherman/smartcontracts/abi/feijoapolygonzkevm.abi
  etherman/smartcontracts/abi/feijoapolygonzkevmglobalexitroot.abi
  etherman/smartcontracts/abi/mocketrogpolygonrollupmanager.abi
  etherman/smartcontracts/abi/mockfeijoapolygonrollupmanager.abi
  etherman/smartcontracts/abi/polygonzkevm.abi
  etherman/smartcontracts/abi/preetrogpolygonzkevm.abi
  etherman/smartcontracts/abi/preetrogpolygonzkevmbridge.abi
  etherman/smartcontracts/abi/preetrogpolygonzkevmglobalexitroot.abi
  etherman/smartcontracts/bin/elderberrypolygonzkevm.bin
  etherman/smartcontracts/bin/etrogpolygonrollupmanager.bin
  etherman/smartcontracts/bin/etrogpolygonzkevm.bin
  etherman/smartcontracts/bin/etrogpolygonzkevmbridge.bin
  etherman/smartcontracts/bin/etrogpolygonzkevmglobalexitroot.bin
  etherman/smartcontracts/bin/feijoapolygonrollupmanager.bin
  etherman/smartcontracts/bin/feijoapolygonzkevm.bin
  etherman/smartcontracts/bin/feijoapolygonzkevmglobalexitroot.bin
  etherman/smartcontracts/bin/mocketrogpolygonrollupmanager.bin
  etherman/smartcontracts/bin/mockfeijoapolygonrollupmanager.bin
  etherman/smartcontracts/bin/polygonzkevm.bin
  etherman/smartcontracts/bin/preetrogpolygonzkevm.bin
  etherman/smartcontracts/bin/preetrogpolygonzkevmbridge.bin
  etherman/smartcontracts/bin/preetrogpolygonzkevmglobalexitroot.bin
  etherman/smartcontracts/elderberrypolygonzkevm/elderberrypolygonzkevm.go
  etherman/smartcontracts/etrogpolygonrollupmanager/etrogpolygonrollupmanager.go
  etherman/smartcontracts/etrogpolygonzkevm/etrogpolygonzkevm.go
  etherman/smartcontracts/etrogpolygonzkevmbridge/etrogpolygonzkevmbridge.go
  etherman/smartcontracts/etrogpolygonzkevmglobalexitroot/etrogpolygonzkevmglobalexitroot.go
  etherman/smartcontracts/feijoapolygonrollupmanager/feijoapolygonrollupmanager.go
  etherman/smartcontracts/feijoapolygonzkevm/feijoapolygonzkevm.go
  etherman/smartcontracts/feijoapolygonzkevmglobalexitroot/feijoapolygonzkevmglobalexitroot.go
  etherman/smartcontracts/mocketrogpolygonrollupmanager/mocketrogpolygonrollupmanager.go
  etherman/smartcontracts/mockfeijoapolygonrollupmanager/mockfeijoapolygonrollupmanager.go
  etherman/smartcontracts/oldpolygonzkevmglobalexitroot/oldpolygonzkevmglobalexitroot.go
  etherman/smartcontracts/polygonzkevm/polygonzkevm.go
  etherman/smartcontracts/preetrogpolygonzkevm/preetrogpolygonzkevm.go
  etherman/smartcontracts/preetrogpolygonzkevmbridge/preetrogpolygonzkevmbridge.go
  etherman/smartcontracts/preetrogpolygonzkevmglobalexitroot/preetrogpolygonzkevmglobalexitroot.go
  etherman/smartcontracts/script.sh
  etherman/types.go
  synchronizer/actions/etrog/processor_l1_sequence_batches_test.go
  synchronizer/synchronizer_test.go
  test/e2e/forced_batches_test.go
  test/e2e/shared.go
  test/scripts/batchsender/main.go
  test/scripts/sendForcedBatch/main.go
  test/scripts/sequenceForcedBatch/main.go
  tools/rlp/main.go
Labels: cla-signed

#3528 sort logs by tx hash and then by log index (#3476)
  state/pgstatestorage/pgstatestorage.go
  state/pgstatestorage/pgstatestorage_test.go
Labels: cla-signed

#3531 fix deltaTimeStamp and TimestampLimit for eth_call (#3529)
  state/transaction.go
  test/contracts/auto/CounterAndBlock.sol
  test/contracts/bin/CounterAndBlock/CounterAndBlock.go
  test/e2e/sc_test.go
Labels: cla-signed

#3536 fix merge conflicts
  state/pgstatestorage/pgstatestorage_test.go
Labels: cla-signed

#3542 Stop syncing l1inforoot when invalid l1inforoot is detected
  event/event.go
  sequencer/finalizer.go
Labels: cla-signed, cherry-picked, zkevm-seq-agg

#3545 Feature/#3544 sync block protection
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  etherman/etherman.go
  synchronizer/config.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/config/test.node.config.toml
Labels: cla-signed

#3547 safe mode by default
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
Labels: cla-signed

#3550 Cherrypick/#3544
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  etherman/etherman.go
  synchronizer/config.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/config/test.node.config.toml
Labels: cla-signed

#3552 Cherry-pick #3480, #3542: Stop syncing l1inforoot when invalid l1inforoot is detected
  event/event.go
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/mock_etherman.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#3551 Check GER and index of synced L1InfoRoot matches with smartcontract values
  etherman/etherman.go
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/mock_etherman.go
  sequencer/sequencer.go
  state/pgstatestorage/l1infotree.go
Labels: cla-signed, cherry-picked, zkevm-seq-agg

#3556 apply txIndex fix to StoreTransactions; add migration to fix wrong txIndexes
  db/migrations/state/0019.sql
  db/migrations/state/0019_test.go
  state/transaction.go
Labels: cla-signed

#3553 Feature/#3549 reorgs improvement
  config/environments/local/local.genesis.config.json
  docs/running_local.md
  etherman/etherman.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  synchronizer/common/syncinterfaces/etherman.go
  synchronizer/common/syncinterfaces/mocks/etherman_full_interface.go
  synchronizer/common/syncinterfaces/mocks/zkevm_client_ethereum_compatible_l2_block_getter.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/config/test.genesis.config.json
  test/docker-compose.yml
  test/e2e/jsonrpc2_test.go
Labels: synchronizer, improvement, cla-signed, zkevm-bridge-sync-rpc

#3559 Fix adding tx that matches with tx that is being processed
  sequencer/addrqueue.go
  sequencer/finalizer.go
  sequencer/worker.go
  test/Makefile
Labels: cla-signed, cherry-picked, zkevm-seq-agg

#3511 remove DS LER
  sequencer/datastreamer.go
  sequencer/forcedbatch.go
  sequencer/l2block.go
  state/datastream.go
  state/pgstatestorage/datastream.go
  state/test/datastream_test.go
  tools/datastreamer/main.go
Labels: cla-signed, datastream

#3562 Add option to query by batch in DS Tool
  tools/datastreamer/Makefile
  tools/datastreamer/main.go
Labels: cla-signed

#3566 Fix/#3565 reorg
  synchronizer/synchronizer.go
Labels: cla-signed

#3517 executor v3
  event/eventlog.go
  proto/src/proto/executor/v1/executor.proto
  state/batchV2.go
  state/batchV3.go
  state/convertersV2.go
  state/convertersV3.go
  state/forkid.go
  state/mocks/mock_executor_service_client.go
  state/runtime/executor/errors.go
  state/runtime/executor/executor.pb.go
  state/runtime/executor/executor_grpc.pb.go
  state/runtime/runtime.go
  state/trace.go
  state/transaction.go
  state/types.go
  synchronizer/synchronizer.go
Labels: cla-signed

#3568 apply txIndex fix to StoreTransactions; add migration to fix wrong txIndexes (#3556)
  db/migrations/state/0019.sql
  db/migrations/state/0019_test.go
  db/migrations/state/0020.sql
  db/migrations/state/0020_test.go
  state/transaction.go
Labels: cla-signed

#3569 Cherry-pick #3551: Check GER and index of synced L1InfoRoot matches with sc values
  etherman/etherman.go
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/mock_etherman.go
  sequencer/sequencer.go
  state/pgstatestorage/l1infotree.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#3570 Cherry-pick #3559: Fix adding tx that matches with tx that is being processed
  sequencer/addrqueue.go
  sequencer/worker.go
  test/Makefile
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#3576 fix L1InfoRoot when an error happens during the process of the L1 information
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  state/l1infotree.go
  state/reset.go
  state/state.go
  synchronizer/actions/check_l2block.go
  synchronizer/actions/check_l2block_test.go
  synchronizer/synchronizer.go
Labels: cla-signed

#3582 fix #3581 synchronizer panic synchronizing from trusted node
  synchronizer/l2_sync/l2_shared/processor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_shared/trusted_batches_retrieve.go
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#3584 synchronized: #3583 stop sync from l2 after no closed batch
  synchronizer/l2_sync/l2_shared/processor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_shared/tests/trusted_batches_retrieve_test.go
  synchronizer/l2_sync/l2_shared/trusted_batches_retrieve.go
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#3586 Cherry pick: Synchronizer PR #3584, #3582. Fix panic and stop sync from Trusted after a open batch
  synchronizer/l2_sync/l2_shared/processor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_shared/tests/trusted_batches_retrieve_test.go
  synchronizer/l2_sync/l2_shared/trusted_batches_retrieve.go
Labels: synchronizer, cla-signed, cherry-pick, zkevm-bridge-sync-rpc

#3592 Feature/extralogdslib
  go.mod
  go.sum
  tools/datastreamer/main.go
Labels: cla-signed, zkevm-seq-agg

#3595 fix log
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
Labels: cla-signed

#3596 fix log
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
Labels: cla-signed

#3599 fix #3598 update GER when closing batch
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync_test.go
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#3597 Change data stream format
  Makefile
  proto/src/proto/datastream/v1/datastream.proto
  sequencer/batch.go
  sequencer/datastreamer.go
  sequencer/finalizer_test.go
  sequencer/forcedbatch.go
  sequencer/l2block.go
  sequencer/sequencer.go
  state/datastream.go
  state/datastream/datastream.pb.go
  state/pgstatestorage/datastream.go
  state/test/datastream_test.go
  test/docker-compose.yml
  tools/datastreamer/Makefile
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: sequencer, cla-signed, zkevm-seq-agg, datastream

#3587 synchronizer feijoa Part 2
  aggregator/prover/aggregator.pb.go
  aggregator/prover/aggregator_grpc.pb.go
  db/migrations/state/0023.sql
  docker-compose.yml
  etherman/feijoa_event_sequence_blobs.go
  merkletree/hashdb/hashdb.pb.go
  merkletree/hashdb/hashdb_grpc.pb.go
  proto/src/proto/executor/v1/executor.proto
  state/batch_pending.go
  state/blob_inner_in.go
  state/blob_inner_process.go
  state/blob_inner_request.go
  state/blob_inner_response.go
  state/blob_sequences.go
  state/interfaces.go
  state/mocks/mock_storage.go
  state/pgstatestorage/batch_pending.go
  state/pgstatestorage/blob_inner_in.go
  state/pgstatestorage/blob_sequences.go
  state/pgstatestorage/l1infotree_recursive.go
  state/pgstatestorage/pgstatestorage_test.go
  state/runtime/executor/executor.pb.go
  state/runtime/executor/executor_grpc.pb.go
  synchronizer/actions/feijoa/processor_l1_sequence_blobs.go
  synchronizer/actions/feijoa/processor_l1_sequence_blobs_test.go
  synchronizer/common/syncinterfaces/mocks/state_blob_sequence_writer.go
  synchronizer/common/syncinterfaces/mocks/state_blob_sequencer.go
  synchronizer/common/syncinterfaces/mocks/state_blob_sequencer_reader.go
  synchronizer/common/syncinterfaces/mocks/state_full_interface.go
  synchronizer/common/syncinterfaces/state.go
  synchronizer/default_l1processors.go
  test/docker-compose.yml
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#3606 activate sonarcloud
  .github/workflows/sonarcloud.yml
  .github/workflows/sonarqube.yml
  sonar-project.properties
  test/Makefile
Labels: ci/cd, cla-signed

#3604 Sequencer L2 block parallel processing improvements
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  db/migrations/state/0021.sql
  db/migrations/state/0021_test.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  event/event.go
  go.mod
  go.sum
  sequencer/addrqueue.go
  sequencer/addrqueue_test.go
  sequencer/batch.go
  sequencer/config.go
  sequencer/datastreamer.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/forcedbatch.go
  sequencer/interfaces.go
  sequencer/l2block.go
  sequencer/metrics.go
  sequencer/mock_state.go
  sequencer/mock_worker.go
  sequencer/sequencer.go
  sequencer/waitgroupcount.go
  sequencer/worker.go
  sequencer/worker_test.go
  state/batch.go
  state/batchV2.go
  state/pgstatestorage/batch.go
  state/test/forkid_etrog/etrog_test.go
  synchronizer/common/syncinterfaces/mocks/state_full_interface.go
  synchronizer/common/syncinterfaces/state.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync_test.go
  synchronizer/l2_sync/l2_sync_etrog/mocks/state_interface.go
  synchronizer/synchronizer_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/docker-compose.yml
Labels: cla-signed, config, cherry-picked, zkevm-seq-agg

#3608 Update DS Format
  Makefile
  proto/src/proto/datastream/v1/datastream.proto
  sequencer/batch.go
  sequencer/datastreamer.go
  sequencer/finalizer_test.go
  sequencer/forcedbatch.go
  sequencer/l2block.go
  sequencer/sequencer.go
  state/datastream.go
  state/datastream/datastream.pb.go
  state/pgstatestorage/datastream.go
  state/test/datastream_test.go
  test/docker-compose.yml
  tools/datastreamer/Makefile
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: sequencer, cla-signed, zkevm-seq-agg, datastream
