Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2024-01, with the labels that each got.

#3008 Fix/l2 block nonce
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/types/types.go
Labels: cla-signed

#3006 Data stream tool improvements
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed, zkevm-seq-agg

#2982 fix l2Blockheader when is synced
  jsonrpc/mocks/mock_pool.go
  jsonrpc/mocks/mock_state.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  state/transaction.go
  synchronizer/interfaces.go
  synchronizer/l2_sync/l2_sync_incaberry/sync_trusted_state.go
  synchronizer/mock_state.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#3010 e2e test fixes for groups 1, 2, 3, 4 and 7
  ci/e2e-group1/constants.go
  docker-compose.yml
  jsonrpc/client/eth.go
  jsonrpc/endpoints_eth.go
  pool/pool.go
  state/runtime/runtime.go
  state/transaction.go
  test/config/test.node.config.toml
  test/docker-compose.yml
  test/e2e/jsonrpc1_test.go
  test/e2e/jsonrpc2_test.go
  test/operations/manager.go
Labels: cla-signed

#3017 fix sync permissionless partial process
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#3019 Fixes executor error handling
  docker-compose.yml
  etherman/etherman.go
  sequencer/finalizer.go
  state/batchV2.go
  test/config/test.genesis-v1tov2.config.json
  test/docker-compose.yml
Labels: cla-signed

#3021 Fix process empty L2 block
  sequencer/l2block.go
  state/batchV2.go
Labels: cla-signed, zkevm-seq-agg

#3024 Fix finalizer forced batches. Fix storage.GetBatchByForcedBatchNum
  sequencer/forcedbatch.go
  sequencesender/interfaces.go
  sequencesender/sequencesender.go
  state/pgstatestorage/forcedbatch.go
Labels: cla-signed, zkevm-seq-agg

#3025 Disable e2e forced batches tests, groups 9, 10 and 11
  sequencer/closingsignalsmanager_test.go
  sequencer/dbmanager_test.go
  sequencer/finalizer_test.go
  test/e2e/forced_batches_test.go
  test/e2e/forced_batches_vector_group1_test.go
  test/e2e/forced_batches_vector_group2_test.go
  test/e2e/forced_batches_vector_group3_test.go
Labels: cla-signed, zkevm-seq-agg

#3029 Allow extra l2 information to be retrieved from standard endpoints conditionally
  docs/json-rpc-endpoints.md
  jsonrpc/client/eth.go
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/types/types.go
  test/e2e/jsonrpc1_test.go
Labels: cla-signed

#3033 Fix/sync l1 info tree data
  sequencer/interfaces.go
  sequencer/mock_state.go
  sequencer/mock_worker.go
  state/batchV2.go
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/interfaces.go
  synchronizer/mock_state.go
Labels: cla-signed

#3030 Added EGP value for eth transfer. Fix zkevm_EstimateFee endpoint. Remove use minGasPriceAllowed on EGP calculation
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  jsonrpc/endpoints_zkevm.go
  jsonrpc/mocks/mock_pool.go
  jsonrpc/types/interfaces.go
  pool/config.go
  pool/effectivegasprice.go
  pool/effectivegasprice_test.go
  pool/pool.go
  pool/pool_test.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed, config, cherry-picked, zkevm-seq-agg

#3034 Update dependencies and fix datastream generation
  go.mod
  go.sum
  state/datastream.go
Labels: cla-signed

#3035 Cherry-pick #3000: Add zkevm_EstimateFee endpoint
  jsonrpc/endpoints_zkevm.go
  jsonrpc/mocks/mock_pool.go
  jsonrpc/types/interfaces.go
  pool/pool.go
Labels: cla-signed, cherry-pick, zkevm-bridge-sync-rpc

#3032 fix synchronizer unittest
  cmd/run.go
  metrics/prometheus.go
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/common/syncinterfaces/sync_trusted_state_executor.go
  synchronizer/l2_sync/l2_shared/trusted_batches_retrieve.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/Makefile
  test/e2e/permissionlessrpc_test.go
  test/operations/manager.go
  test/operations/wait.go
Labels: synchronizer, test, cla-signed, zkevm-bridge-sync-rpc

#3039 fixes v1tov2
  synchronizer/actions/etrog/processor_l1_info_tree_update.go
  test/config/test.genesis-v1tov2.config.json
Labels: cla-signed

#3043 Add new etrog fields to Data Stream and update tool
  cmd/run.go
  config/config_test.go
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  go.mod
  go.sum
  sequencer/config.go
  sequencer/datastreamer.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  state/datastream.go
  state/pgstatestorage/datastream.go
  state/test/datastream_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed, zkevm-seq-agg, datastream

#3036 Fix StopSequencerOnBatchNum implementation
  pool/effectivegasprice.go
  sequencer/finalizer.go
Labels: cla-signed, zkevm-seq-agg

#3048 Fix/aggregator etrog inforoot
  aggregator/aggregator.go
  aggregator/interfaces.go
  aggregator/mocks/mock_state.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  state/batchV2.go
  state/datastream.go
  state/interfaces.go
  state/pgstatestorage/batch.go
Labels: cla-signed

#3049 fix sequencerAddress
  etherman/etherman.go
Labels: cla-signed

#3045 revert l2 block hash to ethereum standard
  state/l2block.go
  state/l2block_test.go
  state/pgstatestorage/l2block.go
  state/pgstatestorage/pgstatestorage_test.go
  state/test/forkid_dragonfruit/dragonfruit_test.go
  state/test/forkid_dragonfruit/genesis_test.go
  state/transaction.go
  test/e2e/debug_calltracer_test.go
Labels: cla-signed

#3052 fix l1InfoRoot in sync, aggregator and state
  aggregator/aggregator.go
  aggregator/interfaces.go
  aggregator/mocks/mock_state.go
  db/migrations/state/0013.sql
  db/migrations/state/0013_test.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  state/batch.go
  state/batchV2.go
  state/datastream.go
  state/interfaces.go
  state/pgstatestorage/batch.go
  state/pgstatestorage/l1infotree.go
  state/pgstatestorage/pgstatestorage_test.go
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
Labels: cla-signed

#3040 Add more unittest to synchronizer
  synchronizer/actions/actions.go
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/common/critical_error_halt.go
  synchronizer/common/syncinterfaces/critical_error_handler.go
  synchronizer/common/syncinterfaces/mocks/critical_error_handler.go
  synchronizer/default_l1processors.go
  synchronizer/l1_parallel_sync/block_range.go
  synchronizer/l1_parallel_sync/l1_data_message.go
  synchronizer/l1_parallel_sync/l1_rollup_info_consumer.go
  synchronizer/l1_parallel_sync/l1_rollup_info_consumer_test.go
  synchronizer/l1_parallel_sync/l1_rollup_info_producer.go
  synchronizer/l1_parallel_sync/l1_syncstatus.go
  synchronizer/l1_parallel_sync/l1_worker_etherman.go
  synchronizer/l1_parallel_sync/l1_worker_etherman_test.go
  synchronizer/l2_sync/l2_shared/batch_compare.go
  synchronizer/l2_sync/l2_shared/batch_compare_test.go
  synchronizer/l2_sync/l2_shared/processor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_shared/tests/processor_trusted_batch_sync_test.go
  synchronizer/l2_sync/l2_shared/trusted_state.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync_test.go
  synchronizer/synchronizer.go
Labels: synchronizer, test, cla-signed, zkevm-bridge-sync-rpc

#3055 fix aggregator batch timestamp
  state/pgstatestorage/batch.go
Labels: cla-signed

#3054 Feature/stream batch bookmark
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  sequencer/batch.go
  sequencer/datastreamer.go
  sequencer/finalizer.go
  sequencer/sequencer.go
  sequencesender/config.go
  state/datastream.go
  test/config/test.node.config.toml
  tools/datastreamer/main.go
Labels: cla-signed

#2986 Tool/egp
  tools/egp/README.md
  tools/egp/cfg/egp0.config.toml
  tools/egp/cfg/egp1.config.toml
  tools/egp/cfg/egp2.config.toml
  tools/egp/main.go
Labels: cla-signed, zkevm-seq-agg

#3061 fix timestamp limit while syncing from scratch
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
Labels: cla-signed

#3064 remove l1iforoot from stream
  sequencer/datastreamer.go
  sequencer/sequencer.go
  state/datastream.go
  state/pgstatestorage/datastream.go
  state/test/datastream_test.go
  tools/datastreamer/main.go
Labels: zkevm-seq-agg

#3063 fix unit tests
  aggregator/aggregator_test.go
  state/pgstatestorage/batch.go
  state/pgstatestorage/pgstatestorage_test.go
  synchronizer/synchronizer_test.go
Labels: cla-signed

#3062 fix storing GER from L1 events
  state/batchV2.go
  state/batchV2_test.go
  state/convertersV2.go
  state/l1infotree.go
  state/mocks/mock_dbtx.go
  state/mocks/mock_executor_service_client.go
  state/mocks/mock_storage.go
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/l2_sync/l2_sync_etrog/check_sync_status_to_process_batch.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
  test/Makefile
  test/docker-compose.yml
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#3065 remove ZeroL1InfoRoot cte
  state/l1infotree.go
Labels: cla-signed

#3067 trusted sync: fix local_exit_root
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
Labels: cla-signed

#3069 v1 to v2 working
  etherman/etherman.go
  test/Makefile
  test/config/test.genesis-v1tov2.config.json
  test/docker-compose.yml
Labels: cla-signed

#3041 Cherry-pick #3030: Added EGP value for eth transfer. Fix zkevm_EstimateFee endpoint. Remove use minGasPriceAllowed on EGP calculation
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  jsonrpc/endpoints_zkevm.go
  jsonrpc/mocks/mock_pool.go
  jsonrpc/types/interfaces.go
  pool/config.go
  pool/effectivegasprice.go
  pool/effectivegasprice_test.go
  pool/pool.go
  pool/pool_test.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed, config, cherry-pick, zkevm-seq-agg

#3070 if a batch have no l2block it returns an zero l1inforoot
  state/batch.go
Labels: synchronizer, state, cla-signed

#3058 feat: optimized txpool purge
  pool/interfaces.go
  pool/pgpoolstorage/pgpoolstorage.go
  sequencer/interfaces.go
  sequencer/mock_pool.go
  sequencer/mock_state.go
  sequencer/sequencer.go
  state/pgstatestorage.go
Labels: cla-signed

#3077 add new executor errors
  docker-compose.yml
  proto/src/proto/executor/v1/executor.proto
  state/runtime/executor/errors.go
  state/runtime/executor/executor.pb.go
  state/runtime/runtime.go
  test/docker-compose.yml
Labels: cla-signed, zkevm-seq-agg

#3068 Populate f.currentGERHash and f.previousGERHash on finalizer start.
  sequencer/finalizer.go
  sequencer/finalizer_test.go
Labels: bug, cla-signed, zkevm-seq-agg

#3078 Add L1 block timestamp margin to send sequences
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  pool/effectivegasprice_test.go
  sequencer/batch.go
  sequencer/finalizer.go
  sequencer/l2block.go
  sequencesender/config.go
  sequencesender/interfaces.go
  sequencesender/sequencesender.go
  state/pgstatestorage/l2block.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed, config, zkevm-seq-agg

#3084 Fix finalize l2block when closing batch due to exhausted resource
  sequencer/batch.go
  sequencer/l2block.go
  state/runtime/runtime.go
Labels: cla-signed, zkevm-seq-agg

#3086 reprocess trusted batch, use GER of leaf 0 of L1InfoRoot
  sequencer/finalizer_test.go
  state/helper.go
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/interfaces.go
  synchronizer/l2_sync/l2_shared/batch_compare.go
  synchronizer/l2_sync/l2_shared/processor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_shared/tests/batch_compare_test.go
  synchronizer/l2_sync/l2_shared/tests/processor_trusted_batch_sync_test.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync_test.go
  synchronizer/mock_state.go
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#3051 fix default value for fromBlock when calling eth_getLogs
  jsonrpc/endpoints_eth.go
Labels: cla-signed

#3002 Security - Add SHA Pin to Third Party Actions/Checkout Action (fixes #3001)
  .github/workflows/codeql.yml
  .github/workflows/jsonschema.yml
  .github/workflows/lint.yml
  .github/workflows/push-docker-develop.yml
  .github/workflows/push-docker-tagged.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test-from-prover.yml
  .github/workflows/test-full-non-e2e.yml
  .github/workflows/updatedeps.yml
Labels: cla-signed

#3092 for L1 sequence batch event if the batch only use leaf 0 set GER as 0x0...0000
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/interfaces.go
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#3090 Return zero GER when L1IntroTreeIndex is 0
  sequencer/finalizer.go
Labels: cla-signed, zkevm-seq-agg

#3094 fix etrog stream generation
  state/datastream.go
  state/pgstatestorage/datastream.go
Labels: bug, cla-signed, zkevm-seq-agg

#3093 synchronizer: remove fatals
  synchronizer/l2_sync/l2_shared/processor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
  synchronizer/synchronizer.go
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#3097 Feature/#3081 smc
  etherman/etherman.go
  etherman/simulated.go
  etherman/smartcontracts/abi/mockpolygonrollupmanager.abi
  etherman/smartcontracts/abi/polygonrollupmanager.abi
  etherman/smartcontracts/abi/polygonzkevm.abi
  etherman/smartcontracts/abi/polygonzkevmbridge.abi
  etherman/smartcontracts/abi/proxy.abi
  etherman/smartcontracts/bin/mockpolygonrollupmanager.bin
  etherman/smartcontracts/bin/mockverifier.bin
  etherman/smartcontracts/bin/polygonrollupmanager.bin
  etherman/smartcontracts/bin/polygonzkevm.bin
  etherman/smartcontracts/bin/polygonzkevmbridge.bin
  etherman/smartcontracts/bin/polygonzkevmglobalexitroot.bin
  etherman/smartcontracts/bin/proxy.bin
  etherman/smartcontracts/mockpolygonrollupmanager/mockpolygonrollupmanager.go
  etherman/smartcontracts/mockverifier/mockverifier.go
  etherman/smartcontracts/polygonrollupmanager/polygonrollupmanager.go
  etherman/smartcontracts/polygonzkevm/polygonzkevm.go
  etherman/smartcontracts/polygonzkevmbridge/polygonzkevmbridge.go
  etherman/smartcontracts/polygonzkevmglobalexitroot/polygonzkevmglobalexitroot.go
  etherman/smartcontracts/proxy/proxy.go
  etherman/smartcontracts/script.sh
  etherman/types.go
  sequencer/batch.go
  sequencer/interfaces.go
  sequencer/mock_state.go
  state/batch.go
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/actions/etrog/processor_l1_update_etrog_sequence.go
  synchronizer/actions/processor_manager/processors_builder.go
  synchronizer/default_l1processors.go
  synchronizer/interfaces.go
  synchronizer/l1event_orders/sequence_extractor.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync_test.go
  synchronizer/l2_sync/l2_sync_etrog/mocks/state_interface.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/config/test.genesis-v1tov2.config.json
  test/e2e/forced_batches_test.go
  test/e2e/shared.go
  test/scripts/sendForcedBatch/main.go
Labels: cla-signed

#3095 etrog: Fix synchronizer OOC sequenced batch
  cmd/run.go
  state/batchV2.go
  state/batchV2_test.go
  state/convertersV2.go
  synchronizer/actions/etrog/processor_l1_sequence_batches_test.go
  synchronizer/common/syncinterfaces/eth_tx_manager.go
  synchronizer/common/syncinterfaces/etherman.go
  synchronizer/common/syncinterfaces/mocks/eth_tx_manager.go
  synchronizer/common/syncinterfaces/mocks/etherman_full_interface.go
  synchronizer/common/syncinterfaces/mocks/pool_interface.go
  synchronizer/common/syncinterfaces/mocks/state_full_interface.go
  synchronizer/common/syncinterfaces/mocks/synchronizer_clean_trusted_state.go
  synchronizer/common/syncinterfaces/mocks/synchronizer_full_interface.go
  synchronizer/common/syncinterfaces/mocks/synchronizer_is_trusted_sequencer.go
  synchronizer/common/syncinterfaces/pool.go
  synchronizer/common/syncinterfaces/state.go
  synchronizer/common/syncinterfaces/sync.go
  synchronizer/control_flush_id.go
  synchronizer/interfaces.go
  synchronizer/mock_etherman.go
  synchronizer/mock_ethtxmanager.go
  synchronizer/mock_pool.go
  synchronizer/mock_state.go
  synchronizer/synchronizer.go
  synchronizer/synchronizer_test.go
  test/Makefile
Labels: synchronizer, test, cla-signed, zkevm-bridge-sync-rpc

#3100 fix OOC errors
  jsonrpc/endpoints_eth.go
  state/runtime/executor/errors.go
  state/runtime/runtime.go
Labels: cla-signed, zkevm-seq-agg

#3089 remove l2 hash from eth_getTransactionReceipt
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/types/types.go
Labels: cla-signed

#3099 Fix set l1InfoRootIndex on changeL2Block
  docker-compose.yml
  sequencer/batch.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/forcedbatch.go
  sequencer/l2block.go
  state/batchV2.go
  test/docker-compose.yml
Labels: cla-signed, zkevm-seq-agg

#3101 fix stream
  state/datastream.go
Labels: cla-signed, zkevm-seq-agg

#3104 Fix batch GER
  sequencer/batch.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/l2block.go
Labels: cla-signed, zkevm-seq-agg

#3109 force version of json-schema-for-humans to 0.47
  Makefile
Labels: documentation, cla-signed

#3103 add new endpoint zkevm_getLatestGlobalExitRoot
  db/migrations/state/0014.sql
  db/migrations/state/0014_test.go
  jsonrpc/client/zkevm.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm.openrpc.json
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/mocks/mock_state.go
  jsonrpc/types/interfaces.go
  state/interfaces.go
  state/mocks/mock_storage.go
  state/pgstatestorage/batch.go
  state/pgstatestorage/pgstatestorage_test.go
Labels: cla-signed

#3112 Fix merkle proof in aggregator. Fix finalize batch on sequencer
  aggregator/aggregator.go
  docker-compose.yml
  sequencer/batch.go
  sequencer/finalizer.go
  sequencer/l2block.go
  test/docker-compose.yml
Labels: cla-signed, zkevm-seq-agg

#3113 Fix new wipL2block on finalizeBatch function
  docker-compose.yml
  sequencer/batch.go
  sequencer/interfaces.go
  sequencer/l2block.go
  sequencer/mock_state.go
  test/docker-compose.yml
Labels: cla-signed, zkevm-seq-agg

#3115 fix l1InfoRoot
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
Labels: cla-signed

#3114 update prover image
  docker-compose.yml
  test/docker-compose.yml
  test/vectors/src/etrog/balances.json
  test/vectors/src/etrog/chain-ids.json
  test/vectors/src/etrog/general.json
  test/vectors/src/etrog/nonces.json
  test/vectors/src/etrog/seq-fees.json
Labels: cla-signed, zkevm-seq-agg

#3117 Feature/aggregator update etrog batch
  aggregator/aggregator.go
  aggregator/config.go
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  test/docker-compose.yml
Labels: cla-signed

#3118 Add L2 block sequential process. Execute empty L2 block. Add tracking number to L2 block. Several refactors
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  sequencer/batch.go
  sequencer/config.go
  sequencer/finalizer.go
  sequencer/finalizer_test.go
  sequencer/l2block.go
  sequencer/worker.go
  sequencer/worker_test.go
  sequencesender/sequencesender.go
  state/batch.go
  state/errors.go
  state/pgstatestorage/pgstatestorage_test.go
  state/types.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
Labels: cla-signed, config, zkevm-seq-agg

#3126 Fix migration batch wip field. Fix send sequence when no wip batch
  db/migrations/state/0013.sql
  sequencer/l2block.go
  sequencesender/sequencesender.go
  state/batch.go
Labels: cla-signed, zkevm-seq-agg

#3127 fix Leaves smtproof
  aggregator/aggregator.go
  aggregator/aggregator_test.go
Labels: cla-signed

#3124 fix default value for fromBlock when calling eth_getLogs
  cmd/run.go
  jsonrpc/endpoints_eth.go
Labels: cla-signed

#3129 Add l2block log dump when storing error. Refactor ProcessBatchV2 logs
  sequencer/l2block.go
  state/batchV2.go
  state/convertersV2.go
  state/pgstatestorage/l2block.go
Labels: cla-signed, zkevm-seq-agg

#3133 fix panic etherman
  etherman/etherman.go
Labels: cla-signed

#3134 Fix GetL2Hash function. Use tx L2 hash returned by the executor when storing L2Block. Logs changes
  docker-compose.yml
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/l2block.go
  sequencer/mock_state.go
  sequencer/worker.go
  state/batchV2.go
  state/convertersV2.go
  state/genesis.go
  state/interfaces.go
  state/mocks/mock_storage.go
  state/pgstatestorage/l2block.go
  state/pgstatestorage/pgstatestorage_test.go
  state/test/forkid_dragonfruit/dragonfruit_test.go
  state/test/forkid_independent/independent_test.go
  state/test/l2txhash_test.go
  state/transaction.go
  test/docker-compose.yml
Labels: cla-signed, zkevm-seq-agg

#3139 remove l2 tx hash computation and use data stored in the state returned by the executor
  jsonrpc/endpoints_eth.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_zkevm.go
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/mocks/mock_state.go
  jsonrpc/types/interfaces.go
  jsonrpc/types/types.go
  state/genesis.go
  state/interfaces.go
  state/mocks/mock_storage.go
  state/pgstatestorage/pgstatestorage_test.go
  state/pgstatestorage/transaction.go
  state/test/forkid_dragonfruit/dragonfruit_test.go
  state/test/forkid_independent/independent_test.go
  state/test/l2txhash_test.go
  state/transaction.go
Labels: cla-signed

#3140 etrog: fix permissionless errors
  synchronizer/l1_parallel_sync/l1_rollup_info_producer.go
  synchronizer/l1_parallel_sync/l1_workers.go
  synchronizer/l1_parallel_sync/mock_workers_interface.go
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#3122 Fix missing batch bookmark
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  sequencer/sequencer.go
  sequencesender/config.go
  state/datastream.go
  state/pgstatestorage/datastream.go
Labels: cla-signed

#3142 fix wipL2Block deltaTimestamp
  sequencer/finalizer.go
  sequencer/l2block.go
  state/batchV2.go
Labels: cla-signed, zkevm-seq-agg

#3145 fix wipL2Block imStateRoot
  sequencer/batch.go
  sequencer/finalizer.go
  sequencer/l2block.go
  state/batch.go
  state/batchV2.go
Labels: cla-signed, zkevm-seq-agg

#3146 fix panic NewStackTrie
  state/transaction.go
Labels: cla-signed, zkevm-bridge-sync-rpc

#3147 fix sync initalization for etrog
  state/transaction.go
Labels: cla-signed

#3148 fix wipL2block imStateRoot
  sequencer/batch.go
  sequencer/errors.go
  sequencer/finalizer.go
  sequencer/l2block.go
  sequencer/worker.go
Labels: cla-signed, zkevm-seq-agg

#3150 fix tracer to work by block stateroot instead of by tx
  db/migrations/state/0015.sql
  db/migrations/state/0015_test.go
  state/pgstatestorage/transaction.go
  state/trace.go
Labels: cla-signed

#3151 update prover image
  docker-compose.yml
  test/config/test.prover.config.json
  test/docker-compose.yml
  test/vectors/src/etrog/balances.json
  test/vectors/src/etrog/chain-ids.json
  test/vectors/src/etrog/general.json
  test/vectors/src/etrog/nonces.json
  test/vectors/src/etrog/seq-fees.json
Labels: cla-signed, zkevm-seq-agg

#3152 if a trusted batch is empty and WIP just create the entry in state.batch
  etherman/etherman.go
  synchronizer/common/converters.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#3153 fix trace for tx index greater than 0
  state/trace.go
  test/e2e/debug_calltracer_test.go
  test/e2e/debug_shared.go
  test/e2e/debug_test.go
Labels: cla-signed

#3154 add cardona.zip to releases files
  .github/workflows/release.yml
Labels: ci/cd, cla-signed, zkevm-bridge-sync-rpc

#3156 Fix default value when creating transaction.used_sha256_hashes field in the pool
  db/migrations/pool/0012.sql
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed

#3149 new fields in stream
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  sequencer/config.go
  sequencer/datastreamer.go
  sequencer/forcedbatch.go
  sequencer/l2block.go
  sequencer/sequencer.go
  state/datastream.go
  state/test/datastream_test.go
  test/config/test.node.config.toml
  test/e2e/jsonrpc2_test.go
  tools/datastreamer/config/config.go
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed, config, zkevm-seq-agg

#3158 set stateManagerPurge to false in Cardona
  config/environments/cardona/prover.config.json
Labels: cla-signed

#3159 synchronizer: fix case emtpy batch and unittest
  synchronizer/common/converters.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync_test.go
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#3160 update prover image to v4.0.1
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed, zkevm-seq-agg

#3162 Update prover image to v4.0.2
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed, zkevm-seq-agg

#3163 Add a note in deployment instruction to restart rpc after forkId 7
  docs/production-setup.md
Labels: rpc, cla-signed, zkevm-bridge-sync-rpc

#3143 EncodeBatchV2 allow to set Tx in binary
  .github/workflows/jsonschema.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test-from-prover.yml
  .github/workflows/test-full-non-e2e.yml
  state/batchV2.go
  state/encoding_batch_v2.go
  state/encoding_batch_v2_test.go
  state/helper.go
  state/interfaces.go
  state/pgstatestorage/batch.go
  state/test/forkid_etrog/etrog_test.go
  synchronizer/synchronizer_test.go
Labels: state, cla-signed, zkevm-bridge-sync-rpc

#3111 synchronizer: unittest and separation of pool_reorg to unittest that
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/actions/etrog/processor_l1_sequence_batches_test.go
  synchronizer/default_l1processors.go
Labels: synchronizer, test, cla-signed, zkevm-bridge-sync-rpc

#3168 synchronizer: unittest and remove pool_reorg (#3111)
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/actions/etrog/processor_l1_sequence_batches_test.go
  synchronizer/default_l1processors.go
Labels: synchronizer, cla-signed, cherry-pick, zkevm-bridge-sync-rpc

#3170 avoid unnecessary get code call when address doesn't have code hash
  merkletree/tree.go
  merkletree/tree_test.go
Labels: cla-signed

#3171 fix parentHash when storing a new L2 block
  state/interfaces.go
  state/mocks/mock_storage.go
  state/pgstatestorage/l2block.go
  state/transaction.go
Labels: cla-signed, zkevm-seq-agg

#3177 Fix/rom error
  state/batchV2.go
Labels: cla-signed

#3174 Cherry-pick #3171: fix parentHash when storing a new L2 block
  state/interfaces.go
  state/mocks/mock_storage.go
  state/pgstatestorage/l2block.go
  state/transaction.go
Labels: cla-signed, cherry-picked, zkevm-seq-agg

#3180 Cherrypick/#3179 geth version
  etherman/etherman_test.go
  etherman/simulated.go
  go.mod
  go.sum
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/server_test.go
  state/genesis.go
  state/pgstatestorage/pgstatestorage_test.go
  state/test/forkid_dragonfruit/dragonfruit_test.go
  state/test/forkid_independent/independent_test.go
  state/transaction.go
Labels: cla-signed, cherry-pick

#3181 Add sanity check: last L2 block timestamp in the sequence is also L1BlockTimestampMargin seconds behind "now"
  docker-compose.yml
  etherman/etherman.go
  sequencesender/interfaces.go
  sequencesender/sequencesender.go
  test/docker-compose.yml
Labels: cla-signed, cherry-picked, zkevm-seq-agg

#3179 new geth version
  etherman/etherman_test.go
  etherman/simulated.go
  go.mod
  go.sum
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/server_test.go
  state/genesis.go
  state/pgstatestorage/pgstatestorage_test.go
  state/test/forkid_dragonfruit/dragonfruit_test.go
  state/test/forkid_independent/independent_test.go
  state/transaction.go
Labels: cla-signed, cherry-pick
