Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2024-08, with the labels that each got.

#3745 Fix release github action
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: cla-signed, cherry-picked, zkevm-seq-agg

#3744 Fix tx OOC (node level) when first empty L2 block in batch
  pool/config_test.go
  pool/pool.go
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/l2block.go
  sequencer/mock_worker.go
  sequencer/worker.go
  sequencer/worker_test.go
  state/config.go
Labels: cla-signed, cherry-picked, zkevm-seq-agg

#3747 Cherry-pick #3745: Fix release github action
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: cla-signed, cherry-picked, zkevm-seq-agg

#3749 Fix tx order in zkevm_getBatchByNumber endpoint response
  state/pgstatestorage/transaction.go
Labels: cla-signed, cherry-picked, zkevm-bridge-sync-rpc

#3752 Cherry Pick add l2blockend to DS (#3751)
  proto/src/proto/datastream/v1/datastream.proto
  sequencer/sequencer.go
  state/datastream.go
  state/datastream/datastream.pb.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  tools/datastreamer/README.md
  tools/datastreamer/config/default.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed, config, cherry-pick, datastream

#3750 Fix timestamp when querying zkevm_getBatchByNumer and the batch is only in trusted state
  state/batch.go
  state/pgstatestorage/batch.go
Labels: cla-signed, cherry-picked, zkevm-bridge-sync-rpc

#3755 Cherry-pick #3745: Fix release github action
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#3757 Cherry-picks #3727: Kill inactive datastream clients
  config/config_test.go
  config/default.go
  config/environments/local/local.node.config.toml
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  go.mod
  go.sum
  sequencer/config.go
  sequencer/sequencer.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  tools/datastreamer/config/config.go
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#3758 Cherry-pick #3734: Add mined l1blocknumber to MonitoredTxResult
  ethtxmanager/ethtxmanager.go
  ethtxmanager/monitoredtx.go
  sequencesender/sequencesender.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#3759 Cherry-pick #3735: Wait the state to be synced when starting aggregator
  aggregator/aggregator.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#3760 Cherry-pick #3741: Fix update datastream file
  state/datastream.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#3763 Cherry-pick #3743: Refactor datastream logs
  go.mod
  go.sum
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#3764 Cherry-pick #3744: Fix tx OOC (node level) when first empty L2 block in batch
  pool/config_test.go
  pool/pool.go
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/l2block.go
  sequencer/mock_worker.go
  sequencer/worker.go
  sequencer/worker_test.go
  state/config.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#3766 Cherry-pick #3748: Fix invalid "updateGER" entry when updating datastream file on startup
  state/datastream.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#3767 Cherry-pick #3749: Fix tx order in zkevm_getBatchByNumber endpoint
  state/pgstatestorage/transaction.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#3768 Cherry-pick #3750: Fix timestamp when querying zkevm_getBatchByNumer and the batch is only in trusted state
  state/batch.go
  state/pgstatestorage/batch.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg
