Repository 0xPolygonHermez/zkevm-node, pull requests merged in 2024-03, with the labels that each got.

#3406 Feature/cherry pick 3375 sync add check l2block hash
  config/config_test.go
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  synchronizer/l2_sync/config.go
  synchronizer/l2_sync/l2_shared/post_closed_batch_check_l2block.go
  synchronizer/l2_sync/l2_shared/processor_trusted_batch_sync.go
  synchronizer/l2_sync/l2_sync_etrog/executor_trusted_batch_sync.go
  synchronizer/synchronizer.go
Labels: synchronizer, cla-signed, config, cherry-pick, zkevm-bridge-sync-rpc

#3407 Update prover image to v5.0.3
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed, zkevm-seq-agg

#3410 Add LER to stream
  sequencer/datastreamer.go
  sequencer/forcedbatch.go
  sequencer/l2block.go
  state/datastream.go
  state/pgstatestorage/datastream.go
  state/test/datastream_test.go
  test/config/debug.node.config.toml
  test/config/test.node.config.toml
  tools/datastreamer/config/tool.config.toml
  tools/datastreamer/main.go
Labels: cla-signed, config, zkevm-seq-agg, datastream

#3428 Fix gaslimit and cumulativeGasUsed for Elderberry transactions
  state/convertersV2.go
  state/helper.go
  state/transaction.go
  state/types.go
Labels: cla-signed, zkevm-seq-agg

#3430 Fix keep empty RPC.SequencerNodeURI config parameter to get node URI from the SC
  config/environments/cardona/node.config.toml
  config/environments/mainnet/node.config.toml
  config/environments/testnet/node.config.toml
Labels: cla-signed, config, cherry-picked, zkevm-seq-agg

#3427 keep im state root in db
  db/migrations/state/0017.sql
  proto/src/proto/executor/v1/executor.proto
  state/datastream.go
  state/genesis.go
  state/helper.go
  state/interfaces.go
  state/mocks/mock_storage.go
  state/pgstatestorage/datastream.go
  state/pgstatestorage/l2block.go
  state/pgstatestorage/pgstatestorage_test.go
  state/pgstatestorage/transaction.go
  state/runtime/executor/errors.go
  state/runtime/executor/executor.pb.go
  state/runtime/runtime.go
  state/test/forkid_dragonfruit/dragonfruit_test.go
  state/test/forkid_independent/independent_test.go
  state/transaction.go
Labels: cla-signed, zkevm-seq-agg

#3431 Cherry-pick #3401: Add gas per second estimation in metrics
  sequencer/finalizer.go
  sequencer/metrics.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#3432 Cherry-pick #3430: Fix keep empty RPC.SequencerNodeURI config parameter to get node URI from the SC
  config/environments/cardona/node.config.toml
  config/environments/mainnet/node.config.toml
  config/environments/testnet/node.config.toml
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#3436 generate receipt refactor
  state/helper.go
  state/runtime/runtime.go
  state/transaction.go
Labels: cla-signed, zkevm-seq-agg

#3438 Add state db migrations to store blobInner information
  db/migrations/state/0017.sql
  db/migrations/state/0017_test.go
Labels: cla-signed, zkevm-seq-agg

#3422 add log0 debug trace e2e tests
  test/contracts/auto/Log0.sol
  test/contracts/bin/Log0/Log0.go
  test/e2e/debug_calltracer_test.go
  test/e2e/debug_shared.go
  test/e2e/debug_test.go
Labels: cla-signed

#3424 Elderberry blockhash adjustments
  db/migrations/state/0017.sql
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/types/types.go
  proto/src/proto/executor/v1/executor.proto
  state/convertersV2.go
  state/datastream.go
  state/genesis.go
  state/helper.go
  state/interfaces.go
  state/mocks/mock_storage.go
  state/pgstatestorage/datastream.go
  state/pgstatestorage/l2block.go
  state/pgstatestorage/pgstatestorage_test.go
  state/pgstatestorage/transaction.go
  state/runtime/executor/errors.go
  state/runtime/executor/executor.pb.go
  state/runtime/runtime.go
  state/test/forkid_dragonfruit/dragonfruit_test.go
  state/test/forkid_independent/independent_test.go
  state/transaction.go
  state/types.go
Labels: cla-signed

#3437 update prover to v5.0.6
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed

#3445 L1 Synchronization process check some L2Blocks from TrustedNode
  cmd/run.go
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  synchronizer/actions/check_l2block.go
  synchronizer/actions/check_l2block_processor_decorator.go
  synchronizer/actions/check_l2block_test.go
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
  synchronizer/common/syncinterfaces/mocks/state_full_interface.go
  synchronizer/common/syncinterfaces/mocks/zkevm_client_get_l2_block_by_number.go
  synchronizer/common/syncinterfaces/mocks/zkevm_client_interface.go
  synchronizer/common/syncinterfaces/state.go
  synchronizer/common/syncinterfaces/zkevm_rpc.go
  synchronizer/config.go
  synchronizer/default_l1processors.go
  synchronizer/l2_sync/l2_shared/mocks/post_closed_batch_checker.go
  synchronizer/l2_sync/l2_shared/mocks/state_post_closed_batch_check_l2_block.go
  synchronizer/synchronizer.go
Labels: synchronizer, cla-signed, config, zkevm-bridge-sync-rpc

#3450 Use `defer rows.Close()`
  state/pgstatestorage/transaction.go
Labels: cla-signed

#3452 Synchronizer accept forkids that are the same as in database
  state/interfaces.go
  state/mocks/mock_storage.go
  state/pgstatestorage/forkid.go
  state/pgstatestorage/pgstatestorage_test.go
  synchronizer/actions/incaberry/processor_l1_forkid.go
  synchronizer/actions/incaberry/processor_l1_forkid_test.go
  synchronizer/common/syncinterfaces/mocks/state_full_interface.go
  synchronizer/common/syncinterfaces/state.go
  synchronizer/mocks/mock_dbtx.go
  test/Makefile
Labels: synchronizer, cla-signed, zkevm-bridge-sync-rpc

#3448 Elderberry blockhash adjustments (#3424)
  db/migrations/state/0017.sql
  db/migrations/state/0018.sql
  db/migrations/state/0018_test.go
  jsonrpc/endpoints_eth_test.go
  jsonrpc/endpoints_zkevm_test.go
  jsonrpc/types/types.go
  proto/src/proto/executor/v1/executor.proto
  state/convertersV2.go
  state/datastream.go
  state/genesis.go
  state/helper.go
  state/interfaces.go
  state/mocks/mock_storage.go
  state/pgstatestorage/datastream.go
  state/pgstatestorage/l2block.go
  state/pgstatestorage/pgstatestorage_test.go
  state/pgstatestorage/transaction.go
  state/runtime/executor/errors.go
  state/runtime/executor/executor.pb.go
  state/runtime/runtime.go
  state/test/forkid_dragonfruit/dragonfruit_test.go
  state/test/forkid_independent/independent_test.go
  state/transaction.go
  state/types.go
Labels: cla-signed

#3457 remove unnecessary eventlog call when estimating tx gas
  state/transaction.go
Labels: cla-signed

#3459 use empty byte array instead of all zeros for receipt poststate (#3449)
  jsonrpc/types/types.go
  state/helper.go
Labels: cla-signed

#3447 add log0 debug trace e2e tests (#3422)
  test/contracts/auto/Log0.sol
  test/contracts/bin/Log0/Log0.go
  test/e2e/debug_calltracer_test.go
  test/e2e/debug_shared.go
  test/e2e/debug_test.go
Labels: cla-signed

#3461 remove unnecessary eventlog call when estimating tx gas (#3457)
  state/transaction.go
Labels: cla-signed

#3466 cherry-pick from 0.6.3 #3443 synchronizer: fix bug closing a batch when sync from L1
  synchronizer/actions/etrog/processor_l1_sequence_batches.go
Labels: bug, synchronizer, cla-signed, cherry-pick, zkevm-bridge-sync-rpc

#3468 cherry pick: 3451 synchronizer accept old forkids
  state/interfaces.go
  state/mocks/mock_storage.go
  state/pgstatestorage/forkid.go
  state/pgstatestorage/pgstatestorage_test.go
  synchronizer/actions/incaberry/processor_l1_forkid.go
  synchronizer/actions/incaberry/processor_l1_forkid_test.go
  synchronizer/common/syncinterfaces/mocks/state_full_interface.go
  synchronizer/common/syncinterfaces/mocks/sync_pre_rollup_syncer.go
  synchronizer/common/syncinterfaces/state.go
  synchronizer/mocks/mock_dbtx.go
  test/Makefile
Labels: synchronizer, cla-signed, cherry-pick, zkevm-bridge-sync-rpc

#3467 cherry-pick: L1 Synchronization process check some L2Blocks from TrustedNode #3445
  cmd/run.go
  config/default.go
  docs/config-file/node-config-doc.html
  docs/config-file/node-config-doc.md
  docs/config-file/node-config-schema.json
  synchronizer/actions/check_l2block.go
  synchronizer/actions/check_l2block_processor_decorator.go
  synchronizer/actions/check_l2block_test.go
  synchronizer/common/syncinterfaces/mocks/state_full_interface.go
  synchronizer/common/syncinterfaces/mocks/zkevm_client_get_l2_block_by_number.go
  synchronizer/common/syncinterfaces/mocks/zkevm_client_interface.go
  synchronizer/common/syncinterfaces/state.go
  synchronizer/common/syncinterfaces/zkevm_rpc.go
  synchronizer/config.go
  synchronizer/default_l1processors.go
  synchronizer/l2_sync/l2_shared/mocks/post_closed_batch_checker.go
  synchronizer/l2_sync/l2_shared/mocks/state_post_closed_batch_check_l2_block.go
  synchronizer/synchronizer.go
Labels: synchronizer, cla-signed, config, cherry-pick, zkevm-bridge-sync-rpc

#3469 fix debug trace for injected tx
  state/trace.go
  test/e2e/debug_test.go
Labels: cla-signed

#3471 update prover version and set global var to allow it to run on mac M1
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed

#3473 fix debug trace for injected tx (#3469)
  state/trace.go
  test/e2e/debug_test.go
Labels: cla-signed

#3481 Update Prover image to v5.0.9
  docker-compose.yml
  test/docker-compose.yml
Labels: cla-signed, cherry-picked, zkevm-seq-agg

#3482 Cherry-pick #3480: Add sanity-check on checkL1InfoTreeUpdate to check state L1 blockhash matches ethereum blockhash (L1 reorg check)
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/mock_etherman.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg

#3483 fix OOC check
  state/batchV2.go
Labels: cla-signed

#3484 Fix ooc 2
  state/batchV2.go
Labels: cla-signed

#3487 fix tx index during debug transaction
  state/trace.go
Labels: cla-signed

#3489 Revert "fix tx index during debug transaction"
  state/trace.go
Labels: cla-signed

#3490 fix debug trace receipt index
  state/trace.go
Labels: cla-signed

#3492 Fix case you want to proof a 0
  aggregator/aggregator.go
  l1infotree/tree.go
Labels: cla-signed

#3491 fix aggregator l1 info tree
  aggregator/aggregator.go
  docker-compose.yml
  l1infotree/tree.go
  test/docker-compose.yml
Labels: cla-signed

#3480 Add sanity-check on checkL1InfoTreeUpdate to check state L1 blockhash matches ethereum blockhash (L1 reorg check)
  docker-compose.yml
  sequencer/finalizer.go
  sequencer/interfaces.go
  sequencer/mock_etherman.go
  test/docker-compose.yml
Labels: cla-signed, cherry-picked, zkevm-seq-agg

#3496 support forkid 9
  state/forkid.go
  synchronizer/actions/forksids.go
  synchronizer/synchronizer.go
Labels: cla-signed

#3488 fix tx index calculation on receipt
  state/transaction.go
Labels: cla-signed

#3495 fix aggregator l1 info tree (#3490) (#3491) (#3484)
  aggregator/aggregator.go
  docker-compose.yml
  l1infotree/tree.go
  state/batchV2.go
  state/trace.go
  state/transaction.go
  test/docker-compose.yml
Labels: cla-signed, cherry-pick

#3503 fix debug trace to compute egp percentage based on tx execution values
  jsonrpc/endpoints_zkevm.go
  jsonrpc/mocks/mock_pool.go
  jsonrpc/types/interfaces.go
  pool/effectivegasprice.go
  pool/effectivegasprice_test.go
  pool/pool.go
  sequencer/finalizer.go
  state/effectivegasprice.go
  state/helper.go
  state/trace.go
Labels: cla-signed

#3500 Cherry-pick #3488: fix tx index calculation on receipt
  state/transaction.go
Labels: cla-signed, cherry-pick, zkevm-seq-agg
